# -*- coding: utf-8 -*-
"""
Currículo oficial del Bachillerato en Artes — Mención Teatro — MINERD
Extraído del Plan de Estudios oficial de la Dirección de Modalidad en Artes.
Segundo Ciclo del Nivel Secundario (4to, 5to, 6to).
"""

CURRICULUM_TEATRO = {
    'Identidad, Cultura y Emprendimiento': {
        'modulo': 'Bachillerato en Artes — Mención Teatro',
        'horas': '4',
        'elemento_competencia': 'Comunica su identidad personal y social a través de un proyecto emprendedor para satisfacer una necesidad de desarrollo cultural en su comunidad y obtener ingresos económicos por ello, siguiendo las normas de redacción, autenticidad, y los criterios establecidos en el área respecto a sus componentes haciendo énfasis en su viabilidad.',
        'rae': ['Identifica los rasgos de la personalidad, y su proyección como estudiante de la modalidad en Artes tomando en cuenta las normas del actuar en esta modalidad.', 'Argumenta el papel de la cultura y el arte en la sociedad y en el mundo.', 'Comunica sus ideas y sentimientos haciendo un uso efectivo de las técnicas, tecnologías y medios de comunicación de la actualidad.', 'Analiza las fortalezas de su personalidad y de su expresividad, en favor de la proyección de una imagen coherente de sí mismo y de los logros de un plan personal.', 'Realiza presentación audiovisual con estrategias aplicadas a la Web 2.0 donde expresa por sí mismo, sus sueños, fortalezas y retos en el marco del aprendizaje de las artes y de su vida.', 'Argumenta las características del emprendedor cultural.', 'Identifica las áreas de industrias culturales en República Dominicana y las oportunidades de establecer una empresa cultural.', 'Elabora planificación preliminar de un proyecto cultural sencillo, en base a determinadas normas de redacción, siguiendo los criterios establecidos en el área respecto a sus componentes y haciendo énfasis en su viabilidad.', 'Aplica hoja de cálculo Excel para calcular el presupuesto del proyecto.'],
        'conceptuales': ['I. La Cultura en un mundo mediatizado II. El ser humano en el contexto de su cultura III. Comunicación verbal y no verbal IV. Auto-concepto e identidad personal V. Identidad social: normas del actuar de los estudiantes de la modalidad en Artes. Relación del estudiante con su comunidad y familia, rasgos de los jóvenes, de su región, nación y contexto global. VI. Emprendimiento cultural. VII. Planeación de proyectos artísticos. VIII. Industrias artísticas locales dominicanas.'],
        'procedimentales': ['Utiliza correctamente el español de forma verbal y escrita según la situación de comunicación.', 'Utiliza recursos expresivos corporales y audiovisuales para la comunicación.', 'Emplea las redes sociales para comunicar la identidad, el arte y la cultura.', 'Realiza análisis simples estilo FODA.', 'Planea proyectos productivos preliminares.'],
        'actitudinales': ['Valora los rasgos personales.', 'Autenticidad.', 'Respeto a la diversidad.', 'Actitud emprendedora y responsable.'],
    },
    'Lenguaje Musical': {
        'modulo': 'Bachillerato en Artes — Mención Teatro',
        'horas': '2',
        'elemento_competencia': 'Reproduce audio-visualmente los términos, signos y demás componentes del lenguaje musical relacionados con las cualidades del sonido ayudando al desarrollo del oído musical para complementar el estudio integral de otros perfiles artísticos.',
        'rae': ['Reconoce e identifica audio-visualmente los símbolos, grafías y otros elementos del lenguaje musical en partituras y/o fragmentos musicales.', 'Analiza y reproduce escrita y oralmente melodías, ritmos y piezas seleccionadas.', 'Reconoce audio-visualmente las combinaciones de sonidos en forma melódica como resultado del desarrollo del oído musical.', 'Reconoce auditivamente y reproduce oralmente cambios de intensidad en fragmentos melódicos.', 'Diferencia auditivamente los ritmos binarios y ternarios.'],
        'conceptuales': ['I. El sonido y sus cualidades: altura, duración e intensidad. II. Simbología melódica (sonidos) rítmicas (figuras). III. Lecto-escritura musical. IV. Altura. V. Registros, sonidos, claves de Sol y Fa en 4ta línea. VI. Intervalos melódicos de 2das y 3ras mayores y menores ascendentes y descendentes. VII. Las alteraciones. Distintos tipos y función. VIII. Armadura de clave (hasta 1 alteración). Orden de los sostenidos y los bemoles. IX. Duración. X. Métrica. Compases binarios y ternarios, simples (denominador 4 y 8) compases compuestos (denominador 8). XI. Ritmo. Figuras de notas y silencios. El puntillo. Valor absoluto y relativo de las figuras (desde la redonda hasta la corchea). Combinaciones rítmicas. Polirritmias. XII. Tempos: Moderato y Andante, Allegro y Adagio. XIII. Intensidad. XIV. Dinámica: matices de Piano (p), mezzopiano (mp), mezzoforte (mf) y Forte (f). Reguladores. XV. Signos de repetición: puntos o barras de repetición.'],
        'procedimentales': ['Reconoce audio-visualmente los signos y términos de la música.', 'Lee entonadamente un fragmento musical.', 'Entona y reconoce auditivamente escalas e intervalos.', 'Ejecuta ritmos y polirritmias.', 'Reconoce auditivamente ejercicios rítmicos y melódicos utilizando compases binarios y ternarios.'],
        'actitudinales': ['Demuestra actitud responsable y emprendedora.', 'Aplica creatividad en los trabajos que realiza.'],
    },
    'Lenguaje Danzario y Teatral': {
        'modulo': 'Bachillerato en Artes — Mención Teatro',
        'horas': '3',
        'elemento_competencia': 'Realiza la expresión artística a través de la danza y del teatro, de rasgos de su identidad de modo personal y colectivo, haciendo uso de elementos básicos del lenguaje de las artes escénicas, dando respuesta a los requerimientos escénicos y comunicativos predefinidos para el nivel medio de formación artística.',
        'rae': ['Argumenta el rol del lenguaje danzario y teatral en el devenir del desarrollo cultural de la humanidad.', 'Identifica los principales elementos presentes en el lenguaje corporal como: las expresiones mímicas, el gesto, la postura, la actitud física y las señales que se emiten con el cuerpo en la danza.', 'Valora los diferentes tipos de percepción del movimiento corporal: percepción corporal y sensorial, percepción espacial y audiokinética.', 'Interpreta o crea fragmentos sencillos de obras escénicas que incorporen la actuación y la danza haciendo uso de los elementos básicos de las técnicas teatral y danzaria.'],
        'conceptuales': ['I. Función social del teatro y la danza. II. El género en la danza. III. Los géneros teatrales. IV. Elementos básicos del lenguaje de la danza. V. Elementos básicos del lenguaje del teatro: personaje, texto dramático, conflicto, acción dramática, hechos, desenlaces, escenas, puestas en escena, escenografía, luces e indumentaria. VI. Técnicas elementales de interpretación de la danza clásica, moderna, contemporánea, folclórica y popular. VII. Técnicas elementales de interpretación del teatro para interpretación realista, distanciamiento y otras tendencias.'],
        'procedimentales': ['Enumera la función social del teatro y la danza en las distintas épocas.', 'Compara los contenidos y formas de diferentes géneros de la danza.', 'Describe las características de los principales géneros dramáticos: comedia, tragedia, drama.', 'Diferencia los géneros teatrales y danzarios de forma concisa.', 'Expresa de forma oral o escrita la idea básica de las técnicas de interpretación dramática y coreográfica.', 'Reconstruye cualidades de la percepción del movimiento corporal.', 'Interpreta o crea fragmentos cortos de danzas, folclóricas o contemporáneas, comunicando rasgos de su identidad.', 'Experimenta diversas formas de la representación dramática, improvisación y juego dramático.'],
        'actitudinales': ['Valora la función social del teatro.', 'Respeta las diferentes estéticas de las formas teatrales y danzarías.', 'Valora el uso del cuerpo y la voz como herramientas de expresión.', 'Valora el cuerpo como instrumento del bailarín.', 'Demuestra interés por la interpretación y concentración en el movimiento propio.', 'Comunica adecuadamente las ideas y el carácter de los personajes.', 'Participa cumpliendo con las indicaciones de la danza.', 'Aprecia el movimiento corporal a través del ritmo o la música.'],
    },
    'Lenguaje Visual y Artesanal': {
        'modulo': 'Bachillerato en Artes — Mención Teatro',
        'horas': '3',
        'elemento_competencia': 'Realiza la expresión artística a través de la integración de las artes visuales y las artesanías reflejando su identidad cultural en trabajos personales y colectivos, haciendo uso de los elementos básicos de los lenguajes visual y artesanal, mostrando sus funciones comunicativas, estéticas y utilitarias.',
        'rae': ['Argumenta el rol del lenguaje visual y artesanal y su evolución a través de la historia.', 'Identifica los principales elementos presentes en el lenguaje visual y artesanal como formas, estructuras, colores, texturas, figura-fondo, composición, luz y sombras, tamaños, escalas, equilibrios, unidad, variedad, materiales y formatos.', 'Analiza aspectos connotativos y denotativos de imágenes de diferentes estilos artísticos.', 'Elabora obras artísticas visuales y artesanales haciendo uso de los elementos básicos y técnicas.'],
        'conceptuales': ['I. Introducción a las artes visuales y las artesanías: conceptos, materiales, soportes, instrumentos y sus diferentes manifestaciones. II. Las artes visuales en distintas épocas y culturas y su rol en la actualidad (énfasis en República Dominicana). III. Las artesanías en distintas épocas y culturas y su rol en la actualidad (énfasis en República Dominicana). IV. Elementos básicos pertenecientes al lenguaje visual y artesanal (formas, estructuras, colores, espacialidades, materiales, formatos, soportes). V. Percepción visual, signos y símbolo (simbología taína): introducción a los aspectos connotativos y denotativos de la imagen u obra artística. VI. Elementos básicos de las técnicas de expresión visual y artesanal.'],
        'procedimentales': ['Identifica las diversas modalidades de las artes visuales y artesanías y su evolución histórica.', 'Percibe elementos del lenguaje visual.', 'Realiza el diseño de una imagen visual aplicando técnicas elementales.', 'Experimenta con técnicas y materiales artesanales.', 'Elabora obras artísticas visuales y artesanales haciendo uso de los elementos básicos y técnicas.'],
        'actitudinales': ['Asume las tareas con responsabilidad y disciplina.', 'Valora los aportes de las artes visuales y las artesanías en la época actual.'],
    },
    'Historia del Arte y Apreciación del Teatro Universal': {
        'modulo': 'Bachillerato en Artes — Mención Teatro',
        'horas': '4',
        'elemento_competencia': 'Reconoce los elementos del lenguaje teatral y su estética, e identifica las características de la dramaturgia, los géneros dramáticos y su desarrollo histórico universal, desde la Antigüedad hasta la modernidad, aplicando estos conocimientos de forma consciente en representaciones de fragmentos de obras teatrales sencillas.',
        'rae': ['Explica las funciones del teatro en la sociedad a través de las épocas.', 'Utiliza términos básicos del lenguaje teatral para apreciar el sentido de obras dramáticas y espectáculos.', 'Identifica las características fundamentales de las diferentes épocas por las que ha atravesado el desarrollo del teatro, desde la prehistoria, antigüedad, edad media, renacimiento, barroco, siglo XVIII, XIX, XX hasta el siglo XXI.', 'Compara las principales características y aportes en el teatro de las diferentes épocas.', 'Define las características de los diferentes géneros (tragedia, comedia, drama, farsa, tragicomedia) y otros teatrales.', 'Diferencia los términos género y estilo teatral.', 'Identifica los principales autores en las diferentes épocas.', 'Analiza cuatro obras dramáticas de diferentes géneros.', 'Realiza improvisaciones tomando en cuenta las características del teatro en una época determinada.', 'Improvisa en base a obras leídas de los diferentes géneros.', 'Realiza síntesis histórica del teatro universal con sus diferentes géneros y estilos.', 'Maneja con propiedad los elementos a tomar en cuenta para la valoración y crítica de una obra teatral.'],
        'conceptuales': ['I. Función del teatro en la sociedad. II. Glosario teatral. III. Características fundamentales de las épocas de la historia del teatro. IV. Aportes del teatro a través de las épocas. V. Géneros y estilos teatrales. VI. Principales autores de los diferentes géneros. VII. Apreciación teatral y crítica en el teatro.'],
        'procedimentales': ['Investiga las funciones del teatro en la sociedad.', 'Define glosario de conceptos y términos teatrales.', 'Establece la diferencia entre género y estilo teatral.', 'Realiza resumen en portafolio sobre los géneros teatrales y características.', 'Realiza mapa gráfico identificando autores, fecha y procedencia.', 'Realiza expresión dramática grupal sobre la evolución de las características del arte teatral.'],
        'actitudinales': ['Interés por la investigación.', 'Juicio crítico.', 'Laboriosidad.', 'Creatividad.'],
    },
    'Entrenamiento Rítmico, Corporal y Vocal I': {
        'modulo': 'Bachillerato en Artes — Mención Teatro',
        'horas': '3',
        'elemento_competencia': 'Desarrolla la expresión dramática del estudiante mediante el uso de los elementos fundamentales de la actuación, capacidades vocales, corporales y técnicas actorales, explorando su poder expresivo-creativo en la escena.',
        'rae': ['Define la expresión corporal comparándola con otras disciplinas corporales.', 'Diferencia la respiración abdominal de la torácica y clavicular.', 'Realiza rutinas de relajación, estiramiento y calentamiento del cuerpo en el espacio, utilizando técnicas de sensopercepción, eutonía, yoga y tai chi.', 'Reconoce los órganos fonadores y sus funciones para la emisión de la voz hablada y cantada.', 'Expresa con su cuerpo imágenes y sentimientos utilizando los elementos fundamentales de la expresión corporal: espacio, tiempo, movimiento e intensidad.', 'Articula correctamente frases y textos teatrales propios y ajenos proyectando su voz en el espacio, con una correcta dicción y expresividad.', 'Reconoce los distintos resonadores del cuerpo y los utiliza adecuadamente según las necesidades de la comunicación expresiva.'],
        'conceptuales': ['I. La expresión corporal: definición e historia. II. El cuerpo como recurso expresivo: gesto y movimiento. III. Niveles de altura, trayectoria, ritmos, peso del cuerpo en el espacio. IV. Conciencia corporal y diferentes métodos de relajación. V. Sensopercepción y eutonía, yoga, tai chi. VI. Composiciones corporales corales. Coro energético. VII. El sonido y sus cualidades: duración, timbre, intensidad, tono. VIII. El aparato fonador, sus componentes y funciones. IX. La respiración: abdominal, torácica y clavicular. X. Dicción, articulación y pronunciación. XI. Proyección vocal-corporal según Jerzy Grotowski.'],
        'procedimentales': ['Explica la importancia de la expresión corporal: definición, historia y corrientes.', 'Diferencia el gesto y el movimiento en los diferentes niveles de altura y calidades del movimiento.', 'Emplea el lenguaje corporal como medio de expresión no verbal a través de técnicas de sensopercepción, eutonía, yoga y tai chi.', 'Crea escenas corporales y gestuales individuales y en grupo utilizando el espacio escénico.', 'Emplea técnicas de relajación del cuerpo y la voz.', 'Reconoce los diferentes órganos del aparato fonador, sus funciones y cuidado.', 'Diferencia los distintos tipos de respiración.', 'Ejecuta ejercicios de dicción, articulación y pronunciación y reconoce los distintos resonadores corporales.', 'Articula correctamente las vocales y consonantes y se expresa correctamente dentro y fuera de escena.'],
        'actitudinales': ['Conciencia de la importancia del cuidado de su cuerpo y su voz para su desarrollo como actor.', 'Adquisición de normas expresivas.', 'Sensibilización ante los ejercicios pautados.', 'Respeto y disciplina ante el trabajo propio y ajeno.'],
    },
    'Caracterización de Personajes I': {
        'modulo': 'Bachillerato en Artes — Mención Teatro',
        'horas': '4',
        'elemento_competencia': 'Capacita al estudiante en el estudio de los elementos básicos, métodos y técnicas de actuación y caracterización de personajes, mediante la relación cuerpo-voz, psicología y movimientos escénicos, para representar y caracterizar ante el público fragmentos seleccionados de obras de los diferentes géneros de la dramaturgia nacional y universal.',
        'rae': ['Aplica fundamentos de improvisación, se introduce a técnicas de actuación mediante movimiento escénico, expresión oral, corporal, interpretación y conflictos psicológicos, memoria dialógica, improvisación y espontaneidad en la expresión dramática y creativa teatral.', 'Argumenta sobre fundamentos, métodos y técnicas de caracterización de personaje teatral.', 'Improvisa personajes con espontaneidad y creatividad.', 'Caracteriza la psicología de personajes en la representación de fragmentos de obras de la dramaturgia nacional y universal.', 'Elabora procesos de creación de diferentes roles de caracterización del personaje teatral.', 'Realiza presentación dramática de caracterización de personajes.', 'Utiliza contexto, psicología y situación de la obra para la caracterización del personaje de la dramaturgia nacional y universal.', 'Elabora proyecto de caracterización y psicología teatral creativa-social.', 'Muestra conflicto psicológico y líneas internas y externas en caracterización del personaje.', 'Adopta espontaneidad, proyecta voz, gestualidad y movimientos propios del personaje en actuación.', 'Caracteriza personajes en fragmentos de obras de la dramaturgia nacional y universal.'],
        'conceptuales': ['I. La improvisación teatral creativa. II. Fundamentos de la caracterización de personaje teatral. III. Historia de la Psicología y caracterización del personaje. IV. Contexto, psicología y situación del personaje en la obra. V. Orientación social y humana del personaje. Sociedad – Cultura. VI. Entrenamiento psicotécnico en expresión creativa, corporal, vocal y movimiento. VII. Caracterización de personajes destacando relación cuerpo-voz-movimiento escénico.'],
        'procedimentales': ['Aplica características creativas y espontáneas en la improvisación de personajes reales o imaginarios.', 'Identifica fundamentos, métodos y técnicas de caracterización de personaje teatral.', 'Utiliza contexto, psicología y situación de la obra para la caracterización del personaje.', 'Muestra conflicto psicológico, líneas internas y externas en caracterización del personaje.', 'Adopta y proyecta voz, gestualidad y movimientos propios del personaje en actuación.', 'Caracteriza personajes en fragmentos de obras de la dramaturgia nacional y universal.'],
        'actitudinales': ['Muestra actitud responsable en la función de actor de teatro frente a la sociedad.', 'Asume responsabilidad y compromiso del actor con el personaje y su situación psicológica.', 'Asume compromiso ético en la función del teatro y el desarrollo cultural de la comunidad.'],
    },
    'Apreciación del Teatro Latinoamericano, Dominicano y su Dramaturgia': {
        'modulo': 'Bachillerato en Artes — Mención Teatro',
        'horas': '4',
        'elemento_competencia': 'El estudiante aprecia, define, argumenta y aplica los disímiles elementos del lenguaje teatral y su estética contemporánea del teatro latinoamericano y dominicano. Ilustra la interpretación de métodos, técnicas, términos, lenguaje y la apreciación de la dramaturgia universal; reconociendo sus características por medio de la dramaturgia dominicana y latinoamericana actual, empleando su valoración por la asistencia a obras teatrales, lecturas de textos teatrales, biografías de dramaturgos, análisis de textos, investigación de acontecimientos relevantes y la representación de obras de nuestra cultura y del teatro latinoamericano.',
        'rae': ['Identifica los diferentes estilos literarios utilizados por los dramaturgos latinoamericanos.', 'Explica el rol del teatro en la colonización de América por parte de los europeos.', 'Describe los diferentes cambios sociales experimentados en América Latina durante los pasados cinco siglos.', 'Compara el avance teatral en las diferentes naciones de América Latina.', 'Explica el proceso evolutivo de la nación dominicana de acuerdo a la conformación y desarrollo de los acontecimientos teatrales de su historia.', 'Dramatiza piezas teatrales basadas en los conocimientos adquiridos en esta competencia.', 'Realiza charlas explicativas acerca de diversos temas, entre ellos la fusión de las culturas europeas, africanas e indígenas.', 'Redacta ensayos y artículos cuyo contenido verse sobre el teatro en América Latina y en República Dominicana.'],
        'conceptuales': ['I. Términos autóctonos de la cultura latinoamericana (aborigen y contemporánea). II. Evolución y desarrollo de los pueblos latinoamericanos. III. Conocimiento de la cultura general dominicana. IV. Conocimiento dramatúrgico latinoamericano. V. Conversatorios, charlas o actividades de aprendizaje cultural.'],
        'procedimentales': ['Realización de escritos y proyectos de investigación cultural comunitarios, nacionales o internacionales.', 'Análisis del comportamiento humano en demarcaciones geográficas de cualquier dimensión.', 'Argumenta sobre la cultura teatral latinoamericana, dominicana y su dramaturgia.', 'Planea actividades culturales con actitud motivadora, creativa e integradora.'],
        'actitudinales': ['Ámbito pedagógico.', 'Promoción turística y cultural.', 'Proyectos de carácter sociológico.', 'Actitud emprendedora, observadora, analítica, comprometedora y responsable.'],
    },
    'Entrenamiento Rítmico, Corporal y Vocal II': {
        'modulo': 'Bachillerato en Artes — Mención Teatro',
        'horas': '4',
        'elemento_competencia': 'Desarrolla la expresión dramática del estudiante mediante el conocimiento de los elementos fundamentales de la actuación, capacidades vocales, corporales, técnicas actorales, explorando su poder expresivo-creativo en la escena.',
        'rae': ['Reconoce las afecciones de la voz del actor.', 'Identifica los mecanismos necesarios para el cuidado y la salud de la voz.', 'Reconoce auditivamente los distintos tipos de voces y sus registros.', 'Crea personajes modificando su voz e incorporando el estilo de habla del mismo en improvisaciones o escenas.', 'Reconoce los modos corporales de las diferentes técnicas o estilos teatrales: sombra, mimo, clown, bufón.', 'Incorpora a su rutina de entrenamiento corporal elementos característicos de las técnicas de Grotowsky, Meyerhold y Eugenio Barba.', 'Crea escenas grupales o individuales originales o adaptaciones utilizando el lenguaje corporal de manera expresiva y creativa.'],
        'conceptuales': ['I. La voz del actor: cuidado y salud vocal. II. Tesitura: clasificación de la voz humana. III. La impostación vocal. IV. La construcción de la voz en el personaje. Método de Stanislavski. V. La expresividad corporal en el teatro de sombras, máscaras, mimo, clown y bufón. VI. El «training» corporal en el teatro pobre de Jerzy Grotowski. VII. La biomecánica de Meyerhold. VIII. La antropología teatral: Eugenio Barba. IX. Trabajo corporal con máscaras: neutra, larvaria y expresiva. Comedia del arte. X. Creación colectiva de espectáculos.'],
        'procedimentales': ['Reconoce los mecanismos para cuidar y proteger su instrumento vocal.', 'Diferencia los distintos tipos de voces femeninas y masculinas.', 'Amplía la proyección vocal a través de la impostación.', 'Construye personajes a través del trabajo vocal.', 'Modifica su cuerpo y su energía de acuerdo a las distintas técnicas y modalidades teatrales.', 'Reconoce las técnicas originales creadas por Jerzy Grotowski para el entrenamiento actoral en su Teatro Laboratorio.', 'Incorpora a su entrenamiento personal componentes de la biomecánica: la intención, la realización y reacción según Meyerhold.', 'Incorpora en su entrenamiento personal los elementos de la antropología teatral: equilibrio precario, cuerpo dilatado, pre-expresividad.', 'Se expresa con su cuerpo utilizando diferentes tipos de máscaras.', 'Crea escenas u obras utilizando el lenguaje corporal adecuado en forma individual o colectiva.'],
        'actitudinales': ['Conciencia de la importancia del cuidado de su cuerpo y su voz para su desarrollo como actor.', 'Buen uso y cuidado de su instrumento vocal y corporal.', 'Adquisición de normas expresivas.', 'Sensibilización ante los ejercicios pautados.', 'Respeto y disciplina ante el trabajo propio y ajeno.', 'Compromiso en su búsqueda personal expresiva y creativa.'],
    },
    'Caracterización de Personajes II': {
        'modulo': 'Bachillerato en Artes — Mención Teatro',
        'horas': '6',
        'elemento_competencia': 'Aplica técnicas de actuación mediante la relación cuerpo-voz para llevar a cabo desde la propuesta metódica y técnica del método de interpretación de Stanislavsky que le permitan y faciliten ejecutar acciones desde la línea de acción, la psicología y las circunstancias dadas del actor-personaje a partir de los métodos de Brecht, Grotowsky y Barba y explora diversas técnicas de teatro-danza para adquirir formas interpretativas dramáticas de acuerdo a los requerimientos del personaje y el guión.',
        'rae': ['Aplica el método de actuación de Stanislavsky para el análisis y representación de personajes haciendo uso de sus recursos expresivos (cuerpo y voz) y en interacción con los demás personajes de la escena.', 'Investiga y describe quién fue Stanislavsky, su aporte al arte y técnica del actor y las distintas derivaciones de su método.', 'Analiza un personaje en su contexto literario y dramático y en relación con el género y estilo del relato, escena u obra en la que existe.', 'Aplica creativamente los conceptos: acciones físicas, objetivo, circunstancias dadas, en la representación de escenas o fragmentos de obras.', 'Recapitula y recrea situaciones para generar estados emocionales.', 'Representa personajes diversos con seguridad, soltura, expresividad y verosimilitud.', 'Aplica distintos métodos de actuación para el análisis y representación de personajes haciendo uso de sus recursos expresivos (cuerpo y voz) y en correspondencia con el estilo particular de las diferentes escuelas.', 'Describe los fundamentos de las principales escuelas de actuación (Brecht, Grotowsky, Barba), en la teoría y en la práctica, que divergen del método Stanislavsky.', 'Distingue el estilo de actuación empleado en un montaje teatral, de acuerdo a las diferentes escuelas de actuación.', 'Aplica los métodos de entrenamiento y preparación propios de cada escuela de actuación estudiada.', 'Actúa y representa según distintos estilos o escuelas utilizando sus recursos expresivos (cuerpo y voz) de modo coherente con el estilo elegido.', 'Distingue y aprecia las manifestaciones de cada escuela de actuación en nuestro país y conoce a sus representantes más destacados.', 'Elige un método de actuación preferido y justifica su elección de modo coherente y bien fundamentado.'],
        'conceptuales': ['I. Stanislavsky y sus aportes al arte de la actuación. II. La acción como modo de existencia del personaje: relación indisoluble Personaje-Acción. III. Método de las acciones físicas: la acción dramática como búsqueda física de un objetivo. IV. Objetivos, obstáculos y circunstancias dadas. V. Memoria emotiva. VI. Caracterización: elementos físicos y de comportamiento que individualizan al personaje. Bertolt Brecht, su vida y su obra / El teatro épico. VII. La actuación en el teatro épico (Brecht). VIII. El distanciamiento. IX. El gesto social. X. Jerzy Grotowsky y el «teatro pobre»: sus antecedentes y fundamentos. XI. La actuación en el teatro pobre (Grotowsky). XII. La búsqueda de la expresión pura del actor mediante la eliminación de todo lo accesorio. XIII. El actor «sagrado». XIV. Eugenio Barba y el teatro antropológico: la búsqueda de los orígenes. XV. La actuación en el teatro antropológico (Barba). XVI. Situaciones de representación. XVII. «Bios» escénico. XVIII. Comportamiento pre-expresivo. XIX. Presencia extra-cotidiana. XX. Tensión y desequilibrio. XXI. Aproximación al teatro-danza.'],
        'procedimentales': ['Investiga la vida y obra de Konstantin Stanislavsky.', 'Analiza un personaje en su contexto y en relación con los demás personajes del relato escénico.', 'Aplica el método de las acciones físicas como herramienta fundamental de su práctica actoral, haciendo énfasis en las acciones más que en la «psicología» del personaje.', 'Descompone una acción dramática en sus elementos: el objetivo que persigue respecto a los demás personajes de la escena, y las circunstancias (imaginarias y escénicas) en cuyo contexto se desarrolla la búsqueda de dicho objetivo.', 'Distingue en el enfoque y en la práctica las improvisaciones de las representaciones fijadas y con un texto preestablecido.', 'Incorpora al personaje características físicas, vocales y de comportamiento (modo de caminar, de hablar, ritmo, etc.) coherentes con las circunstancias dadas y la acción dramática que se desarrolla en la escena.', 'Utiliza, con el debido cuidado, experiencias sensoriales pasadas para despertar determinados estados emocionales necesarios para la representación.', 'Analiza los aportes de cada uno de los maestros citados (Brecht, Grotowsky, Barba) y sus relaciones/diferencias con el método de Stanislavsky.', 'Representa fragmentos de obras según los distintos estilos de actuación y aprecia sus diferencias en la práctica, tanto en sí mismo como en la observación de los demás compañeros.', 'Experimenta los distintos métodos de entrenamiento y preparación correspondientes a cada escuela o método estudiado.', 'Confronta con sentido crítico la teoría y la práctica, los pros y los contras de cada escuela y su pertinencia en nuestro contexto social y cultural.', 'Identifica las manifestaciones de cada estilo en nuestro país y a sus representantes más destacados.'],
        'actitudinales': ['Valora el aporte fundamental de Stanislavsky a la técnica del actor.', 'Enfrenta el análisis y representación de personajes con rigor y disciplina, evitando el facilismo y la simple intuición.', 'Reconoce su práctica actoral como parte de un conjunto y mantiene una actitud de interacción positiva y de colaboración con sus demás compañeros de escena, evitando el individualismo, el egoísmo y el «divismo».', 'Mantiene, en cada momento de la búsqueda, las improvisaciones o la representación, una actitud de juego creativo, disfrutando cada etapa y evitando un excesivo involucramiento emocional que puede ser dañino.', 'Valora la actuación y el teatro en general como un ejercicio estético que no se agota en sí mismo, sino que es útil y positivo para la comunidad.', 'Concentración, entrega, disciplina y sinceridad.', 'Aprecia la gran variedad de estilos, escuelas y tendencias del teatro como expresión de la infinita riqueza de este arte.', 'Valora los aportes de las distintas escuelas de interpretación, sus técnicas y sus métodos, sus puntos de coincidencia y de divergencia.', 'Opta por un estilo y un enfoque de interpretación preferido acorde con nuestras posibilidades y características como sociedad, enriquecido con los aportes de las otras escuelas y tendencias.'],
    },
    'Recursos Actorales para la Creación de obras Infantiles y Juveniles (Títeres)': {
        'modulo': 'Bachillerato en Artes — Mención Teatro',
        'horas': '6',
        'elemento_competencia': 'Utiliza los títeres para desarrollar contenidos teatrales y propuestas creativas para espectáculos infantiles y animación de eventos juveniles.',
        'rae': ['Identifica el teatro de títeres como recurso en el teatro infantil y juvenil.', 'Define títere y teatro de títeres.', 'Reconoce la historia del teatro de títeres universal y dominicana.', 'Aplica y relaciona la técnica y los mecanismos de construcción de títeres simples y reciclados como: títere plano, títere de sombra, títere de cono, títere de varilla, marioneta simple, títere de dedos, títere de mano, títere de boca, títere de guante.', 'Integra los personajes del folclor y popular a la construcción de títeres simples y reciclados.', 'Maneja de forma apropiada títeres de guante, plano, boca y marioneta simple.', 'Reconoce la titiriturgia dominicana y universal.', 'Organiza el espectáculo infantil y juvenil siguiendo el patrón de montaje e integrando el teatro de actores y el teatro de títeres.', 'Construye teatrino según los requerimientos del espectáculo infantil y juvenil.', 'Presenta espectáculo infantil y juvenil con teatro de actores y teatro de títeres.', 'Incorpora las TIC al teatro de títeres.'],
        'conceptuales': ['I. Títeres como recurso en el teatro infantil y juvenil de acuerdo al tipo de público. II. Definiciones de títere y teatro de títeres. III. La historia del teatro de títeres universal y dominicana. IV. Personajes del folclor y populares en las obras de teatro infantil y juvenil. V. Clasificación y tipos de títeres. VI. Titiriturgia dominicana y universal. VII. Técnicas de manejo de títeres. VIII. Estructuras y mecanismos de títeres. IX. Técnicas de títeres con materiales simples y reciclados. X. Técnicas de construcción y manejo de títeres de guante. XI. Técnicas y construcción de teatrinos. XII. Montaje de espectáculo de teatro de títeres. XIII. Las TIC en el teatro de títeres.'],
        'procedimentales': ['Usa las técnicas de animación infantil y juvenil.', 'Define el teatro de títeres.', 'Reconoce las distintas etapas de la historia de los títeres tanto universal como dominicana.', 'Reconoce los personajes del folclor y popular.', 'Identifica las distintas clasificaciones y tipos de títeres desde sus estructuras y mecanismos.', 'Utiliza titiriturgia dominicana y universal.', 'Maneja las técnicas de los títeres de guante y otras técnicas de títeres simples.', 'Construye títeres de guante y teatrinos.', 'Realiza espectáculo de teatro de títeres siguiendo el patrón de montaje.', 'Utiliza las TIC en el teatro de títeres.'],
        'actitudinales': ['Se interesa por el trabajo en equipo.', 'Tolera a sus compañeros.', 'Cumple con las normas del teatro de títeres.', 'Se esfuerza para aplicar los conocimientos de ritmo tomando en cuenta el manejo de movimiento en sintonía con la expresión vocal.', 'Acepta las correcciones técnicas y de actitud frente al trabajo.'],
    },
    'Fundamentos de Escenografía e Iluminación': {
        'modulo': 'Bachillerato en Artes — Mención Teatro',
        'horas': '3',
        'elemento_competencia': 'Aplica los componentes fundamentales de escenografía, la utilería, los tipos de luces y su colocación y colores, coherentes entre sí y con el resto de los elementos de producción, para crear un ambiente adecuado con sentido artístico y viable de realizar si fuera necesario.',
        'rae': ['Aplica los principios básicos del diseño de escenografía, gestionando las piezas de la misma en calidad de préstamo o construyéndolas, así como la colocación de las luces, su posición, intensidad y colorido de acuerdo al ambiente o simbolismo de la obra.', 'Escoge, compone y organiza escenografías con los elementos necesarios al alcance, según el estilo decidido por el profesor.', 'Diseña y confecciona con materiales desechables un acercamiento a piezas de utilería y complementos de escenografía de épocas que son hitos de la historia del teatro universal.', 'Diseña la iluminación y sus colores en armonía con la escenografía y el estilo, concebidos con sentido artístico y trabajo en equipo.'],
        'conceptuales': ['Modelos históricos de espacios teatrales, sus partes y componentes escenográficos. La escenografía del teatro a la italiana. Teatros flexibles o múltiples. Relación de la escenografía con el espectador en los diferentes espacios. Diferenciación y clasificación de los espacios del escenario a la italiana: escenario y sus partes, foso, laterales, locales de servicio, retro escena, caja escénica y sus componentes, el vestido escénico (cámara negra, telones), elementos escenográficos fundamentales, practicables.', 'Breve recuento histórico de la iluminación en el teatro. Diferencia y descripción de los distintos tipos de aparatos lumínicos, sus usos y partes. Breve introducción al uso de la electricidad: uso, buenas prácticas, riesgos y prevención. Tipos de focos básicos (bombillas de uso hogar, bombillos y extensiones navideñas, lámpara incandescente y fluorescente) y focos dentro del espectáculo (panorama o cuarzo, PAR 64/56/42/24, P.C., fresnel, recortes, cañones de seguimiento o perseguidores, focos móviles y lentes, halógenas, luces LED, gelatina, mascarilla y gobos). La consola: análoga y digital. Los dimmers. Planteamiento de proyecto de iluminación con efectos específicos: procedencia de la luz según posición de la fuente (frontal, lateral, rasante, contrapicado, cenital o ducha, contraluz). Significado del color para crear ambientes y sugerir horas del día o temperaturas.'],
        'procedimentales': ['Elabora de manera básica diferentes modelos o maquetas de la relación entre escenario, actores y espectadores-platea.', 'Reconoce en esos ejemplos las técnicas de escenografía y la arquitectura como escenografía.', 'Utiliza los colores, materiales y texturas para realzar los elementos de la escenografía escogidos o diseñados.', 'Emplea y/o confecciona elementos de utilería de acuerdo a la obra, el estilo y el tipo de personajes y de escenografía requerida.', 'Reconoce, en una visita a un teatro, las partes aprendidas del escenario a la italiana.', 'Construye en cartón un modelo detallado de un escenario a la italiana.', 'Realiza maquetas con cartón, papel, cartulina y elementos recortados para diferenciar cada elemento y su aplicación.', 'Diseña, realiza y dibuja collage de las piezas escenográficas descritas.', 'Identifica los diferentes equipos básicos del escenario y los distintos tipos de foco lumínico y sus piezas.', 'Practica e interpreta un plano de iluminación y su simbología.', 'Practica cambios de colores y posición de las luces en el espacio respecto a los objetos y los personajes.', 'Practica con diferentes efectos lumínicos, siluetas y gobos.'],
        'actitudinales': ['Desarrolla la mirada y el sentido de la composición y del espacio mediante ejercicios comparativos.', 'Aprecia mediante imágenes en fotos y en visitas guiadas la importancia del patrimonio teatral dominicano y sus diferentes espacios.', 'Valora nuestras principales salas teatrales como lugares para la representación de sus trabajos y con visión de meta futura.', 'Dinamiza el grupo con actitudes de motivación de la creatividad y el trabajo conjunto en equipo.', 'Desarrolla la observación, el juicio crítico y la atención al detalle.', 'Cuidado y esmero al manipular los diferentes focos y su uso.', 'Cuidado y conciencia al trabajar con electricidad, utilizando la prevención adecuada.'],
    },
    'Recursos Actorales para la Creación de Espectáculos Turísticos y Público en General': {
        'modulo': 'Bachillerato en Artes — Mención Teatro',
        'horas': '4',
        'elemento_competencia': 'Utiliza las técnicas circenses y de calle como el clown, mimo, acrobacia y zanco para desarrollar animación creativa para los espectáculos turísticos y público general.',
        'rae': ['Aplica técnicas corporales como un instrumento escénico.', 'Aplica la técnica vocal de respiración, dicción, colocación, proyección y articulación en cada interpretación.', 'Diferencia el circo y el teatro de calle y los elementos que lo componen: clown, mimo, acrobacia (malabares o danza aérea o telas), zanco.', 'Argumenta sobre la historia del circo y el teatro de calle universal y dominicano.', 'Interpreta con seguridad los personajes desde las técnicas del clown, mimo, acrobacia (malabares, danza aérea, telas) y zanco.', 'Aplica el espectáculo circense y de calle con fines turísticos y público general con el empleo de las técnicas clown, mimo, acrobacia y zanco.', 'Explica sobre el desmontaje de espectáculo para circo y teatro de calle.', 'Muestra la aplicación de las TIC del circo y teatro de calle.'],
        'conceptuales': ['I. Fundamentos de circo y teatro de calle universal y dominicano. II. Etapas de la historia del circo y teatro de calle universal y dominicano. III. Estructura y funcionamiento de clown, mimo, acrobacia (malabares o danza aérea o telas) y zanco. IV. Definiciones y fundamentos técnicos de clown, mimo, acrobacia y zanco. V. Disposición corporal para el clown, mimo, acrobacia y zanco. VI. El espectáculo circense y teatro de calle siguiendo modelos y patrones generales. VII. Las TIC (iluminación, sonorización, mecánicas escénicas, proyección, técnica de proyección Mapping) en el circo y teatro de calle.'],
        'procedimentales': ['Reconoce la historia del circo y el teatro de calle universal y dominicano.', 'Fundamenta las diferencias entre circo y teatro de calle.', 'Describe estructura, técnica y fundamento de clown, mimo, acrobacia y zanco.', 'Utiliza de forma correcta el cuerpo escénico en función de las técnicas de clown, mimo, acrobacia y zanco.', 'Realiza espectáculo turístico y público general con el empleo de las técnicas clown, mimo, acrobacia y zanco.', 'Utiliza las TIC (iluminación, sonorización, mecánicas escénicas, proyección, técnica de proyección Mapping) en el circo y teatro de calle.'],
        'actitudinales': ['Actitud responsable y emprendedora.', 'Confianza y respeto al resolver problemas técnicos y escénicos.', 'Perseverancia en la búsqueda de eficiencia colectiva.', 'Decisión y prudencia en los desafíos que implican compromisos corporales y motrices.', 'Solidaridad con los otros en las prácticas corporales.', 'Valoración de la precisión en el movimiento.', 'Tolera a sus compañeros.', 'Cumple con las normas preestablecidas.', 'Esfuerzo por aplicar los conocimientos.', 'Acepta las correcciones técnicas y de actitud frente al trabajo.', 'Creatividad en la búsqueda de soluciones a problemas de movimiento.', 'Gusto por el trabajo autónomo y por el trabajo con otros.', 'Cuidado de la expresión corporal propia y consideración responsable de la ajena.'],
    },
    'Actuación para Cine': {
        'modulo': 'Bachillerato en Artes — Mención Teatro',
        'horas': '4',
        'elemento_competencia': 'Actúa según las especificaciones del cine y la TV, caracterizando los modos y registros técnicos de la actuación, logrando la realización verosímil de los personajes que interprete.',
        'rae': ['Expresa verosimilitud en la interpretación del personaje cinematográfico en un corto.', 'Desarrolla las capacidades básicas para la producción de cine: elaboración y ejecución del cronograma de rodaje y desglose de guión.', 'Aplica las aptitudes fundamentales para la dirección y realización de proyectos de cortometrajes.', 'Realiza actuación dinámica, utilizando el método empleado en Actor Studio y el método del actor clown y de la actuación gimnástica.'],
        'conceptuales': ['I. Estética de la actuación fílmica. II. Nociones básicas de la técnica cinematográfica necesaria para la actuación frente a cámara: acciones físicas, línea de pensamiento, mirada y la actuación en los distintos planos (generales, medios y primeros planos). III. Diferencia entre actuación para teatro, cine y televisión, ejercicios prácticos. IV. La improvisación como base fundamental para el entrenamiento actoral. V. La fotografía, encuadre, composición y tipos de planos. VI. Especificaciones técnicas de los aparatos fílmicos. VII. Principios básicos de la estructura dramática y guión. VIII. Trabajo de mesa: circunstancias, arco dramático, objetivos y conflicto. Búsqueda del subtexto. IX. Características del guion literario y fílmico. X. Análisis de escenas de largometrajes, series de ficción y entrevistas desde el punto de vista de la construcción dramática. XI. Introducción a la construcción de personajes: aspectos físicos y síquicos. Experiencia, observación, documentación e imaginación. XII. Producción y rodaje: conceptos de producción y las funciones que se deben cubrir en un rodaje. XIII. Dirección y realización: trabajo escrito sobre la puesta en escena, la acción dramática como eje central, la fotografía, encuadre y composición en función del valor dramático. XIV. El trabajo del equipo de arte en rodaje: cuidado y organización de set, utilería y escenografía; el ambiente de trabajo en el set. XV. Historia del relato fílmico.'],
        'procedimentales': ['Realiza investigaciones y supervisiones de los procesos cinematográficos.', 'Efectúa ejercicios prácticos a partir de escenas.', 'Ejecuta ejercicios prácticos en actuación de teatro y cine.', 'Realiza análisis de escenas de largometrajes, series de ficción y entrevistas de actores y actrices.', 'Realiza desglose de guiones literarios y fílmicos.', 'Realiza trabajo escrito sobre la puesta en escena: fotografía, encuadre y composición.'],
        'actitudinales': ['Actitud responsable y dedicación.', 'Responsabilidad hacia el trabajo en equipo.'],
    },
    'Maquillaje y Vestuario': {
        'modulo': 'Bachillerato en Artes — Mención Teatro',
        'horas': '4',
        'elemento_competencia': 'Realiza maquillajes y vestuarios básicos de personajes tipos, con sentido artístico, para escenas u obras relacionadas con esos personajes.',
        'rae': ['Realiza varios tipos de maquillajes preseleccionados por el profesor, desarrollando con seguridad e higiene caracterizaciones de personajes, asentándolos paso a paso en una ficha para poder repetirlos de la misma manera.', 'Repite el proceso planteado en la ficha de maquillaje que el facilitador propone, para tipologías que requieran caracterizaciones e imágenes similares, con apego al orden de aplicación.', 'Compone un acercamiento al diseño del personaje, con piezas de vestuario y complementos (masculino o femenino) de épocas hito en la historia del teatro universal, asentado en una ficha.', 'Organiza y lleva a término el maquillaje y el vestuario de los personajes tipo en armonía con la caracterización diseñada.', 'Diseña y aplica maquillaje básico, y compone vestuarios básicos, de personajes de escenas u obras preseleccionadas, integrando armónicamente las características morfológicas del rostro y cuerpo de los actores con el personaje tipo, con sentido artístico.'],
        'conceptuales': ['Fundamentos de maquillaje: conceptos de las diferentes modalidades de maquillaje y sus usos (maquillaje general o de calle, maquillaje teatral); tipologías de maquillaje (de calle, correctivo, clásico, dramático, de fantasía, de efectos, de payaso, personajes de la comedia del arte); momentos de la historia del maquillaje; reconocimiento de materiales y cosméticos y sus usos; aporte de la peluquería a la caracterización; historia del peinado y la peluca; bigotes, cejas, barbas, patillas, pelucas y pestañas; calvas y prótesis y los materiales para elaborarlas (papel sanitario, yeso, látex líquido o casero, goma espuma, gasa, bandas de gasa con yeso, gelatina sin sabor y color).', 'Fundamentos de vestuario: definición y diferenciación de vestuario, trajes, indumentaria, vestuario de calle y moda; tipos de materiales textiles, texturas, colores y cueros; aporte del vestuario e indumentaria a la caracterización de personajes y a la actuación; historia del vestuario por épocas (greco-romano, China y Japón, medioevo, renacimiento, barroco y neoclásico, revolución industrial, hitos de 1910 a 1990); caracterización por vestuario según oficio, clase social y estado de ánimo; materiales y formas alternativas para crear un traje; técnicas de envejecimiento del vestuario (enjuague, teñido, pintado, cera, estampado); armonía entre el vestuario diseñado y el maquillaje del personaje.'],
        'procedimentales': ['Emplea las técnicas del maquillaje básico o de calle.', 'Relaciona los personajes creados con las asignaturas de actuación o caracterización para acentuar rasgos emocionales (enojo, furia, alegría, tristeza, terror) en el maquillaje.', 'Elabora la ficha técnica de maquillaje siguiendo paso a paso los procedimientos explicados por el profesor.', 'Emplea y confecciona, de acuerdo al personaje y al modelo, el tipo de maquillaje del personaje.', 'Utiliza materiales, colores y matices para realzar los elementos distintivos emocionales del personaje.', 'Explora con diferentes productos (látex, algodón, gasa, cola blanca no tóxica) para crear efectos de envejecimiento, cicatrices, golpes, heridas y moretones.', 'Realiza prácticas y combinaciones con pelucas y postizos para la creación de personajes.', 'Realiza prótesis y maquillajes con moldes y modelos al rostro propio y de compañeros.', 'Identifica las prendas del vestuario básico de teatro y diferencia la moda de cada época.', 'Reconoce en figurines e imágenes las diferentes épocas de la historia del vestuario y las reproduce en dibujos, modelos y collages.', 'Emplea y ejercita las técnicas básicas de confección de vestuario: corte, hilvanado, cosido y pegado.', 'Compone en modelos bidimensionales y tridimensionales vestuarios de época con personajes tipo.', 'Recrea, con vestuarios reciclados, elementos de épocas destacando textura y color.', 'Utiliza diferentes tipos de materiales reciclados y aplica técnicas de envejecimiento, teñido y uso de cera.'],
        'actitudinales': ['Valora las expresiones y los rasgos importantes de la morfología de cada rostro para destacar la psicología del personaje.', 'Participa con entusiasmo, actitud motivadora y creatividad en el trabajo en equipo.', 'Estimula el sentido de compromiso, orden, previsión y disciplina.', 'Maneja con cuidado y economía los productos cosméticos y maquillajes que le son facilitados.', 'Aprecia las buenas prácticas de cuidado e higiene de los elementos de maquillaje, posticería o prótesis, sobre todo los de re-uso.', 'Sigue las normas prácticas en el uso y manejo de productos e instrumentos de maquillaje.', 'Atención al detalle y cuidado y esmero en la búsqueda de soluciones creativas en obras de épocas.', 'Desarrolla su creatividad y no se avergüenza ante equívocos, corrigiendo por ensayo y error.', 'Valora el cuidado del medio ambiente y la protección de la naturaleza con el uso de materiales biodegradables.', 'Entiende la importancia de la higiene, lavado y cuidado de los instrumentos en su uso.'],
    },
    'Asistencia de la Dirección Teatral': {
        'modulo': 'Bachillerato en Artes — Mención Teatro',
        'horas': '6',
        'elemento_competencia': 'Asiste en la toma de decisiones, organización y supervisión de todos los elementos de la escena de obras trabajadas desde las materias de actuación, para conducir el espectáculo teatral con la estética requerida por el guión, ante el público, siempre colaborando con el sentido artístico.',
        'rae': ['Define el oficio del director y las diversas causas de la aparición del director a través de la historia.', 'Analiza las diferentes funciones de la dirección teatral.', 'Identifica y describe con facilidad las funciones de todos los componentes del equipo artístico y el equipo técnico.', 'Diferencia los diferentes tipos de escenarios históricos y la relación espectadores-actores para aplicarlos a la propuesta específica.', 'Describe claramente las diferentes etapas de la dirección y los principales elementos que la componen.', 'Conoce cuáles son las funciones de la asistencia de dirección.', 'Distingue y realiza labores de regiduría de escena.', 'Analiza el texto y el subtexto de la escena, cuadro o acto, identificando las acciones dramáticas y la progresión del conflicto de la pieza, y las características físicas y psicológicas de los personajes.', 'Realiza diseño de las escenas de la obra, donde armoniza escenografía, personajes y luces en la propuesta escénica.', 'Describe en detalle las funciones y responsabilidades de cada participante, desde la concepción del director hasta el final de las presentaciones o postproducción.', 'Participa en la dirección para la preparación, organización y puesta en ejecución del montaje.', 'Prioriza la consecución de todos los elementos sugeridos por el director.'],
        'conceptuales': ['I. Funciones de todos los componentes del equipo artístico y el equipo técnico. II. Definiciones de la dirección teatral. III. Rol de la dirección teatral y su evolución histórica. IV. Funciones de la dirección teatral. V. La asistencia de dirección: qué es y sus responsabilidades. VI. Perfil del asistente de dirección; libreto del asistente de dirección de escena. VII. Labores de regiduría de escena. VIII. Perfil del regidor de escena; libreto del regidor de escena. IX. El oficio del director y las diversas causas de su aparición a través de la historia. X. Funciones del asistente de dirección y su relación con el equipo técnico. XI. Etapas de la dirección y sus principales elementos. XII. Consecución de los elementos sugeridos por el director: utilerías, mobiliarios, vestuarios y maquillaje. XIII. Cronograma de ensayos y producción de las escenas u obras. XIV. Lectura y análisis del libreto. XV. Libreto del asistente de dirección. XVI. Regiduría: cualidades del regidor y su rol en el proceso de ensayo y presentaciones. XVII. Obtención de insumos necesarios para el montaje: programa, patrocinios. XVIII. Principios del movimiento, plan de escena y nomenclatura teatral. XIX. Diferenciación entre géneros y el tratamiento actoral que requiere cada uno. XX. Plan de montaje: hojas de llamado y reportes de asistencia. XXI. Perfiles profesionales y responsabilidades de cada uno. XXII. Procesos de trabajo y sus responsables. XXIII. Necesidades y equipamientos requeridos para dar solución a los procesos.'],
        'procedimentales': ['Realiza diferentes modelos o dibujos de las escenas y relaciones entre los actores para el movimiento en el espacio.', 'Reconoce en esos ejemplos los elementos de escenografía y utilería a usar en el montaje y su ubicación.', 'Pone en práctica los diferentes modelos de dirección de acuerdo al tipo de obra elegida (composición, movimiento, énfasis, concentración, dispersión, acciones físicas).', 'Utiliza colores y simbologías para demarcar los planos de iluminación, escenografía, utilería y mobiliario, así como los movimientos de los actores en el espacio.', 'Diseña reportes para el manejo del personal y sus responsabilidades.', 'Planifica y ejecuta el cronograma de ensayos y la programación de horarios de las diferentes escenas, dándole seguimiento.', 'Practica con diversos ejercicios los principios del balance compositivo y la armonía del conjunto.', 'Identifica, bajo la dirección del profesor, las necesidades de tipos de actuación.'],
        'actitudinales': ['Reconoce los elementos y rasgos para el acento y destaque de los componentes que utiliza.', 'Desarrolla la mirada y el sentido de la composición y del espacio.', 'Reconoce el orden y las disposiciones necesarias de acuerdo a la escena y en función del movimiento creado por la dirección.', 'Desarrolla la observación y el juicio crítico, con atención al detalle.', 'Se compromete a estar atento en la composición de sus espacios de acuerdo al tipo de espectáculo.', 'Estimula el sentido de compromiso, orden, previsión y disciplina.', 'Aprecia mediante imágenes en fotos y en visitas guiadas la importancia del patrimonio teatral dominicano y sus diferentes espacios.', 'Dinamiza el grupo con actitudes de motivación de la creatividad y el trabajo conjunto en equipo.', 'Participa en clase y comparte con los compañeros sus experiencias y descubrimientos.'],
    },
    'Proyecto Final de Producción de Espectáculos': {
        'modulo': 'Bachillerato en Artes — Mención Teatro',
        'horas': '2',
        'elemento_competencia': 'Asiste en el proceso de producción del espectáculo teatral, desde su pre-producción hasta la postproducción, ejercitándose en el desempeño de las distintas tareas que le competen al productor del espectáculo para llevar con éxito la obra ante el público.',
        'rae': ['Explica los principios básicos del diseño de escenografía, gestionando la utilería y la colocación de las luces y su colorido de acuerdo al ambiente y simbolismo de la obra.', 'Compone escenografías con los elementos necesarios.', 'Confecciona piezas de utilería y complementos de escenografía de épocas que son hitos de la historia del teatro universal.', 'Diseña la iluminación y sus colores en armonía con la escenografía, con sentido artístico, trabajo en equipo y responsabilidad.'],
        'conceptuales': ['I. Definiciones de producción, emprendimiento e industrias culturales. II. Gestión y gerencia. III. Historia de la producción teatral, la producción en el último siglo. IV. Divulgación, propaganda y promoción; tipos de promoción. V. Tareas de la producción y planificación: diseño del proyecto de producción, campaña de difusión, presupuesto (contratación de personal, vestuario, escenografía) y gestión de relaciones públicas, interinstitucionales y comunitarias. VI. Etapas de preproducción: elaboración de anteproyecto, selección del equipo de trabajo, cronograma, revisión y selección de reparto y colaboradores técnicos (escenografía, vestuario, utilería, maquillaje), presupuesto de costos, fuentes de financiamiento, patrocinio y venta de funciones, definición de estilo y reparto, discusiones con dirección y dramaturgia, y presentación y selección de diseños (vestuario, iluminación, sonido, escenografía, maquillaje, audiovisuales), incluyendo derechos de autor y prevención de riesgos laborales. VII. Etapas de producción: comprobación de derechos de autor y disponibilidad de sala, análisis del diseño con el director, definición de público y precios, programación de ensayos, elaboración y seguimiento del presupuesto y flujo de caja, seguimiento al cronograma, compras y alquileres (escenografía, vestuario, utilería, maquillaje), diseño de iluminación y de la pista de sonido, sesiones de fotografía, plan de medios y difusión, diseño de imagen, afiches y programas, y elaboración del plan de montaje y desmontaje. VIII. Etapas de postproducción: seguimiento a funciones y corrección de fallas, intensificación de la promoción, recopilación de productos promocionales, recepción de la crítica de la comunidad, reunión evaluativa del proceso, desmontaje, devolución de materiales prestados y recopilación del expediente del montaje (planos, fichas, fotos) para futuros montajes.'],
        'procedimentales': ['Elabora plantillas, reportes y planillas de producción.', 'Realiza comunicaciones y búsqueda de información y elementos necesarios.', 'Busca y coordina patrocinios o intercambios.', 'Revisa los planos y les da seguimiento cuando es necesario rehacerlos.', 'Coordina y adecua al personal que trabaja en la producción.', 'Aplica medidas disciplinarias cuando es necesario.', 'Organiza la venta de boletas y lleva fichas de las boletas vendidas.', 'Realiza el presupuesto de producción.', 'Coordina la organización y contratación del personal de vestuario y escenografía.', 'Elabora el plan de mercadeo.', 'Coordina la presencia de críticos y periodistas.', 'Da seguimiento a la difusión de los eventos.'],
        'actitudinales': ['Dinamiza el grupo con actitudes de motivación, de la creatividad y el trabajo conjunto en equipo.', 'Participa en clase y comparte experiencias e ideas.', 'Estimula el sentido de compromiso, orden, previsión y disciplina.', 'Trabajo en equipo y perseverancia.', 'Empatía con los demás.', 'Emprendimiento y creatividad.', 'Organización y motivación.'],
    },
    'Entrenamiento para Talleres de Expresión Dramática': {
        'modulo': 'Bachillerato en Artes — Mención Teatro',
        'horas': '3',
        'elemento_competencia': 'Organiza talleres teatrales fundamentados en las unidades didácticas recibidas en la mención de Teatro para el desarrollo de la expresión dramática en los aspectos corporales, cognitivos y afectivos.',
        'rae': ['Argumenta sobre los conceptos fundamentales de expresión teatral.', 'Aplica dinámicas de la expresión teatral.', 'Planifica procesos de expresión oral-corporal en presentación teatral grupal.'],
        'conceptuales': ['I. Introducción a fundamentos de la expresión teatral. II. Expresión dramática y corporal en las etapas del desarrollo del niño. III. Actividades teatrales y juegos dramáticos creativos y grupales.'],
        'procedimentales': ['Emplea estrategias de actuación y expresión corporal para niños.', 'Planea dinámicas de expresión dramática con actitudes integradoras, motivadoras y creativas.', 'Identifica las etapas del desarrollo de los alumnos en la actividad teatral.', 'Argumenta sobre métodos de actuación teatral.'],
        'actitudinales': ['Valora la función del teatro en los aprendizajes y el desarrollo del niño y jóvenes.', 'Valora la actitud responsable y el compromiso ético de los participantes.'],
    },
}

ALIAS_TEATRO = {}

import re as _re
import unicodedata as _ud

def _firma_teatro(s: str) -> str:
    """Firma sin acentos/espacios para búsqueda tolerante a kerning del PDF."""
    nfkd = _ud.normalize('NFKD', s)
    sin_tilde = ''.join(c for c in nfkd if not _ud.combining(c))
    return _re.sub(r'[^a-zA-Z0-9]', '', sin_tilde).lower()

_IDX_TEATRO = {_firma_teatro(k): k for k in CURRICULUM_TEATRO}

def get_asignatura_teatro(nombre: str) -> dict:
    canon = ALIAS_TEATRO.get(nombre, nombre)
    result = CURRICULUM_TEATRO.get(canon) or CURRICULUM_TEATRO.get(nombre)
    if not result:
        firma = _firma_teatro(nombre)
        orig_key = _IDX_TEATRO.get(firma)
        if orig_key:
            result = CURRICULUM_TEATRO.get(orig_key)
    return result or {}

def formatear_contexto_teatro(nombre: str) -> str:
    d = get_asignatura_teatro(nombre)
    if not d: return ""
    partes = []
    if d.get("elemento_competencia"):
        partes.append("ELEMENTO DE COMPETENCIA:\n" + d["elemento_competencia"])
    if d.get("rae"):
        partes.append("RAE (Resultados de Aprendizaje Esperados):\n" + "\n".join("- " + r for r in d["rae"]))
    if d.get("conceptuales"):
        partes.append("SABERES CONCEPTUALES:\n" + "\n".join("- " + c for c in d["conceptuales"]))
    if d.get("procedimentales"):
        partes.append("SABERES PROCEDIMENTALES:\n" + "\n".join("- " + p for p in d["procedimentales"]))
    if d.get("actitudinales"):
        partes.append("SABERES ACTITUDINALES:\n" + "\n".join("- " + a for a in d["actitudinales"]))
    return "\n\n".join(partes)
