# -*- coding: utf-8 -*-
"""
Currículo oficial del Bachillerato en Artes — Mención Artes Visuales — MINERD
Extraído del Plan de Estudios oficial de la Dirección de Modalidad en Artes.
Segundo Ciclo del Nivel Secundario (4to, 5to, 6to).
"""

CURRICULUM_ARTES_VISUALES = {
    # ============================= 4TO GRADO =============================
    'Identidad, Cultura y Emprendimiento': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '2',
        'elemento_competencia': 'Identidad personal, socio cultural, su comunicación y el emprendimiento. Se favorece que los estudiantes realicen una mirada hacia sí mismos, reconociéndose como personas que comportan un sello único que imprimirá unas características distintivas en el uso del lenguaje de las artes, proyectando un uso apropiado del lenguaje verbal y artístico, con miras a realizar un proyecto emprendedor e innovador que destaque las competencias adquiridas durante el trascurso de la asignatura.',
        'rae': ['Identifica los rasgos de la personalidad y su proyección como estudiante de la modalidad en Artes tomando en cuenta las normas del actuar en esta modalidad.', 'Argumenta el papel de la cultura y el arte en su sociedad y en el mundo.', 'Comunica sus ideas y sentimientos, haciendo un uso efectivo de las técnicas, tecnologías y medios de comunicación de la actualidad.', 'Analiza las fortalezas de su personalidad y de su expresividad, en favor de la proyección de una coherente imagen de sí mismo y de los logros de un plan personal.', 'Realiza una presentación audiovisual con estrategias aplicadas a la Web 2.0 donde el estudiante se exprese a sí mismo, sus sueños, fortalezas y retos en el marco del aprendizaje de las artes y de su vida.', 'Argumenta las características del emprendedor cultural.', 'Identifica las áreas de industrias culturales en República Dominicana y las oportunidades de establecer una empresa cultural.', 'Elabora la planificación preliminar de un proyecto cultural sencillo, en base a unas determinadas normas de redacción, siguiendo los criterios establecidos en el área respecto a sus componentes y haciendo énfasis en su viabilidad.', 'Aplica la hoja de cálculo Excel para calcular el presupuesto del proyecto.'],
        'conceptuales': [],
        'procedimentales': [],
        'actitudinales': [],
    },
    'Lenguaje Musical': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '2',
        'elemento_competencia': 'La expresión musical: un despertar de la sensibilidad ante las producciones sonoras. El estudiante se inicia en la lectura y escritura musical, reconociendo audio-visualmente los términos, signos y demás componentes del lenguaje musical relacionados con las cualidades del sonido, para el desarrollo del oído musical y sus posibilidades al complementar el estudio integral de otros perfiles artísticos.',
        'rae': ['Reconoce e identifica audio-visualmente los símbolos, grafías y otros elementos del lenguaje musical en partituras y/o fragmentos musicales.', 'Analiza y reproduce escrita y oralmente melodías, ritmos y piezas seleccionadas.', 'Reconoce audio-visualmente las combinaciones de sonidos en forma melódica como resultado del desarrollo del oído musical.', 'Reproduce oralmente cambios de intensidad en fragmentos melódicos.', 'Diferencia auditivamente los ritmos binarios y ternarios.'],
        'conceptuales': [],
        'procedimentales': [],
        'actitudinales': [],
    },
    'Lenguaje Danzario y Teatral': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '2',
        'elemento_competencia': 'La expresión escénica, que permite la exploración de la experiencia del cuerpo como elemento dramático y rítmico.',
        'rae': ['Reflexiona sobre el empleo de las artes escénicas en tanto valor de uso (social, antropológico), su vinculación al mercado y la industria; y función del arte en distintas épocas y culturas.', 'Identifica los principales géneros de la danza y el teatro, y su relación con otras expresiones artísticas.', 'Utiliza elementos del lenguaje corporal: las expresiones mímicas, el gesto, la postura, la actitud física y las señales que se emiten con el cuerpo.', 'Relaciona algunos elementos del lenguaje teatral: el texto dramático, la iluminación, la escenografía, la utilería, el vestuario como reflejo de la situación escénica, el maquillaje, el sonido, la música incidental y elementos de multimedia.', 'Reconstruye algunas cualidades de la percepción del movimiento corporal: la percepción corporal y sensorial, percepción espacial y audiokinética.', 'Se expresa a través de la danza de forma personal y colectiva, aplicando elementos básicos del lenguaje corporal.', 'Se expresa a través de la actuación de forma personal y colectiva, aplicando elementos básicos del lenguaje teatral.'],
        'conceptuales': [],
        'procedimentales': [],
        'actitudinales': [],
    },
    'Lenguaje Visual y Principios del Diseño Artesanal': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '2',
        'elemento_competencia': 'La expresión gráfica y visual, que facilita la expresión mediante el lenguaje visual y una exploración de las técnicas de diseño bidimensional gráfico para crear artesanías.',
        'rae': ['Argumenta sobre la expresión del lenguaje visual y artesanal, y su evolución a través de la historia.', 'Aplica de forma experimental los principales elementos presentes en el lenguaje visual y artesanal: formas, estructuras, colores, texturas, figura-fondo, composición, luz y sombras, dimensiones, escalas, unidad, variedad, espacialidades, materiales y formatos.', 'Analiza aspectos connotativos y denotativos de imágenes con diferentes estilos artísticos y en diseños con mensajes visuales destinados a diversas funciones: comunicativa, estética y utilitaria.', 'Elabora obras artísticas visuales y artesanales haciendo uso de los elementos básicos del diseño y de la composición.'],
        'conceptuales': [],
        'procedimentales': [],
        'actitudinales': [],
    },
    'Historia del Arte Universal y Teoría de las Artes Visuales': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '4',
        'elemento_competencia': 'Aborda la percepción y valoración de obras artísticas y su evolución a través de la historia del arte universal, con el empleo de recursos sensoriales, corporales y de los lenguajes de la plástica en el contexto de la cultura visual de diferentes movimientos y estilos que los identifican.',
        'rae': ['Valora la variabilidad de las funciones sociales y de las concepciones diferentes del arte a lo largo de la historia.', 'Utiliza términos del glosario de forma adecuada en actividades apreciativas.', 'Explica los hechos artísticos más relevantes de la Historia del Arte situándolos adecuadamente en el tiempo y en el espacio valorando su significación en el proceso histórico-artístico.', 'Disfruta las obras más destacadas del patrimonio artístico dominicano, desde posiciones críticas y creativas, como exponente de nuestra identidad cultural.', 'Desarrolla el gusto personal, el sentido crítico y la capacidad de goce estético a través de las artes.', 'Argumenta acerca de los orígenes de la historia del arte universal, su importancia y relación con las artes visuales.', 'Organiza cronológicamente los períodos históricos del arte con sus obras y autores representativos desde la prehistoria hasta la edad post.', 'Describe las etapas y características y los ejemplos más sobresalientes desde la prehistoria hasta la edad post moderna.', 'Analiza el contexto político, social, religioso de las grandes culturas que protagonizaron la historia del arte de la humanidad.', 'Clasifica las obras representativas evidenciando los valores estéticos de cada época, tendencias, géneros y estilos.', 'Elabora proyectos artísticos de reinterpretación de obras relevantes de la historia del arte universal integrando elementos de la cultura dominicana.'],
        'conceptuales': [],
        'procedimentales': [],
        'actitudinales': [],
    },
    'Principios de Dibujo, Pintura y Creatividad': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '5',
        'elemento_competencia': 'Es la asignatura que fomenta en los estudiantes la representación de sus percepciones visuales mediante composiciones simples y complejas utilizando los conceptos fundamentales y las técnicas principales del dibujo, la pintura y la creatividad.',
        'rae': ['Explica los orígenes y la evolución del dibujo artístico haciendo énfasis en los artistas más destacados, sus obras y aporte al arte.', 'Reconoce la percepción visual y la relación que guarda con el dibujo.', 'Identifica los materiales, instrumentos y soportes para la elaboración de un dibujo artístico.', 'Construye formas bidimensionales y tridimensionales a partir de la línea y aplicación del concepto de la perspectiva.', 'Realiza encajados y reproduce las proporciones correctas de las formas y figuras geométricas y objetos cotidianos.', 'Aplica las técnicas de dibujo haciendo uso del carboncillo, lápiz grafito, sanguina y tinta.', 'Dibuja objetos y figuras geométricas proporcionadas al natural expresando la luz, la sombra, la textura y el fondo.', 'Compone obras artísticas simétricas y asimétricas con figuras geométricas y objetos cotidianos e imaginarios en las cuales se aplique la luz, la sombra, la textura, el fondo y técnicas mixtas.', 'Diseña por medio del dibujo motivos decorativos con formas abstractas geométricas y orgánicas o combinaciones de estas.', 'Identifica las herramientas y materiales de la pintura para el cuidado y su buen uso.', 'Realiza ejercicios aplicando la teoría del color sobre diferentes soportes.', 'Aplica las técnicas del pastel, tinta, témperas y acuarelas en diversos soportes.', 'Construye distintas composiciones a partir de la observación de imágenes y modelos naturales con monocromías y policromías.', 'Aplica las degradaciones tonales sobre diversos soportes.', 'Realiza ejercicios donde utiliza la teoría del color de manera creativa.', 'Desarrolla composiciones artísticas en sus proyectos pictóricos aplicando la teoría del color.', 'Pinta composiciones utilizando las técnicas de: pastel, tinta, témperas y acuarelas.', 'Aplica la teoría de la perspectiva de las sombras en proyectos pictóricos.', 'Elabora portafolio utilizando la luz, la sombra, los reflejos y la relación figura fondo.'],
        'conceptuales': [],
        'procedimentales': [],
        'actitudinales': [],
    },
    'Dibujo Técnico': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '4',
        'elemento_competencia': 'Es la asignatura que facilita normas de representación que permiten al ser humano comunicarse de forma universal, sobre cómo está estructurado un objeto o una forma, un espacio, un edificio, de tal manera que el artista creador puede transmitir, divulgar y conservar sus diseños, para fines de reproducción o recreación por medio de artesanos y personal técnico.',
        'rae': ['Representa gráficamente objetos bidimensionales según técnicas manuales e infográficas propias del dibujo técnico, cumpliendo con la correcta aplicación de las normas referidas a vistas, trazados de líneas, rotulación, acotación y simplificaciones indicadas en la representación de las Artes Visuales.', 'Adopta una postura correcta de acuerdo a su entorno de trabajo.', 'Selecciona los instrumentos y soportes para el dibujo técnico y elige los necesarios para sus propósitos.', 'Utiliza los instrumentos manuales y digitales para el dibujo técnico.', 'Implementa correctamente las escalas en la elaboración de los planos.', 'Utiliza líneas tipo, valores tonales y figuras geométricas, y crea formas combinándolas.', 'Aplica el dibujo técnico en una variedad de situaciones para dibujar plantas, elevaciones y cortes.'],
        'conceptuales': [],
        'procedimentales': [],
        'actitudinales': [],
    },
    'Introducción a la Fotografía Digital': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '2',
        'elemento_competencia': 'Persigue la educación de la mirada, mediante el manejo básico de la cámara, para lograr imágenes que faciliten el entendimiento de las formas, los espacios, la composición, el sentido de la profundidad y la posición del observador en relación a los elementos de una composición. Ejecuta el proceso del uso de la cámara y los principios básicos de la fotografía, en proyectos de expresión artística y como medio de comunicación, aplicando técnicas novedosas y creativas.',
        'rae': ['Realiza ensayos reflexivos sobre los antecedentes y evolución de la fotografía.', 'Realiza fotografías técnicamente correctas.', 'Manipula la cámara de manera correcta.', 'Identifica los mecanismos adecuados para ser usados dependiendo el tipo de iluminación.', 'Valora la fotografía como medio de expresión artística, como medio de comunicación.'],
        'conceptuales': [],
        'procedimentales': [],
        'actitudinales': [],
    },

    # ============================= 5TO GRADO =============================
    'Teoría e Historia de las Artes Visuales Latinoamericana y Dominicana': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '4',
        'elemento_competencia': 'Analiza los orígenes, característica y evolución del arte Latinoamericano y Dominicano desde la época precolombina hasta la actualidad, incorporando sus técnicas, temáticas y sus valores estéticos y formales a su expresión visual.',
        'rae': ['Argumenta con claridad acerca de los orígenes e identidad del arte en Latinoamérica y República Dominicana, su importancia y la influencia de otras culturas.', 'Establece una secuencia cronológica del desarrollo evolutivo de las culturas Latinoamericanas y Dominicanas, de forma gráfica a través mapas conceptuales y líneas de tiempo.', 'Describe las características, contexto político, social y religioso de las culturas que protagonizaron el Arte Latinoamericano y Dominicano en su devenir histórico.', 'Selecciona imágenes de obras destacadas donde se identifican las características estéticas, técnicas, tendencias, géneros, estilos y las grandes temáticas de las obras representativas en la arquitectura, dibujo, pintura, escultura etc. del arte Latinoamericano y Dominicano desde la etapa precolombina hasta la época actual.', 'Realiza cuadros comparativos donde establece las diferencias y similitudes de las características de la arquitectura, pintura y escultura surgidas en la cuna de las civilizaciones del Continente Europeo y las culturas originarias en Latinoamérica.', 'Participa en la elaboración proyectos de reinterpretación de obras a partir de los referentes del arte Latinoamericano y Dominicano haciendo uso de las características, técnicas, valores estéticos y formales imprimiendo su propia inventiva y expresión visual.'],
        'conceptuales': ['Introducción a los orígenes e identidad del arte Latinoamericano y Dominicano y sus influencias.', 'Cronología y culturas que habitaron en Latinoamérica (Centroamérica y el Caribe), sus etapas evolutivas, contexto histórico, social, político y religioso: 1- Arte prehispánico en Mesoamérica.', 'Etapas del arte prehispánico en Mesoamérica. Olmecas, zapotecas, mayas, Los Inca, Los Aztecas. 2- El Arte Latinoamericano: Centro América, Sur América y el Caribe. Períodos, características y artistas reconocidos y sus obras más destacadas.', 'Etapas: Arte Indígena o Precolombino, Arte Colonial, Arte Post Colonial, Arte Latino Americano del XX.', 'Surgimiento del concepto de "Arte Latinoamericano", búsqueda de identidad, autores relevantes del Arte Latinoamericano y Dominicano (IX - XX). 3- El Arte Dominicano:', 'Etapas: Sus orígenes Precolombino, Arte Colonial, Arte de la Primera República, Arte de la Segunda República y Arte Actual.', 'Características estéticas, técnicas y las grandes temáticas de las obras representativas en la arquitectura, dibujo, pintura, escultura etc. del Arte Latinoamericano y Dominicano desde la Etapa Precolombina hasta la Época Actual.'],
        'procedimentales': ['Identificar las etapas y características y los ejemplos más sobresalientes desde el Arte Precolombino hasta la modernidad del Arte Latinoamericano y Dominicano.', 'Construir mapas conceptuales y líneas de tiempo identificando característica, contexto histórico, político, social, religioso de las grandes culturas que protagonizaron el Arte Latinoamericano y Dominicano.', 'Realizar tablas de análisis que contengan las principales características estéticas, técnicas y las grandes temáticas de las obras representativas en la arquitectura, dibujo, pintura, escultura etc. del arte Latinoamericano y Dominicano desde la Etapa Precolombina hasta la Época Actual.', 'Establecer diferencia y similitudes de las características de la arquitectura, pintura y escultura surgidas en la cuna de las civilizaciones del Continente Europeo y las culturas originarias en Latinoamérica.', 'Comparar los valores estéticos de cada época, destacando tendencias, géneros y estilos.', 'Comentar las principales obras del Arte Latinoamericano y Dominicano.', 'Reinterpretar obras a partir de los referentes del Arte Latinoamericano y Dominicano (características, valores estéticos y formales).'],
        'actitudinales': ['Reflexión y juicio crítico.', 'Disciplina y orden.', 'Actitud curiosa y atenta.', 'Respeto por la expresión del arte de cada cultura.', 'Aprecia el entorno espacial urbano y arquitectónico.', 'Concentración e interés por la lectura.', 'Valoración de los aportes de las culturas que habitaron arte Latinoamericano y Dominicano.', 'Interés por los aportes y obras de los autores más destacados del Arte Latinoamericano y Dominicano.'],
    },
    'Fundamentos de la Semiótica Visual': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '2',
        'elemento_competencia': 'Reconoce los elementos expresivos del signo visual, semióticos, e indaga sobre las relaciones entre el contenido y la forma del signo, en la creación de significados, contextualizando las obras de su preferencia en su sentido cultural e histórico y la influencia de las tecnologías recientes, la fotografía, el cine, la televisión y el Internet.',
        'rae': ['Identifica la relación signo-significado en diversas muestras de imágenes y obras visuales.', 'Argumenta sobre los tipos de signos de acuerdo a las teorías de Pierce y Saussure y las diferencias entre ambas tendencias, editando fotografías con cambios y collage, fotomontajes digitales.', 'Expresa coherencia con el mensaje, los signos visuales en creaciones plásticas: dibujo, pintura, cartel, fotografías, grabados, collage, ilustración, diseño.', 'Interpreta los sistemas de signos.', 'Crea un sistema de signos aplicado a su comunidad.'],
        'conceptuales': ['I. Comunicación visual y su esquema.', 'II. Tipos de imágenes.', 'III. Aspectos connotativo y denotativo.', 'IV. Signo, significante, y significado.', 'V. Pictograma, ideograma.', 'VI. Índice, icono, símbolo.', 'VII. Alfabetidad visual.', 'VIII. Esquema de transmisión y estilo de comunicación de la imagen.', 'IX. Proceso de creación de los signos visuales y audiovisuales.'],
        'procedimentales': ['Identificar las relaciones del signo, su contexto, los elementos de la composición pictórica.', 'Reconocer diversos tipos de imágenes según su función comunicativa, en obras de distintos estilos y períodos.', 'Emplear de forma adecuada diversos tipos de signos según su esquema de transmisión.', 'Interpretar con fluidez mensajes visuales y creaciones de la plástica, en el marco del autor, su cultura y su época.', 'Crear un sistema de signos siguiendo proceso de investigación, esquemas, forma y estructuración del signo, retícula para construcción del signo.'],
        'actitudinales': ['Actitud de responsabilidad social y ética profesional en la obra visual.'],
    },
    'Dibujo Artístico': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '4',
        'elemento_competencia': 'Dibuja a través de la observación y el análisis: paisajes, figuras anatómicas desde esquemas simples y complejos relacionándolos con entornos reales o imaginarios representados con las distintas técnicas de dibujo en los distintos proyectos.',
        'rae': ['Diferencia los distintos paisajes, estilos de dibujo, las técnicas y materiales. Desarrolla la expresión gráfico-analítica en las técnicas de lápiz grafito, carboncillo y sanguina así como su aplicación a la resolución de problemas.', 'Hace uso de las habilidades para la percepción y análisis de la forma, textura y la materia.', 'Domina la representación de la perspectiva, proporción, composición, textura y efecto de luz y sombra en paisajes.', 'Representa composiciones de rostros con proporción y volumen desde distintos ángulos (frente, tres cuartos y perfil).', 'Dibuja caricaturas exagerando y manipulando las proporciones de los rasgos faciales de un rostro mostrando personalidades claras sin perder el parecido.', 'Realiza proyectos colectivos que involucren la composición de rostros y paisajes.', 'Argumenta acerca de los aspectos generales y elementos característicos del dibujo anatómico, su relevancia y evolución desde el principio de la historia del arte hasta los tiempos actuales.', 'Construye la figura humana a través de esquemas básicos que permiten elaborar bocetos simples tomando en consideración la proporción, el encaje y el equilibrio.', 'Coloca la figura humana en diferentes perspectivas por medio del dibujo y toma en cuenta el punto de vista, la profundidad y el escorzo.', 'Realiza estudios de dibujo de las extremidades del cuerpo humano de forma proporcionada según el punto de vista o tipo de cuerpo.', 'Interpreta las figuras humanas a través de esquemas de movimiento, síntesis y gestos corporales.', 'Aplica los efectos de la luz y la sombra a las figuras humanas tomando en consideración la dirección y colocación de las mismas.', 'Añade vestuarios a las figuras humanas con atención a los pliegues y arrugas que se producen en ellos.', 'Dibuja partiendo de la observación y el análisis de las figuras humanas al natural.', 'Explorar creativamente las posibilidades de representación del dibujo anatómico aplicando las diversas técnicas, materiales, instrumentos y soportes para plasmar su lenguaje propio.', 'Crea distintos personajes animados de autoría propia, partiendo desde su historia, tipos, características particulares y elementos que los componen como son las escenas y los textos descriptivos previamente reinterpretados por medio del dibujo.'],
        'conceptuales': ['El Paisaje rural, Composición: La división del marco.', 'Cambio de perspectiva.', 'La perspectiva árboles.', 'La textura y efecto.', 'Formas de árboles.', 'Materiales para los bosquejos.', 'A gran escala.', 'Composición: la selección.', 'Licencias con el paisaje.', 'Inventar paisajes.', 'El paisaje como diseño.', 'El paisaje urbano.', 'Visita a la ciudad.', 'La perspectiva de un punto.', 'La perspectiva de dos puntos.', 'Varios puntos de fuga.', 'La perspectiva de tres puntos.', 'La forma de la cabeza.', 'Los rasgos faciales.', 'Un sencillo autorretrato.', 'La cabeza de perfil.', 'Distintos ángulos.', 'Autorretrato (vista de tres cuartos).', 'La juventud y la vejez: bebés, niños y adolescentes, mediana y tercera edad.', 'La expresión.', 'La iluminación.', 'La composición: retratos.', 'La caricatura.', 'El dibujo anatómico a través de la historia (Arte Rupestre, Leonardo Da Vinci, Miguel Ángel Buonarrotti y Rafael Sancio), evolución y características.', 'La figura humana: el esqueleto, la musculatura, el encaje y la proporción, tipos de cuerpo y cánones, la estructura básica (figuras geométricas, líneas verticales, horizontales y diagonales), el equilibrio, el boceto.', 'Colocación de la figura humana: perspectiva (paralela y oblicua), punto de vista, profundidad, escorzo.', 'Extremidades en el dibujo anatómico: brazos y piernas, manos y pies.', 'Dibujo anatómico y esquemas de movimiento. La síntesis, los gestos y el lenguaje corporal en el dibujo.', 'Luz y sombra en la figura humana. Claroscuro.', 'Criterios del vestuario aplicado a la figura humana.', 'Dibujo anatómico al natural.', 'Técnicas creativas de representación anatómica: el dibujo creativo, la observación, exploración e imaginación, la línea y forma, composición, perspectiva y puntos de vista, el detalle y manejo de escalas, fondo y entorno, tono, manchas y texturas, grafito, carboncillo, sanguina, tinta y lápiz color, el movimiento y la gestualidad, soportes y formatos.', 'Personajes y dibujos animados: historia, evolución y características del dibujo animado, ilustración, tipos de dibujos animados (figura de súper héroe y caricaturas), lenguaje corporal y figura dinámica (expresión y acción), escenas y textos complementarios.'],
        'procedimentales': ['Manejar las técnicas de: grafito, carboncillo, sanguina.', 'Dibujar paisajes y componer paisajes con cambios de perspectivas tanto rurales como urbanas.', 'Representar visualmente la forma de la cabeza, rasgos faciales y la expresión desde distintos ángulos (de frente, tres cuartos y perfil).', 'Interpretar y producir bosquejos rápidos y espontáneos.', 'Dibujar y componer retratos y auto retratos con volumen.', 'Interpretar a partir de modelos reales con volumen.', 'Estructurar los esqueletos y esquemas básicos de dibujo anatómico.', 'Preparar bocetos.', 'Realizar los pasos para el encajado y proporción.', 'Integrar la musculatura al dibujo anatómico.', 'Dibujar las extremidades de la figura humana.', 'Elaborar patrones y esquemas de movimiento.', 'Estudiar la luz y la sombra en el dibujo anatómico.', 'Representar los gestos y el lenguaje corporal.', 'Aplicar las técnicas creativas para la representación del dibujo anatómico.', 'Crear personajes y dibujos animados.', 'Preparar escenarios y textos para dibujos animados.'],
        'actitudinales': ['Desarrollo del sentido de la observación, el análisis de las formas, la perspectiva, la composición, encaje y proporción.', 'Uso de la percepción, sensibilidad, la introspección y la concentración.', 'Valora la precisión, la limpieza, la calidad expresiva y la calidad gráfica en el dibujo.', 'Importancia del dibujo anatómico para las demás manifestaciones plásticas.', 'Observación y el análisis en el estudio de la figura humana.', 'Fomento de la Memoria visual.', 'Importancia del valor tonal y el claroscuro para la expresión del volumen en la figura humana.', 'Valor de la calidad expresiva en el dibujo anatómico.', 'Identidad cultural a través del dibujo anatómico.', 'Apreciación del lenguaje corporal.', 'Prudencia y respeto por los procesos de elaboración del dibujo.', 'Trabajo creativo y original.', 'Compromiso con la producción propia y de otro autor.'],
    },
    'Pintura y Creatividad': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '4',
        'elemento_competencia': 'Expresa mediante la pintura: formas, colores, líneas, tonalidades, texturas, paisajes, bodegones, figura humana y temas libres, a través del uso de diversas técnicas y estilos pictóricos.',
        'rae': ['Experimenta con la paleta de colores de la pintura acrílica.', 'Pinta paisajes atendiendo las diversas estructuras urbana y rural.', 'Aplica las técnicas de la acrílica en paisajes y bodegones.', 'Representa los pliegues del paño y las diversas texturas que se producen en el bodegón. Estudia los fondos y su relación con las figuras.', 'Interpreta en forma creativa obras en diversos estilos.', 'Desarrolla composiciones artísticas, creativas y originales en sus proyectos pictóricos.', 'Identifica las características de la pintura al óleo y los materiales necesarios para su desarrollo en el taller.', 'Pinta la figura humana y su relación con el entorno.', 'Realiza obras tomando en cuenta el ropaje y el claroscuro.', 'Plasma retratos y autorretratos por medio de la pintura al óleo.', 'Aplica las diferentes técnicas con la pintura al óleo.', 'Produce diversas texturas aprovechando los objetos extra pictóricos.', 'Combina colores en composiciones abstractas y neofigurativas.', 'Desarrolla proyectos pictóricos con pintura al óleo que manifiesten la originalidad y creatividad utilizando temáticas relativas a la figura humana y su relación con el entorno.'],
        'conceptuales': ['I. La pintura acrílica, característica y usos.', 'II. La composición del paisaje urbano y rural.', 'III. El bodegón y su composición.', 'IV. Pintura al natural.', 'V. Estudios de fondos.', 'VI. Estilos en la pintura.', 'VII. La pintura al óleo, propiedades y características.', 'VIII. Tipos de formatos, montaje, preparación e imprimación sobre diversos soportes.', 'IX. Disolventes, herramientas, barnices.', 'X. Introducción de la figura humana en la pintura.', 'XI. El canon de la figura humana.', 'XII. Perspectiva de la figura humana en la pintura.', 'XIII. Relación figura humana y fondo.', 'XIV. El retrato y autorretrato.', 'XV. Aplicación claroscuros, texturas y pliegues.', 'XVI. La pintura simbólica y abstracta.', 'XVII. Técnica mixta y estilos pictóricos vanguardistas.'],
        'procedimentales': ['Manejar la paleta de colores en pintura acrílica.', 'Realizar un paisaje con pintura acrílica.', 'Preparar un bodegón con pintura acrílica.', 'Realizar estudios de fondo.', 'Aplicar estilos artísticos.', 'Mezclar los colores con limpieza y armonía, en tonalidades diversas, y con sentido expresivo y simbólico.', 'Preparar correctamente los diferentes tipos de soportes.', 'Realizar veladuras, manchas y empastes siguiendo un proceso correcto de ejecución.', 'Pintar al óleo paisajes, marinas, bodegones y retratos de figuras con modelos masculinos y femeninos vivos (al natural).', 'Realizar auto retratos.', 'Elaborar pinturas relacionando la figura y el fondo.', 'Usar la espátula y los materiales extra pictóricos.', 'Aplicar el dripping en el soporte.', 'Utilizar el modeling paste para conseguir diversas texturas.', 'Aplicar la técnica del puntillismo en un proyecto pictórico.', 'Pintar usando el método del restregado en la superficie del cuadro para lograr valoraciones de luz y sombras.', 'Realizar pinturas abstractas y neo figurativas con estilos vanguardistas.', 'Crear proyectos pictóricos haciendo uso de la originalidad y creatividad.'],
        'actitudinales': ['Importancia de la concentración durante la ejecución de un trabajo.', 'Desarrollo de habilidades psicomotoras, creativas y originalidad.', 'Muestra sensibilidad, utiliza la introspección y la concentración.', 'Sentido de la observación, la percepción, el análisis de las formas y las proporciones.'],
    },
    'Grabado': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '2',
        'elemento_competencia': 'Crea composiciones de representación expresiva, mediante las técnicas básicas del grabado: el monotipo, la estampación, la colografía, la xilografía, el linóleo, la punta seca y otras técnicas alternativas de grabado.',
        'rae': ['Explica los principios y fundamentos del grabado, la estampa original, reproductibilidad, funcionalidad estética y lenguaje gráfico del linograbado.', 'Adecua el boceto al lenguaje propio del grabado develando sus posibilidades gráficas y expresivas.', 'Realización de impresiones en diferentes soportes preparados en el taller y comerciales.', 'Adquiere destrezas en el uso de la instrumentación y construcción de matriz.', 'Produce proyectos creativos haciendo uso de los conocimientos del grabado y sus distintas manifestaciones.'],
        'conceptuales': ['Los orígenes del grabado.', 'Diferentes técnicas del grabado.', 'Materiales, herramientas, tintas. Las Vanguardias y el inicio de su empleo en el siglo XX.', 'La presión y máquinas para efectuar la presión. Prensas, tórculos y estampación a mano.', 'Metodología para la realización del grabado sobre linóleo.', 'Elementos espaciales: punto, línea, plano, textura y forma.'],
        'procedimentales': ['Manipula las herramientas.', 'Aplica los procesos creativos del estampado.', 'Selecciona los materiales adecuados a las diferentes técnicas, las tintas y rodillos, las prensas, los hornos, resinas y papeles.', 'Realiza trabajos con grabado en hueco, a través de la técnica de xilografía.', 'Experimenta con la preparación de una matriz de madera dura.', 'Ejecuta grabados con la técnica xilográfica, para adiestrarse con sus detalles.', 'Usa analíticamente las alternativas de matrices como las técnicas del estarcido, esténcil, serigrafía, frottage, colografía.', 'Entinta adecuadamente la superficie de la plancha.', 'Procesa una o varias estampas con la técnica del linograbado, para dominar esta técnica.'],
        'actitudinales': ['Disciplina y orden.', 'Trabajo creativo y de forma original.', 'Prudencia, y respeto por los procesos.', 'Cuidado al medio ambiente.', 'Limpieza y orden del entorno de trabajo.'],
    },
    'Modelado I': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '3',
        'elemento_competencia': 'Aplica técnicas básicas del modelado en arcilla y en la talla representando figuras geométricas sencillas que reproduce siguiendo procedimientos de moldeado (tacelado) y vaciado.',
        'rae': ['Desarrolla una sensibilidad táctil con el manejo de la arcilla, modelando volúmenes geométricos básicos.', 'Identifica y maneja las herramientas del escultor.', 'Modela figuras de patrones geométricos copiando y dando un acabado de superficie con texturas apropiadas.', 'Arma moldes y vacía en yeso respetando los procedimientos.', 'Aplica la técnica básica de talla, descubriendo el bulto de una figura geométrica sencilla.', 'Reconoce y diferencia las técnicas del modelado escultórico.'],
        'conceptuales': ['I. Breve Introducción a la historia de la escultura y del modelado.', 'II. La escultura en el plano y en el espacio:', 'III. El Bajo relieve', 'IV. El Alto relieve', 'V. El bulto.', 'VI. Aspectos técnicos del modelado.', 'VII. Directa: tallar, esculpir.', 'VIII. Indirecta: modelado, tacelado, vaciado y fundido.', 'IX. Mixtas: modelado directo, ensamblado y otros.', 'X. Herramientas de cada proceso.', 'XI. Técnicas de talla. Esculpir la piedra, el granito y el mármol.', 'XII. Fundición en hierro bronce o aluminio. La cera perdida.', 'XIII. La masilla, el cemento, el yeso; directos o por vaciado.'],
        'procedimentales': ['Conoce y experimenta con la plasticidad de la arcilla: Tritura, amasa, alisa, carga.', 'Conoce y usa correctamente las herramientas del escultor.', 'Realiza ejercicios de modelado copiando frisos en alto relieve y en bajo relieve, así como modela figuras geométricas elementales.', 'Experimenta las características técnicas del yeso realizando un molde o tacel y reproduce por vaciado en yeso, los frisos modelados.', 'EJERCICIOS DE MODELADO ESPACIALES: Modela una columna, estriada, con o sin tope en arcilla 10cm x 10cm x 45cm.', 'Copia por vaciado en yeso la columna.', 'Modela 3 formas geométricas básicas (cono, cubo, poliedro) s/ plano inclinado. 25cm x 30cm x 25cm.', 'Copia por vaciado en yeso usando taceles.', 'EJERCICIO DE TALLA: Talla un bloque de yeso de 10cm x 20cm x 30cm.'],
        'actitudinales': ['Paciencia, cuidado y pulcritud en el desarrollo de los procesos. Responsabilidad y perseverancia. Trabajo en equipo.'],
    },
    'Diseño Bi y Tridimensional': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '4',
        'elemento_competencia': 'Representa gráficamente por medio de técnicas manuales y tecnologías digitales, proyectos sencillos de diseño bidimensional, y construye objetos y/o espacios tridimensionales, así como proyectos arquitectónicos sencillos con planta general, planta amueblada y elevaciones, en varias escalas, aplicando los códigos técnicos de arquitectura y el diseño.',
        'rae': ['Asume una actitud crítica a ejemplificaciones y respecto a las etapas de desarrollo del proyecto de diseño de objetos o espacios arquitectónicos.', 'Elabora argumentos, proyecta composiciones y soluciones innovadoras de proyectos de creación de formas, objetos, diseño bidimensional y espacial.', 'Proyecta a escala composiciones y soluciones innovadoras de proyectos en 2D y 3D.', 'Construye manualmente o mediante el uso de la tecnología las posibles soluciones al proyecto, modelos y maquetas.'],
        'conceptuales': ['I. Introducción al uso de la PC. Instalación de programas. Herramientas y comandos básicos de programas CAD y de ilustración vectorial. Aplicaciones.', 'II. Diseño Bidimensional. Definición. Elementos: tipos. Las formas. Características, tipos e interrelaciones en composiciones bidimensionales.', 'III. Módulos y estructuras. Definición. Generalidades. Tipos.', 'IV. Aportes del color y la textura como elementos visuales importantes en la realización de proyectos bidimensionales. Diversas teorías. Clasificación. Tipos.', 'V. Introducción al dibujo 3D. Tipos de programas. Requerimientos. Ventajas.', 'VI. Diseño Tridimensional. Definición. Particularidades sobre visualización y coordenadas. Isométricas. Elevación de objetos 2D. Modificación de objetos.', 'VII. Crear regiones. Superficies regladas. Las variables. Comandos tabulated y revolved surface. Crear sólidos con los diferentes comandos de edición.', 'VIII. Iluminación: Tipos. Modificadores de luces. Sombras. Texturas: Tipos. Aplicación a superficies y objetos. Efectos.', 'IX. Renderización: Tipo. Mallas. Tipos de formatos. Impresión.'],
        'procedimentales': ['Aplicar técnicas manuales de delineación, para la representación de proyectos bidimensionales.', 'Explorar los diferentes programas, sus comandos y herramientas, para la consecución de elementos bidimensionales en un proyecto simple.', 'Generar presentaciones de 2D y 3D proporcionadas a escala, para propiciar su impresión e interpretación posterior correctas.', 'Crear imágenes fotorrealistas de los modelos tridimensionales, para tener una idea más cercana al objeto representado, utilizando recursos digitales y/o convencionales.', 'Estructurar adecuadamente los proyectos tridimensionales a través de una lógica de ordenamiento, para lograr una propuesta que pueda ser entendible por otros.', 'Realizar acotamientos que permitan describir con precisión el proyecto, adaptándose a la normativa en diversas escalas.', 'Creación, uso y edición de librerías de detalles y elementos constructivos, para abreviar tiempos y garantizar uniformidad en la preparación de proyectos representados tridimensionalmente.', 'Emplear los diferentes métodos y comandos de edición, para la creación de volúmenes, juego de luces, sombras (entre otros), para la consecución de elementos tridimensionales en un proyecto.'],
        'actitudinales': ['Interés, observación y orden.'],
    },

    # ============================= 6TO GRADO =============================
    'Pintura Mural y Decorativa': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '6',
        'elemento_competencia': 'Realiza la pintura mural artística mediante haciendo uso de las técnicas clásicas o contemporáneas de su elección: al fresco, al graffitti, la acrílica y-o la piroxilina, así como diversos acabados del muro con fines decorativos.',
        'rae': ['Identifica los diversos momentos históricos del mural y los materiales usados progresivamente.', 'Investiga sobre todos los estilos y tendencias de la pintura mural.', 'Visita localidades con murales para estudiar las temáticas y técnicas empleadas.', 'Desarrolla un proyecto colectivo usando los procedimientos aprendidos.'],
        'conceptuales': ['I. Pintura Mural, contexto histórico, evolución, características y principales exponentes.', 'II. Los murales más importantes de la historia; Capilla Sixtina.', 'III. Carácter de la pintura mural: decorativo y arquitectónico.', 'IV. La Pintura Mural materiales, técnicas y evolución.', 'V. La pintura mural y otras intervenciones murales artísticas.', 'VI. La pintura mural y las intervenciones murales de arte público: El grafiti valor sociocultural y expresivo.', 'VII. Función comunicativa del mural en la actualidad.'],
        'procedimentales': ['Estudiar el espacio de trabajo, sus condiciones estructurales y su carácter efímero o duradero.', 'Aplicar técnicas de pintura mural decorativa, para efectos en espacios interiores.', 'Aplicar técnicas de pintura mural al exterior.', 'Producir composiciones murales mediante técnicas de: Temple de huevo sobre muros.', 'Técnicas de pintura mural al seco: Pintura mural a la caseína, encáustica, óleo, pintura acrílica y piroxilina.', 'Realizar un proyecto de mural en una representación a escala.', 'Reflejar el diseño del proyecto al muro.'],
        'actitudinales': ['La importancia de la pintura Mural como exponente de nuestra idea estética.', 'Apreciar el entorno espacial urbano y arquitectónico.', 'Disciplina y orden para llevar a cabo los procesos de la pintura mural.', 'Actitud creativa e innovadora.', 'Cuidado medioambiental y personal.', 'Ética y compromiso social.'],
    },
    'Modelado II': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '4',
        'elemento_competencia': 'Modela formas anatómicas y figuras abstractas o concretas, abiertas o cerradas, en reposo o movimiento, y las reproduce mediante técnicas de vaciado en yeso o cemento.',
        'rae': ['Analiza visualmente y aplica las leyes de la composición y proporción de la figura escultórica, sus formas, ejes y movimientos.', 'Construye la estructura del armazón, con ejes y direcciones bien definidas.', 'Modela figuras de Cabeza, Tronco y Extremidades, aplicando acertadamente la proporción.', 'Expresa la dinámica de la estructura interna de las formas dando al modelado una intención plástica determinada.', 'Resuelve los problemas del vaciado en yeso de figuras anatómicas complejas.', 'Aplica las diferentes técnicas del modelado figurativo.', 'Identifica los detalles estructurales mediante la observación del modelo y los representa a través de un elaborado modelado del bulto anatómico basado en una estructura sólida.', 'Expresa y transmite sensaciones y acciones captadas en un momento.', 'Cuida la plasticidad de la materia, otorgando vida, tensión o relajamiento a cada músculo o gesto; propiciando a la obra vida, y un carácter dinámico.', 'Resuelve el molde de múltiples taceles en figuras abiertas como cerradas. Ejecuta un proceso de vaciado ordenado y exitoso.'],
        'conceptuales': ['Morfología: lo geométrico vs. lo orgánico.', 'Anatomía básica músculo-esquelética.', 'La estructura interna y su dinámica de fuerzas.', 'Las proporciones anatómicas.', 'La divina proporción. Espiral Áurea.', 'Análisis de obras anatómicas destacadas, de la historia del arte clásica. Miguel Ángel, Donatello, Rodín, entre otros.', 'El concepto de la espiral áurea, la proporción y su aplicación en la escultura.', 'Las figuras cerradas, las abiertas y las estáticas en movimiento.', 'Estudiar la estructura axial en las obras básicas (parado, sentado, acostado).', 'Estudio de la figura cerrada: La esfinge, el ChacMool, un esclavo de Miguel Ángel.', 'Estudio de la dinámica de lo cerrado estático: Venus de Milo, La Piedad, un caballo de Botero, el David de Donatello, el Moisés de Miguel Ángel.', 'Estudio de lo cinético. El movimiento y lo abierto: el David de Bernini, la Victoria alada de Samotracia, el Discóbolo, el David de Miguel Ángel.'],
        'procedimentales': ['Construye armazones para sostener la estructura de figuras de cabeza, tronco y extremidades, aplicando ejes y vectores de direcciones.', 'Modela piezas figurativas: una cabeza, una figura humana sentada o parada, una figura reclinada sobre un plano inclinado.', 'Planea la ejecución del tacelado múltiple hasta completar un molde con registros.', 'Montaje y armado de moldes por taceles.', 'Reproducción por vaciado en yeso.', 'Desmoldado de taceles.', 'Realiza un compás áureo para comprender la lógica constructiva de algunas proporciones.', 'Realiza ejercicios de medición y usos para una mejor comprensión de las proporciones.', 'Bocetar fotografías de esculturas predeterminadas buscando proporciones áureas y marcando ejes, pesos, balance, masa, bulto y vacío.', 'Realización de bocetos escultóricos rápidos, para adiestrarse con ejes y proporciones.', 'Desarrollar un plan personal con dos proyectos diferentes (figura parada apoyada en reposo, y figura en movimiento), armando armazones a escala, modelando la pieza, preparando taceles para el vaciado a yeso o cemento y trabajando en equipo el armado y desmolde.'],
        'actitudinales': ['Desarrollar la inteligencia visual y espacial.', 'Desarrollar la sensibilidad crítica en la percepción del entorno y de la naturaleza.', 'Fomentar el compañerismo, la organización y el trabajo en grupo.', 'Velar por el cuidado de lo personal, el equipo y las herramientas.', 'Fomentar la paciencia con los procesos, el entorno ambiental y las condiciones del trabajo.', 'Se entrega y enfoca en la observación de la figura humana como un todo. Se concentra en su trabajo y en los procesos. Trabaja en equipo. Cuida el medio ambiente. Lleva adelante el trabajo hasta conseguir sus objetivos con prolijidad y perseverancia. Internaliza al modelado como una forma de expresarse.', 'Colabora con sus compañeros ayudando durante el proceso de corte de materiales, cuida y se maneja de manera prudente en el uso de las herramientas.', 'Respeta los lugares de trabajo.', 'Es ordenado y consistente durante los procedimientos.'],
    },
    'Dibujo Arquitectónico Digital': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '4',
        'elemento_competencia': 'Diseña a través de representaciones digitales objetos y dibujos arquitectónicos, destacando: los planos, la planta general, elevación frontal, sección, perspectiva y mueblería; aplicando los códigos técnicos y normativos de la arquitectura y el diseño haciendo uso del software CAD.',
        'rae': ['Reconoce los códigos y sus símbolos para la representación de diseños arquitectónicos y diseño de objetos de uso cotidiano.', 'Representa un plano sencillo mediante boceto con el uso de instrumentos manuales utilizando la escala 1:10 y 1:50.', 'Distingue en las aplicaciones de diversos programas para el diseño y dibujo digital, los beneficios que aporta en la exactitud y visualización del diseño.', 'Interpreta la interfaz del usuario del programa Autocad, accediendo con fluidez a la barra de menús de trabajo: archivo, edición, visualización.', 'Emplea los comandos para visualizar los planos, figuras y objetos: zoom, ventana, vista previa, entre otros.', 'Dibuja formas 2D con las herramientas del menú de dibujo y edición.', 'Realiza un plano sencillo con vista en planta sobre una vivienda, su planta arquitectónica y amueblada.', 'Indica correctamente las dimensiones en líneas de acotamiento.', 'Distingue las herramientas de dibujo en 3D, comparando sus funcionamientos en diversos programas CAD.', 'Aplica sus conocimientos en 2D y 3D en el software CAD, en un proyecto de arquitectura de local comercial.', 'Realiza representaciones 3D aplicando sus conocimientos del software CAD, en proyectos de diseño industrial: un mueble.', 'Argumenta sobre las ventajas de implantar un sistema CAD en una empresa.', 'Opera el programa CAD con fluidez en el marco de una simulación del ambiente laboral.', 'Emplea los conceptos, normas y el vocabulario técnico de al menos dos programas CAD (AutoCad, VectorWorks).'],
        'conceptuales': ['I. La representación gráfica, 2D las formas y sus vistas en planta y elevación.', 'II. Signos y símbolos de la representación gráfica en planos arquitectónicos.', 'III. Concepto de proporción aplicado al diseño de objetos y espacios.', 'IV. Concepto de escala. Escala natural, escala de reducción y escala de ampliación.', 'V. Clases y grosores de líneas según el uso y la escala a utilizar.', 'VI. Contenido de la tarjeta de Presentación.', 'VII. Interfaz del usuario, Menú de inicio, creación del entorno.', 'VIII. Acotación de las medidas.', 'IX. Formas básicas para dibujar objetos en 2D.', 'X. Elementos constructivos y su representación en 2D.', 'XI. Visión tridimensional en el entorno CAD: fundamentos de la perspectiva axonométrica.', 'XII. Introducción de las dimensiones o medidas.', 'XIII. Sistema de medidas.'],
        'procedimentales': ['Maneja las herramientas digitales del programa asistido por computadora CAD.', 'Administra archivos de dibujo y configura su sistema de unidades.', 'Ejecuta los diversos comandos del programa, para construir figuras en 2D.', 'Realiza planos digitales de objetos geométricos sencillos representados en planta y en elevación.', 'Ejecuta a escala, planos arquitectónicos sencillos con acotaciones.', 'Domina la herramienta extrusión, y región, modelado 3D, presionar y tirar.', 'Ejecuta los diversos comandos del programa, para construir figuras en 3D.', 'Ejecuta a escala, planos arquitectónicos sencillos con acotaciones, dando forma a un proyecto final.'],
        'actitudinales': ['Receptividad.', 'Interés por la representación visual.', 'Percepción y visualización.'],
    },
    'Proyecto Emprendedor de Arte Contemporáneo': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '5',
        'elemento_competencia': 'Diseña proyectos culturales, emprendedores y contemporáneos de producción plástica creativa, con una imagen corporativa y la exploración creadora del estilo propio para la exposición y venta de sus creaciones plásticas, aplicando estrategias de mercadeo, liderazgo y toma de decisiones en equipos de simulación empresarial, en el marco de la promoción y venta del producto artístico, asumiendo una actitud emprendedora con responsabilidad social y financiera.',
        'rae': ['Identifica las diferentes manifestaciones y tendencias de la plástica contemporánea.', 'Interpreta un lenguaje artístico propio y reinventa los conceptos de la obra.', 'Produce y relaciona ideas dentro del proceso creativo.', 'Ejercita la creatividad y la innovación en el uso de los materiales.', 'Interactúan con el espacio por medio a experiencias y la manipulación de materiales.', 'Elabora proyectos que involucren la construcción de obras u objetos artísticos de forma individual o colectiva para su posterior análisis, valoración y discusión.', 'Desarrolla la capacidad de plantear, desarrollar y concluir el trabajo de investigación artístico de manera crítica, comprensiva y creativa con el fin de identificar y utilizar métodos y estrategias de investigación coherentes con la práctica artística contemporánea.', 'Interpreta enfoques creativos dentro del contexto contemporáneo.', 'Se identifica con una modalidad e incorpora sus ideas a la producción creativa donde interviene el espectador.', 'Construye pensamientos lógico creativo en los espacios expositivos de comunicación y didáctica.', 'Adquiere responsabilidad financiera.', 'Impulsa la participación en el proceso de selección y desarrollo de proyectos tecnológicos y experimentales, individuales o colectivos que serán exhibidos al final de la materia.'],
        'conceptuales': ['Pensamiento ideológico, ecléctico y multicultural del arte contemporáneo.', 'Las Manifestaciones y tendencias del arte objetual, las instalaciones artísticas, el arte conceptual, happening y la performance.', 'Modalidades procesuales en las instalaciones artísticas (Arte Minimalista, Arte Povera y Land Art)', 'Arte Conceptual, ideas, sistema y proceso.', 'Glosario de términos del arte contemporáneo.', 'Proyectos creativos contemporáneos (idealización, gestión, producción.)', 'Análisis de productos fotográficos como documentación', 'El arte y las nuevas tecnologías (El video arte, Net Art)', 'El Arte urbano e implicaciones sociales, ambientales, lúdicas identidad y memoria.', 'Plan museográfico de espacios de exposición.'],
        'procedimentales': ['Describir objetos como un documento testimonial (Arte Objetual)', 'Ensamblar objeto común y elaborar un Radymade.', 'Construir objetos artísticos (minimalista, Povera).', 'Dominar las herramientas de montaje de la instalación artística.', 'Producir instalación artística con creaciones multimedios (video-instalación, pintura y esculto-instalación, instalación-sonora, performance-instalación).', 'Utilizar fotografías conceptuales en la preparación de proyectos.', 'Pinta y dibuja conceptualmente.', 'Realizar montaje y apropiación de imágenes conceptuales.', 'Preparar portafolio de imágenes y/o documentación de obra realizadas.', 'Utilizar la fotografía como documentación del proceso crítico y creativo, a través del análisis de sus contenidos visuales.', 'Crear una propuesta visual con estilo personal y autónomo.', 'Planear la ejecución de propuestas artísticas lúdica, social y crítica.', 'Reproducir montaje sensorial de creaciones permanente y efímera.', 'Calcular el presupuesto, financiamiento y plan de gastos del proyecto.', 'Ejecutar estrategias de mercadeo con el empleo de la Web 2.0.', 'Documentar obras de arte efímero, memorias y de acciones.', 'Intervenir espacios públicos y privados (folclore urbano y medio ambientales).'],
        'actitudinales': ['Valora la obra como documento testimonial artístico e histórico.', 'Critica reflexiva ante el proceso de aprendizaje en el contexto de una realidad cercana.', 'Participa en aspecto lúdico-creativo y sensorial como un proceso intelectual.', 'Pensamiento lógico abstracto en la variedad de la plástica creativa y perceptiva (arte-vida).', 'Fomentar hábitos de pensamiento crítico, lógico y creativo.', 'Responsabilidad social y financiera en el proceso de aprendizaje.', 'Actitud emprendedora y creativa.', 'Disposición a la innovación en presentación de multimedia.', 'Trabajo en equipo, cooperación y solidaridad.', 'Ser tolerante y solidario a proyecto desarrollado por una crítica abierta y participativa en el aula por parte de todos sus miembros.'],
    },
    'Entrenamiento Para Talleres De Expresión Plástica': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '4',
        'elemento_competencia': 'Realiza la planificación de un taller fundamentado en unidades didácticas para el desarrollo de la expresividad plástica creadora fundamentados en el constructivismo socio-histórico cultural, y enfocado a la estimulación y desarrollo artístico en talleres comunitarios.',
        'rae': ['Argumenta la importancia de la educación y de la expresión plástica para el desarrollo emocional, intelectual, físico, senso-perceptivo, creativo y estético.', 'Formula las competencias adquiridas en el taller haciendo uso de los fundamentos del enfoque constructivista.', 'Selecciona adecuadamente las estrategias de seguimiento en el marco del diseño curricular.', 'Realiza la planeación de una unidad didáctica con actividades de educación plástica infantil.', 'Aplica sus conocimientos en talleres comunitarios o en un centro educativo.'],
        'conceptuales': ['I. Etapas de desarrollo psicosocial y expresivo de niño y adolescentes.', 'II. Teoría de la educación: las tendencias de la educación en el arte, con énfasis en el constructivismo el enfoque constructivista socio-histórico cultural, y el desarrollo de las competencias de la creatividad.', 'III. Fundamentos sobre la planeación de los aprendizajes en una unidad didáctica. Categorías de la Didáctica.', 'IV. Métodos y estrategias de aprendizaje en la expresión plástica.', 'V. Estrategias de seguimiento al desarrollo expresivo.'],
        'procedimentales': ['Argumenta la importancia de la educación plástica en el desarrollo psicosocial del niño y el adolescente, en el marco de las principales tendencias formativas en el arte.', 'Realiza la planeación de una unidad didáctica con actividades de expresión creadora infantil, en el marco del diseño curricular.', 'Aplica metodología del proceso de enseñanza-aprendizaje de la expresión plástica infantil en una clase de un taller en su comunidad.'],
        'actitudinales': ['Valoración del arte infantil.', 'Amor por la infancia.', 'Responsabilidad.'],
    },
}

ALIAS_ARTES_VISUALES = {}

import re as _re
import unicodedata as _ud

def _firma_artes_visuales(s: str) -> str:
    """Firma sin acentos/espacios para búsqueda tolerante a kerning del PDF."""
    nfkd = _ud.normalize('NFKD', s)
    sin_tilde = ''.join(c for c in nfkd if not _ud.combining(c))
    return _re.sub(r'[^a-zA-Z0-9]', '', sin_tilde).lower()

_IDX_ARTES_VISUALES = {_firma_artes_visuales(k): k for k in CURRICULUM_ARTES_VISUALES}

def get_asignatura_artes_visuales(nombre: str) -> dict:
    canon = ALIAS_ARTES_VISUALES.get(nombre, nombre)
    result = CURRICULUM_ARTES_VISUALES.get(canon) or CURRICULUM_ARTES_VISUALES.get(nombre)
    if not result:
        firma = _firma_artes_visuales(nombre)
        orig_key = _IDX_ARTES_VISUALES.get(firma)
        if orig_key:
            result = CURRICULUM_ARTES_VISUALES.get(orig_key)
    return result or {}

def formatear_contexto_artes_visuales(nombre: str) -> str:
    d = get_asignatura_artes_visuales(nombre)
    if not d: return ""
    partes = []
    if d.get("elemento_competencia"):
        partes.append("ELEMENTO DE COMPETENCIA:\n" + d["elemento_competencia"])
    if d.get("rae"):
        partes.append("RAE (Resultados de Aprendizaje Esperados):\n" + "\n".join("- " + r for r in d["rae"]))
    if d.get("conceptuales"):
        partes.append("SABERES CONCEPTUALES:\n" + "\n".join("- " + c for c in d["conceptuales"]))
    if d.get("procedimentales"):
        partes.append("SABERES PROCEDIMENTALES:\n" + "\n".join("- " + p for p in d["procedimentales"]))
    if d.get("actitudinales"):
        partes.append("SABERES ACTITUDINALES:\n" + "\n".join("- " + a for a in d["actitudinales"]))
    return "\n\n".join(partes)
