# -*- coding: utf-8 -*-
"""
Currículo oficial del Bachillerato en Artes — Mención Música — MINERD
Extraído del Plan de Estudios oficial de la Dirección de Modalidad en Artes.
Segundo Ciclo del Nivel Secundario (4to, 5to, 6to).
"""

CURRICULUM_MUSICA = {
    'Identidad, Cultura y Emprendimiento': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '2',
        'elemento_competencia': 'Comunica su identidad personal y social a través de un proyecto emprendedor para satisfacer una necesidad de desarrollo cultural en su comunidad y obtener ingresos económicos por ello, siguiendo las normas de redacción, autenticidad, los criterios establecidos en el área respecto a sus componentes y haciendo énfasis en su viabilidad.',
        'rae': ['Identifica los rasgos de la personalidad, y su proyección como estudiante de la modalidad en Artes tomando en cuenta las normas del actuar en esta modalidad.', 'Argumenta el papel de la cultura y el arte en su sociedad y en el mundo.', 'Comunica sus ideas y sentimientos, haciendo un uso efectivo de las técnicas, tecnologías y medios de comunicación de la actualidad.', 'Analiza las fortalezas de su personalidad y de su expresividad, en favor de la proyección de una coherente imagen de sí mismo y de los logros de un plan personal.', 'Realiza una presentación audiovisual con estrategias aplicadas a la Web 2.0 donde el estudiante se exprese a sí mismo, sus sueños, fortalezas y retos en el marco del aprendizaje de las artes y de su vida.', 'Argumenta las características del emprendedor cultural.', 'Identifica las áreas de industrias culturales en República Dominicana y las oportunidades de establecer una empresa cultural.', 'Elabora la planificación preliminar de un proyecto cultural sencillo, en base a unas determinadas normas de redacción, siguiendo los criterios establecidos en el área respecto a sus componentes y haciendo énfasis en su viabilidad.', 'Aplica la hoja de cálculo Excel para calcular el presupuesto del proyecto.'],
        'conceptuales': ['La Cultura en un mundo mediatizado.', 'El ser humano en el contexto de su cultura.', 'Comunicación verbal y no verbal.', 'Autoconcepto e identidad personal.', 'Identidad social: normas del actuar de los estudiantes de la modalidad en Artes. Relación del estudiante con su comunidad y familia. Rasgos de los jóvenes de su región, nación y contexto global.', 'Emprendimiento cultural.', 'Planeación de proyectos artísticos.', 'Industrias artísticas locales dominicanas.'],
        'procedimentales': ['Utilizar correctamente el español de forma verbal y escrita según la situación de comunicación.', 'Utilizar recursos expresivos corporales y audiovisuales para la comunicación.', 'Emplear las redes sociales para comunicar la identidad, el arte y la cultura.', 'Realizar análisis simples estilo FODA.', 'Planear proyectos productivos preliminares.'],
        'actitudinales': ['Valoración de los rasgos personales.', 'Autenticidad.', 'Respeto a la diversidad.', 'Actitud emprendedora y responsable.'],
    },
    'Introducción a la Historia del Arte universal y Dominicano': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '3',
        'elemento_competencia': 'El alumno será capaz de realizar la apreciación de obras artísticas correspondientes a movimientos y estilos artísticos de la Historia del Arte universal y dominicano, argumentando su relación con la época, el contexto socio-cultural y geográfico.',
        'rae': ['Valora la variabilidad de las funciones sociales y de las concepciones diferentes del arte a lo largo de la historia.', 'Utiliza términos del glosario de forma adecuada en actividades apreciativas.', 'Explica los hechos artísticos más relevantes de la Historia del Arte situándolos adecuadamente en el tiempo y en el espacio valorando su significación en el proceso histórico-artístico.', 'Disfruta las obras más destacadas del patrimonio artístico dominicano, desde posiciones críticas y creativas, como exponente de nuestra identidad cultural.', 'Desarrolla el gusto personal, el sentido crítico y la capacidad de goce estético a través de las artes.'],
        'conceptuales': ['El concepto arte y su evolución a través del tiempo.', 'Glosario de términos (Arte, estética y cultura, las Bellas Artes, entre otros).', 'De la Prehistoria al Arte Medieval Occidental: su manifestación en la cultura dominicana.', 'Las maravillas del mundo antiguo, moderno y dominicano.', 'Arte dominicano desde los tiempos precolombino y colonial.', 'Del Arte Renacentista hasta el Barroco: su manifestación en la cultura dominicana.', 'Del Arte Neoclásico hasta las vanguardias del siglo XX: su manifestación en la cultura dominicana.'],
        'procedimentales': ['Desarrollar una apreciación estética práctica sobre distintas obras de arte sustentado en los rasgos que cualifican los movimientos y estilos y su relación con el contexto, importancia histórica y repercusiones en el país.'],
        'actitudinales': ['Respeto por las culturas diferentes.', 'Valoración de la estética y del arte en las obras de cada época.', 'Interés por los valores que promueve el arte en diferentes épocas.'],
    },
    'Lenguaje Visual y Principios del Diseño Artesanal': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '2',
        'elemento_competencia': 'Realiza la expresión artística a través de la integración de las artes visuales y las artesanías reflejando su identidad cultural en trabajos personales y colectivos, haciendo uso de los elementos básicos de los lenguajes visual y artesanal, mostrando sus funciones comunicativas, estéticas y utilitarias.',
        'rae': ['Argumenta el rol del lenguaje visual y artesanal y su evolución a través de la historia.', 'Identifica los principales elementos presentes en el lenguaje visual y artesanal como formas, estructuras, colores, texturas, figura-fondo, composición, luz y sombras, tamaños, escalas, equilibrios, unidad, variedad, espacialidades, materiales y formatos.', 'Analiza aspectos connotativos y denotativos de imágenes de diferentes estilos artísticos.', 'Elabora obras artísticas visuales y artesanales haciendo uso de los elementos básicos y técnicas.'],
        'conceptuales': ['Introducción a las artes visuales y las artesanías: conceptos, materiales, soportes, instrumentos y sus diferentes manifestaciones.', 'Las artes visuales en distintas épocas y culturas y su rol en la actualidad (énfasis en República Dominicana).', 'Las artesanías en distintas épocas y culturas y su rol en la actualidad (énfasis en República Dominicana).', 'Elementos básicos pertenecientes al lenguaje visual y artesanal (formas, estructuras, colores, espacialidades, materiales, formatos, soportes).', 'Percepción visual, signos y símbolo (simbología taína): introducción a los aspectos connotativos y denotativos de la imagen u obra artística.', 'Elementos básicos de las técnicas de expresión visual y artesanal.'],
        'procedimentales': ['Identificar las diversas modalidades de las artes visuales y artesanías y su evolución histórica.', 'Percibir visualmente elementos del lenguaje visual.', 'Realizar el diseño de una imagen visual aplicando técnicas elementales.', 'Experimentar con técnicas y materiales artesanales.', 'Elaborar obras artísticas visuales y artesanales haciendo uso de los elementos básicos y técnicas, relacionando el lenguaje visual con el lenguaje sonoro usando la creatividad.'],
        'actitudinales': ['Responsabilidad y disciplina.', 'Valorar los aportes de las artes visuales y las artesanías en la época actual.'],
    },
    'Lenguaje Danzario y Teatral': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '2',
        'elemento_competencia': 'El alumno será capaz de hacer uso de elementos básicos del lenguaje danzario y teatral para expresar escénicamente rasgos de su identidad, de modo personal y colectivo, dando respuesta a los requerimientos escénicos y comunicativos predefinidos para el nivel medio de formación artística.',
        'rae': ['Argumenta el rol del lenguaje danzario y teatral en el devenir del desarrollo cultural de la humanidad.', 'Identifica los principales elementos presentes en el lenguaje corporal como las expresiones mímicas, el gesto, la postura, la actitud física y las señales que se emiten con el cuerpo en la danza.', 'Analiza y valora los diferentes tipos de percepción del movimiento corporal: percepción corporal y sensorial, percepción espacial y audiokinética.', 'Interpreta o crea fragmentos sencillos de obras escénicas que incorporen la actuación y la danza haciendo uso de los elementos básicos de las técnicas teatral y danzaria.'],
        'conceptuales': ['Función social del teatro y la danza.', 'El género en la danza.', 'Los géneros teatrales.', 'Elementos básicos del lenguaje de la danza.', 'Elementos básicos del lenguaje del teatro: personaje, texto dramático, conflicto, acción dramática, hechos, desenlaces, escenas, puestas en escena, escenografía, luces e indumentaria.', 'Técnicas elementales de interpretación de la danza: clásica, moderna, contemporánea, folclórica y popular.', 'Técnicas elementales de interpretación del teatro: interpretación realista, distanciamiento y otras tendencias.'],
        'procedimentales': ['Enumera la función social del teatro y la danza en las distintas épocas.', 'Compara los contenidos y formas de diferentes géneros de la danza.', 'Describe las características de los principales géneros dramáticos: comedia, tragedia, drama.', 'Diferencia los géneros teatrales y danzarios de forma concisa.', 'Expresa de forma oral o escrita la idea básica de las técnicas de interpretación dramática y coreográfica.', 'Reconstruye cualidades de la percepción del movimiento corporal.', 'Interpreta o crea fragmentos cortos de danzas folclóricas o contemporáneas, comunicando rasgos de su identidad.', 'Experimenta diversas formas de la representación dramática, improvisación y juego dramático.'],
        'actitudinales': ['Valora la función social del teatro.', 'Respeta las diferentes estéticas de las formas teatrales y danzarias.', 'Valora el uso del cuerpo y la voz como herramientas de expresión.', 'Valora el cuerpo como instrumento del bailarín.', 'Interés en la interpretación y concentración en el movimiento propio.', 'Comunica adecuadamente las ideas y el carácter de los personajes.', 'Participación cumpliendo con las indicaciones de la danza.', 'Aprecia el movimiento corporal a través del ritmo o la música.'],
    },
    'Lenguaje Musical, Teoría y Entrenamiento': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '3',
        'elemento_competencia': 'Reproduce audio-visualmente los términos, signos y demás componentes del lenguaje musical relacionados con las cualidades del sonido ayudando al desarrollo del oído musical, la lectura, escritura, ejecución y memorización de fragmentos musicales.',
        'rae': ['Reconoce e identifica audio-visualmente los símbolos, grafías y otros elementos del lenguaje musical en partituras y/o fragmentos musicales.', 'Analiza y reproduce escrita y oralmente melodías, ritmos y piezas seleccionadas.', 'Reconoce audio-visualmente las combinaciones de sonidos en forma melódica como resultado del desarrollo del oído musical.', 'Reconoce auditivamente y reproduce oralmente cambios de intensidad en fragmentos melódicos.', 'Diferencia auditivamente los ritmos binarios y ternarios.', 'Reconoce e identifica audio-visualmente los conceptos, símbolos, grafías y otros elementos del lenguaje musical en fragmentos y partituras musicales escritas.', 'Solfea fragmentos melódicos y rítmicos con diferentes grados de dificultad.', 'Memoriza melodías y ritmos estudiados.', 'Identifica las distintas combinaciones de sonidos en forma melódica y/o armónica como respuesta al desarrollo del oído musical.'],
        'conceptuales': ['El sonido y sus cualidades: altura, duración, intensidad.', 'Simbología melódica (sonidos) y rítmica (figuras).', 'Lecto-escritura musical.', 'Altura.', 'Registros, sonidos, claves de Sol y Fa en 4ta línea.', 'Intervalos melódicos de 2das y 3ras mayores y menores, ascendentes y descendentes.', 'Las alteraciones: distintos tipos y su función.', 'Armadura de clave (hasta 1 alteración). Orden de los sostenidos y los bemoles.', 'Duración.', 'Métrica: compases binarios y ternarios, simples (denominador 4 y 8) y compuestos (denominador 8).', 'Ritmo: figuras de notas y silencios, el puntillo, valor absoluto y relativo de las figuras (desde la redonda hasta la corchea), combinaciones rítmicas, polirritmias.', 'Tempos: Moderato, Andante, Allegro y Adagio.', 'Intensidad.', 'Dinámica: matices de Piano (p), mezzopiano (mp), mezzoforte (mf) y Forte (f), reguladores.', 'Signos de repetición: puntos o barras de repetición, Da Capo.'],
        'procedimentales': ['Reconoce audio-visualmente los signos y términos de la música.', 'Lee entonadamente un fragmento musical.', 'Entona y reconoce auditivamente escalas e intervalos.', 'Ejecuta ritmos y polirritmias.', 'Reconoce auditivamente ejercicios rítmicos y melódicos utilizando compases binarios y ternarios.', 'Lee entonadamente un fragmento musical con las dificultades del nivel.', 'Memoriza melodías y ritmos estudiados en clases.'],
        'actitudinales': ['Actitud responsable y emprendedora.', 'Creatividad.'],
    },
    'Instrumento I - Guitarra': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '4',
        'elemento_competencia': 'Ejecuta la guitarra interpretando escalas, arpegios, acordes, estudios y piezas, teniendo en cuenta la colocación correcta del instrumento, cuerpo y manos, aplicando la técnica del movimiento alternado de los dedos i-m y m-i, logrando una buena sonoridad, claridad y limpieza.',
        'rae': ['Identifica las partes de la guitarra y la simbología utilizada en su escritura, nombre de las cuerdas al aire y su identificación en el pentagrama.', 'Ejecuta la guitarra en la interpretación de ejercicios, estudios y piezas del programa, aplicando la técnica del movimiento alternado de los dedos i y m, teniendo en cuenta la colocación correcta del instrumento, cuerpo y manos.', 'Ejecuta correctamente los ejercicios técnicos del primer nivel.', 'Ejecuta las escalas, arpegios, acordes y piezas aplicando correctamente la técnica.'],
        'conceptuales': ['La guitarra: sus partes, producción del sonido, simbología utilizada en su escritura, nombre de las cuerdas al aire y su identificación en el pentagrama.', 'Cuerdas al aire para la colocación de la mano derecha.', 'Movimiento alternado de im, mi, ma y am en una y dos cuerdas, ascendentes y descendentes.', 'Sonidos naturales de la guitarra en el I cuádruplo (escala diatónica).', 'Escala de Do Mayor y de Sol Mayor.', 'Inicio del movimiento del pulgar.', 'Forma musical cánon (La Gallinita) en Sol Mayor.', 'Estudio de pulgar con movimiento alternado de i-m.', 'Escala de Mi menor natural y armónica.', 'Movimiento simultáneo de im y mi.', 'Arpegios descendentes y ascendentes de 3 notas.', 'Movimiento de pulgar seguido de i-m simultáneos.', 'Acordes de 3 notas.', 'Escala cromática en el I cuádruplo.'],
        'procedimentales': ['Identifica las partes que forman la guitarra.', 'Coloca correctamente el instrumento y la posición del cuerpo y las manos.', 'Ejecuta los sonidos naturales en el 1er cuádruplo (escala diatónica).', 'Realiza los ejercicios técnicos, estudios y piezas en tiempos lentos con buena sonoridad, claridad y limpieza.'],
        'actitudinales': ['Actitud responsable y dedicación.', 'Sensibilidad ante la música.'],
    },
    'Instrumento I - Teclado': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '4',
        'elemento_competencia': 'Ejecuta el instrumento musical teclado utilizando la técnica básica del piano para lograr una postura corporal correcta, la articulación de sus dedos y la digitación para ambas manos; interpreta piezas cortas del repertorio tradicional universal en compases simples de denominador 4 utilizando los signos de la expresión musical.',
        'rae': ['Identifica las partes del teclado, teclas blancas y negras, el Do central, la digitación para ambas manos y los planos sonoros en el teclado.', 'Ejecuta en el teclado los ejercicios técnicos de su nivel logrando una posición correcta de cuerpo, manos, brazos, hombros y dedos, y la digitación para ambas manos.', 'Toca el repertorio seleccionado para su nivel de memoria con un ritmo estable y buena sonoridad.', 'Identifica los elementos de la grafía y expresión musical para la ejecución de sus piezas.', 'Toca una obra sencilla a 4 manos, acompañado de su profesor.'],
        'conceptuales': ['El teclado y sus posibilidades sonoras.', 'Partes del instrumento: teclas blancas y negras, registros medio, grave y agudo.', 'La nota Do central.', 'Breve historia del piano y el teclado.', 'Respetar el valor de las notas: tiempo y ritmo.', 'Digitación de ambas manos.', 'Ejercicios de relajación y respiración.', 'Posición correcta del cuerpo, brazos, codos y manos en el teclado.', 'Grafía musical inicial: pentagrama, claves, compases, alteraciones, intervalos, escalas, acordes, arpegios.', 'Las figuras o notas musicales: redonda, blanca, negra y corchea en compases de denominador 4, en claves de Sol y Fa.', 'Los toques en el teclado: ligado, picado y portato.', 'Lectura de partitura y ejecución práctica en el teclado.', 'Las frases musicales.', 'Estudios y piezas para los dedos 1-2-3 con avance gradual hasta los dedos 4 y 5 de ambas manos.', 'Escala de Do Mayor, manos separadas, iniciando con el 3er dedo.', 'Ejercicios del pase del pulgar con ambas manos.', 'El hábito de tocar de memoria.', 'Repertorio seleccionado de piezas empleando las notas más próximas al Do central.', 'Obra sencilla a 4 manos.'],
        'procedimentales': ['Adopta la posición correcta en el instrumento.', 'Identifica las partes del teclado.', 'Lee y ejecuta en el teclado las notas más próximas al Do central.', 'Ejecuta sus piezas de memoria.'],
        'actitudinales': ['Interés y disposición de aprender y estudiar.', 'Disciplina y responsabilidad.', 'Aplica las directrices de su profesor-a.', 'Disfruta el aprendizaje de las melodías.', 'Cuida y preserva su instrumento, partituras y accesorios.'],
    },
    'Instrumento I - Viento': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '4',
        'elemento_competencia': 'Selecciona, identifica, explora, ejecuta y cuida un instrumento musical de la familia de viento madera y metal desarrollando la técnica básica en el registro central fundamentada en la correcta posición de los brazos y manos, emisión del sonido (respiración costo-diafragmática y ataque) y digitación participando en actividades escolares, religiosas, deportivas y otras de igual carácter, interpretando fragmentos musicales del repertorio universal de estructura formal simple con un grado de dificultad de (0 a 0.5) utilizando las figuras de redonda, blanca y negra.',
        'rae': ['Identifica la importancia del rol que desempeña como estudiante de nivel inicial cuando ejecuta el instrumento seleccionado de la familia de viento madera y metal en actividades escolares, religiosas, deportivas y otras de igual carácter.', 'Identifica las partes del instrumento musical seleccionado, para su cuidado y mantenimiento.', 'Aplica la técnica básica fundamentada en la correcta posición de los brazos y manos, emisión del sonido (embocadura y respiración) y digitación, para la ejecución en el registro central de un instrumento de la familia de viento madera y metal en las actividades programadas.', 'Ejecuta el instrumento que estudia en la interpretación de pequeños fragmentos musicales de estructura formal simple con un orden de dificultad de (0 a 0.5) utilizando las figuras de redonda, blanca y negra del repertorio universal.', 'Participa en las actividades programadas con respeto y disposición para realizar las tareas.'],
        'conceptuales': ['Historia de los instrumentos musicales seleccionados para su estudio.', 'Función del instrumentista en la ejecución de pequeños fragmentos musicales de estructura simple con un nivel de dificultad de (0 a 0.5) utilizando las figuras de redonda, blanca y negra del repertorio universal.', 'Importancia del estudio de la música para el desarrollo humano.', 'Valoración del estudio técnico en su relación con las habilidades y destrezas necesarias para la ejecución del instrumento.', 'Importancia del dominio del repertorio musical universal.'],
        'procedimentales': ['Ejecuta pequeños fragmentos musicales a través de la técnica básica fundamentada en la correcta posición de los brazos y manos con la que se evitan enfermedades profesionales óseas, emisión del sonido, respiración costo-diafragmática que favorece el buen desarrollo del aparato respiratorio y la salud en general, y ataque, así como la digitación en el registro central.', 'Participa ejecutando un instrumento seleccionado de la familia de viento, madera y metal en actividades escolares, religiosas, deportivas y otras de igual carácter.', 'Interpreta pequeños fragmentos musicales de estructura formal simple de un grado de dificultad de (0 a 0.5) utilizando las figuras de redonda, blanca y negra del repertorio universal.'],
        'actitudinales': ['Cuida y da mantenimiento a los instrumentos seleccionados para su estudio.', 'Cumple con los deberes y tareas asignados.', 'Mantiene buenas relaciones éticas con sus compañeros de estudio y profesores lo que le ayuda al desarrollo de los valores de justicia y equidad.', 'Disfruta y aprecia el valor estético de las obras musicales que interpreta, lo que contribuye al desarrollo de su autoestima.'],
    },
    'Instrumento I - Percusión': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '4',
        'elemento_competencia': 'Selecciona, ejecuta y cuida instrumentos musicales de la familia de la percusión clásica de sonido indeterminado, desarrollando la técnica básica, fundamentada en la correcta posición de los brazos y manos, emisión del sonido tanto en actividades escolares, religiosas, deportivas y otras de igual carácter, interpretando fragmentos musicales del repertorio universal de estructura formal simple con un grado de dificultad de (0 a 0.5) utilizando las figuras de redonda, blanca y negra.',
        'rae': ['Explica la importancia del rol que desempeña como estudiante de nivel inicial cuando ejecuta los instrumentos de la familia de la percusión, en actividades escolares, religiosas, deportivas y otras de igual carácter.', 'Explica las partes de los instrumentos musicales de percusión, para su cuidado y mantenimiento.', 'Aplica la técnica básica fundamentada en la correcta posición de los brazos y manos, emisión del sonido y digitación, para la ejecución en las actividades programadas.', 'Ejecuta los instrumentos que estudia en la interpretación de pequeños fragmentos musicales de estructura formal simple con un orden de dificultad de (0 a 0.5) utilizando las figuras de redonda, blanca y negra del repertorio universal.'],
        'conceptuales': ['Elementos técnicos básicos de los instrumentos de percusión clásica de sonido indeterminado (rudimentos).', 'Cuidado y mantenimiento de los instrumentos de percusión de sonido indeterminado.', 'Ejecución de los instrumentos de percusión en grupos o ensambles.', 'Repertorio universal de nivel (0-0.5) acorde al programa técnico de cada instrumento de percusión.'],
        'procedimentales': ['Aplicación de los elementos técnicos básicos de los instrumentos de percusión clásica de sonido indeterminado (rudimentos).', 'Utilización de los accesorios requeridos en el cuidado y mantenimiento de los instrumentos de percusión clásica de sonido indeterminado.', 'Selección de los instrumentos de percusión a utilizar en cada fragmento musical.', 'Ejecución de un repertorio acorde al nivel técnico del estudiante con un grado de dificultad de 0 a 0.5.'],
        'actitudinales': ['Responsabilidad y persistencia.', 'Acepta y cumple con las observaciones técnicas.', 'Respeta, valora y se integra al trabajo en equipo.', 'Atiende y acepta las correcciones técnicas del programa.', 'Comparte los conocimientos adquiridos.', 'Sensible a los requerimientos musicales.', 'Disposición para el estudio.'],
    },
    'Práctica Instrumental Grupal I': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '4',
        'elemento_competencia': 'Ejecuta un instrumento musical como integrante de una agrupación musical (ensamble, grupo de cámara, conjuntos con diferentes formatos instrumentales o banda de música), utilizando los principales elementos técnicos (respiración, emisión, sonido, afinación, postura y rudimentos de la percusión), identificando y valorando su rol e importancia dentro de la agrupación, interpretando fragmentos musicales simples al unísono con un grado de dificultad (0 a 0.5), incluyendo progresivamente pequeños fragmentos musicales del repertorio universal.',
        'rae': ['Identifica las principales partes del instrumento musical seleccionado, para su cuidado y mantenimiento.', 'Aplica los elementos técnico-musicales básicos para la ejecución del instrumento dentro de la agrupación (respiración, emisión, afinación, postura).', 'Ejecuta con fluidez y seguridad su instrumento dentro de la agrupación, interpretando pequeños fragmentos musicales del repertorio universal de nivel (0 a 0.5).', 'Ejecuta un instrumento musical como integrante de una agrupación musical (ensamble, conjunto, grupo de cámara, orquesta o banda de música), identificando su importancia, conformación y rol como instrumentista dentro de la agrupación.', 'Participa en la organización y realización de actividades musicales grupales, con respeto y disposición para realizar las tareas.'],
        'conceptuales': ['Elementos técnicos básicos del instrumento en la práctica grupal (respiración, emisión, sonido, afinación, postura).', 'Formatos de las agrupaciones musicales (ensambles, conjuntos con diversos formatos, grupos de cámara o banda de música). Rol del instrumentista dentro de la agrupación.', 'Sonoridad, balance y concepto rítmico de las agrupaciones.', 'Técnicas de ensayo por secciones y familias de instrumentos.', 'Cuidado y mantenimiento del instrumento.', 'Repertorio universal de nivel 0 a 0.5, acorde al programa técnico de cada instrumento.'],
        'procedimentales': ['Aplica los elementos técnicos básicos del instrumento en la práctica grupal (respiración, emisión, sonido, afinación, postura).', 'Realiza trabajo sistemático de calentamiento grupal.', 'Ejecuta variados sistemas de trabajo por secciones y familias de instrumentos.', 'Realiza diversos ejercicios rítmicos como herramienta fundamental en la práctica grupal.', 'Utiliza prácticas vocales en lectura del repertorio y soporte de la afinación.', 'Utiliza los accesorios requeridos en el cuidado y mantenimiento del instrumento.', 'Ejecuta un repertorio acorde al nivel técnico del estudiante con un grado de dificultad de 0 a 0.5.'],
        'actitudinales': ['Responsabilidad y persistencia.', 'Acepta y cumple con las observaciones técnicas.', 'Respeta y valora el trabajo en equipo.', 'Atiende y acepta las exigencias del programa.', 'Comparte los conocimientos adquiridos.', 'Sensible a los requerimientos musicales.', 'Disposición para el estudio.'],
    },
    'Canto Coral I': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '3',
        'elemento_competencia': 'Aplica los conceptos de la técnica vocal trabajada, en las interpretaciones corales y/o vocales, partiendo de las características de las obras seleccionadas del repertorio tradicional, universal, enfatizando afinación, entonación, en la técnica respiración costal-diafragmática, el apoyo, el empaste o acoplamiento, considerando la importancia de su voz dentro de la agrupación.',
        'rae': ['Identifica los aparatos y órganos de la voz humana, su funcionamiento y el uso correcto de esta en la agrupación coral.', 'Aplica la técnica de respiración costal-diafragmática al cantar.', 'Usa el apoyo diafragmático al cantar.', 'Mantiene la entonación y afinación de la línea melódica correspondiente a su cuerda.', 'Aplica los conocimientos adquiridos de la técnica vocal a las interpretaciones de pequeñas obras.', 'Participa con compromiso, respeto y disciplina en las actividades (ensayos parciales, generales, pequeñas presentaciones) propias del coro.'],
        'conceptuales': ['Fundamentos de técnica vocal: anatomía, estructura y funcionamiento del aparato respiratorio, fonador y resonador.', 'Técnicas básicas de relajación, ejercicios de respiración, apoyo diafragmático, uso de los resonadores, ejercicios básicos de vocalización de expansión del registro e impostación vocal.', 'Técnica del canto coral aplicada a la interpretación entonada y afinada de un repertorio seleccionado para el nivel cursado de canciones tradicionales universales.'],
        'procedimentales': ['Usa de forma correcta los órganos y partes del cuerpo que forman parte del aparato respiratorio.', 'Realiza los ejercicios técnicos de relajación, respiración, apoyo diafragmático, expansión del registro e impostación vocal, con consonantes resonantes.', 'Aplica la técnica del canto coral en cada una de las obras seleccionadas del repertorio a abordar en este nivel, ejecutando de forma entonada y afinada, con un sonido homogéneo frente al grupo.'],
        'actitudinales': ['Se integra al trabajo en equipo.', 'Tolera a sus compañeros.', 'Cumple con las normas disciplinarias del canto coral.', 'Se esfuerza para aplicar los conocimientos.', 'Interioriza y toma conciencia del sentido de afinación, colocación, respiración, dicción y homogeneidad.', 'Acepta las correcciones técnicas y de actitud frente al trabajo.'],
    },
    'Teoría y Entrenamiento Musical I': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '4',
        'elemento_competencia': 'Crea fragmentos y piezas musicales, relacionando el significado de los símbolos, signos, caracteres y grafías, así como de los vocablos y conceptos propios del lenguaje musical a través de la lectura, el análisis, la escritura y la ejecución demostrando una mayor complejidad en el proceso.',
        'rae': ['Reconoce e identifica audio-visualmente los conceptos, símbolos, grafías y otros elementos del lenguaje musical en fragmentos y partituras musicales escritas.', 'Emplea los elementos de la música en la creación de ideas musicales, donde utilice los nuevos conocimientos adquiridos.', 'Solfea fragmentos melódicos y rítmicos con diferentes grados de dificultad.', 'Lee a primera vista pequeñas melodías y patrones rítmicos.', 'Compone fragmentos melódicos sencillos para voces o instrumentos (flauta dulce) utilizando todos los conocimientos teóricos adquiridos en la materia.', 'Demuestra con su actuación las habilidades físicas, motoras y emocionales adquiridas en función del nuevo lenguaje aprendido a través de la rigurosidad de la enseñanza.'],
        'conceptuales': ['Las claves de Sol y Fa en 4ta línea. Notas y figuras. Alteraciones. Armadura de clave (escalas, intervalos, acordes, ritmos, compases simples y compuestos, signos de repetición, signos de dinámica).', 'Contenido teórico: los nuevos conocimientos se van adicionando a los ya adquiridos.', 'Signos y términos de la música en su relación con las cualidades del sonido.', 'Registros, sonidos, pentagrama, claves de Sol y Fa en 4ta línea.', 'Intervalos melódicos de 2das, 3ras, 6tas y 7mas mayores y menores, 4tas, 5tas y 8vas justas, ascendentes y descendentes.', 'Acordes: tríadas mayores y menores con sus inversiones. Cifrado tradicional y anglosajón (popular).', 'Armadura de clave (con 3 alteraciones). Orden de los sostenidos y los bemoles.', 'Métrica: compases simples (denominador 4 y 8), compases compuestos (denominador 8).', 'Ritmo: figuras de notas y silencios, valor absoluto y relativo de las figuras (desde la redonda hasta la semicorchea), combinaciones rítmicas, valores irregulares (tresillo), síncopa y contratiempo, polirritmias.'],
        'procedimentales': ['Reconoce audio-visualmente los signos y términos de la música.', 'Lee entonadamente un fragmento musical acorde a los conocimientos adquiridos.', 'Crea pequeñas melodías y ritmos con una extensión de 4 compases.', 'Ejecuta ritmos y polirritmias en los compases estudiados.', 'Lee a primera vista melodías y ritmos con una extensión de 4 compases.'],
        'actitudinales': ['Actitud responsable.', 'Emprendimiento.', 'Creatividad.'],
    },
    'Armonía I': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '3',
        'elemento_competencia': 'Construye de forma audio-visual, los distintos tipos de acordes de tres sonidos: triadas mayores y menores con sus inversiones, para la utilización en acompañamientos instrumentales y corales.',
        'rae': ['Reconoce e identifica audio-visualmente las triadas (mayores y menores) en estado fundamental e invertido.', 'Identifica auditivamente la tonalidad en una pieza musical sencilla.', 'Forma tríadas de distintos tipos, en estado fundamental e invertido.', 'Reconoce los grados tonales de las tonalidades con sus respectivos acordes.', 'Lee en forma entonada distintos cifrados tanto en el estilo tradicional (grados I, IV, V) como en el anglosajón o popular (A, B, C, etc.).'],
        'conceptuales': ['Ejemplificación y concepto de armonía.', 'Tríadas y sus inversiones.', 'Construcción y reconocimiento audio-visual.', 'Tríadas mayores y menores: inversión, construcción y reconocimiento audio-visual.', 'Cifrados tradicionales y anglosajón (alfabético). Utilización en las construcciones de acordes (triadas) estudiados.', 'Grados fundamentales de las escalas mayores y menores. Reconocimiento y entonación.'],
        'procedimentales': ['Reconoce audio-visualmente los signos y términos de la música.', 'Construye distintos tipos de tríadas y sus inversiones.', 'Cifra los acordes en el estilo anglosajón y el tradicional.'],
        'actitudinales': ['Actitud responsable y emprendedora.', 'Creatividad.'],
    },
    'Música Dominicana': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '2',
        'elemento_competencia': 'Ejecuta las diversas expresiones de la música folklórica y popular dominicana, las cuales forman parte de la identidad cultural nacional.',
        'rae': ['Investiga y despierta el interés por el estudio y conocimientos de los ritmos básicos y característicos de las diversas expresiones del folklor musical.', 'Interpreta temas musicales populares y folklóricos.', 'Crea fragmentos musicales basados en esquemas rítmicos de la música popular y folklórica dominicana.'],
        'conceptuales': ['Historia, contexto social-cultural de la música folklórica dominicana.', 'Medios y recursos musicales de las siguientes expresiones musicales folklóricas: la sarandunga, el chenche matriculado, el carabiné, la mangulina, gagá, los palos, salve, criolla, media tuna, zarambo, guarapo, cantos de trabajo, canciones de rondas.', 'Historia, contexto social-cultural de la música popular dominicana.', 'Exponentes más destacados, producciones y obras más destacadas de la música popular dominicana y de difusores del folklor dominicano.', 'Medios y recursos musicales empleados en las siguientes expresiones: música típica dominicana (perico ripiao), merengue (en todas sus variantes), bachata, balada, bolero.'],
        'procedimentales': ['Investiga acerca de la música folklórica y popular en los contextos socio-culturales de desarrollo.', 'Analiza y reflexiona sobre las expresiones musicales folklóricas y populares desde el aspecto rítmico, melódico, temático e instrumental a fin de establecer diferencias.', 'Discrimina por medio de audiciones la música folklórica y la música popular.', 'Ejecuta fragmentos o pequeñas obras del folklor musical y género popular.', 'Ejecuta de forma pública los fragmentos o pequeñas obras folklóricas y populares.', 'Crea fragmentos musicales de 8 compases basados en los esquemas de la música folklórica o popular.'],
        'actitudinales': ['Fomenta una actitud responsable y emprendedora.', 'Fomenta la creatividad.', 'Valora su cultura e identidad.', 'Desarrolla su capacidad de comunicación por medio de la expresión oral y corporal.', 'Fomenta la disciplina.'],
    },
    'Instrumento II - Guitarra': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '4',
        'elemento_competencia': 'Ejecuta la guitarra con memorización de la música, reafirmando la posición correcta de cuerpo, instrumento y manos, que le permitan lograr un mejor desempeño y control auditivo de la calidad e intensidad del sonido, interpretando escalas, arpegios, acordes así como pequeños fragmentos musicales integrando ritmos del repertorio universal, clásico y popular, aplicando los recursos y técnicas (ligados ascendentes y descendentes, etc.) e incorporando nuevos recursos y elementos técnicos para un mejor desempeño en la interpretación musical.',
        'rae': ['Ejecuta la guitarra manteniendo una correcta posición de cuerpo, instrumento y manos.', 'Aplica las herramientas técnicas del nivel para realizar las escalas, arpegios, ejercicios técnicos, estudios y piezas con buena calidad e intensidad de sonido.', 'Ejecuta la escala cromática y la escala de Do Mayor en el II cuádruplo.', 'Improvisa una pequeña melodía.', 'Identifica y ejecuta los acordes mayores y menores con sus respectivas escalas.', 'Ejecuta los acordes y arpegios de 4 notas ascendentemente.', 'Aplica el movimiento alternado de pulgar con los dedos i y m simultáneos.', 'Aplica la técnica de los ligados ascendentes y descendentes en la interpretación de estudios y piezas logrando la articulación correcta de los sonidos.', 'Ejecuta acordes utilizando la barra o ceja.', 'Ejecuta y acompaña piezas musicales en los distintos tipos de ritmos.'],
        'conceptuales': ['Escala cromática. Escala de Do Mayor en el II cuádruplo.', 'Arpegios de cuatro notas con 3 dedos: p-i-m-i, p-m-i-m, p-i-m-i-p-m-i-m.', 'Acordes de La menor. Escala de La menor natural y armónica. Acordes de 4 notas en Mi menor. Arpegios ascendentes de 4 notas seguido de acordes.', 'Escala de Fa Mayor. Escala de Re menor natural y armónica.', 'Ligados ascendentes y descendentes de 2 notas.', 'Acordes y escala de La Mayor, Re Mayor, Do Mayor y Sol Mayor.', 'Punteo simple y punteo redondo.', 'Escala cromática en el 1er cuádruplo, valores de negras y corcheas.', 'Estudio con movimiento alternado de pulgar con i y m simultáneos.', 'Inicio de la barra o ceja, medias barra.', 'Tono de Do Mayor y de La menor: posiciones y escala.', 'Ritmo de merengue. Canciones y villancicos. Improvisación.'],
        'procedimentales': ['Identifica las notas musicales en el diapasón de la guitarra y en el II cuádruplo.', 'Realiza las escalas en el II cuádruplo.', 'Ejecuta la escala cromática en tiempo de negras y corcheas.', 'Ejecuta escalas mayores y menores.', 'Interpreta los estudios y piezas en tiempos lentos con calidad e intensidad del sonido.', 'Realiza ejercicios técnicos del pulgar, alternando con i y m simultáneos.', 'Ejecuta ejercicios de ligados ascendentes y descendentes en tiempos lentos y relajado.', 'Lee y acompaña un fragmento musical.', 'Puntea e improvisa sobre un tema musical de corte popular.'],
        'actitudinales': ['Actitud responsable y dedicación.', 'Sensibilidad ante la música.', 'Concentración.', 'Responsabilidad hacia el trabajo en equipo.'],
    },
    'Instrumento II - Teclado': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '4',
        'elemento_competencia': 'Emplea los conocimientos adquiridos para profundizar en la técnica básica del piano-teclado e iniciar la ejecución de escalas mayores y menores según el orden del ciclo musical de quintas con arpegios y acordes fundamentales y afianzar la independencia de manos y dedos; interpreta un repertorio de obras breves seleccionado del acervo tradicional universal con ritmo estable, incluye estudios de mayor extensión, una obra en formato de 3 partes (tripartita) y una obra polifónica breve aplicando el carácter de las obras y los elementos de la expresión musical.',
        'rae': ['Reconoce las características del sonido.', 'Ejecuta el repertorio seleccionado para el nivel con piezas de 8-12 compases, con independencia de sus manos y mejor articulación de sus dedos.', 'Ejecuta el fraseo, emplea los matices y aplica los elementos de la expresión en la ejecución musical.', 'Toca las escalas de Do y Sol mayores y las escalas menores de La y Mi menores con manos juntas en movimiento paralelo, acordes y arpegios fundamentales de 3 notas.', 'Identifica auditivamente y ejecuta los intervalos de 3ra mayor y menor, toca los arpegios y acordes de 3 notas, mayores y menores.', 'Conoce los principales periodos de la historia de la música, compositores y obras más relevantes.', 'Ejecuta un repertorio de piezas aplicando los matices y el fraseo musical en su interpretación.', 'Aplica el carácter de las piezas logrando el realce y belleza de las mismas.', 'Ejecuta los ejercicios técnicos: escala de Re Mayor a 2 octavas, escala de Si menor a 1 octava y terceras dobles de Do y Sol mayores a 1 octava.', 'Toca una obra sencilla acompañando un instrumento solista como el violín, clarinete o flauta.'],
        'conceptuales': ['El sonido y sus características.', 'Periodos más importantes de la historia de la música: barroco, clásico, romántico y moderno. Principales compositores y obras.', 'El fraseo y las expresiones musicales.', 'Los intervalos y las distancias de los sonidos: tonos y semitonos.', 'Intervalos de 3ra mayor y menor. Acordes mayores y menores.', 'Escalas de Do y Sol mayores, arpegios y acordes fundamentales.', 'Terceras dobles de Do mayor.', 'Escala relativa menor natural.', 'Escalas de La y Mi menor natural, arpegios y acordes.', 'Repertorio de obras sencillas de 8 y 12 compases escogidas para su nivel.', 'Cruce de manos en el teclado.', 'Autores y compositores de las piezas. La melodía y el acompañamiento.', 'La respiración profunda y la relajación de brazos, codos, manos y dedos.', 'El hábito de la lectura musical a primera vista.', 'La melodía y otros planos sonoros: polifonía (varias voces).', 'Escalas de Re Mayor a 2 octavas y Si menor natural a 1 octava. La escala cromática.', 'Aplica los matices: f, mf, p y mp.', 'El carácter en las obras: Andante, Moderato y Allegro.'],
        'procedimentales': ['Autocontrol en la ejecución de escalas y acordes.', 'Aplica los conocimientos adquiridos en la interpretación de sus piezas.', 'Completa el estudio del repertorio seleccionado para su nivel.', 'Dominio de la acción psicomotriz en sus dedos, logrando más claridad y vigor en su toque.', 'Destreza y agilidad con una inversión de mayor tiempo de estudio y práctica sistemáticos.', 'Orden y preservación de las partituras de su repertorio.'],
        'actitudinales': ['Cumple con las tareas asignadas.', 'Atiende las indicaciones de su profesor-a.', 'Disciplina, respeto y camaradería.', 'Cuida su instrumento y accesorios.', 'Escucha las interpretaciones de sus compañeros.', 'Se integra al trabajo en equipo.', 'Comparte los conocimientos adquiridos.'],
    },
    'Instrumento II - Viento': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '4',
        'elemento_competencia': 'Ejecuta un instrumento musical de la familia de viento madera y metal desarrollando la técnica básica en los registros central y grave fundamentada en la correcta posición de los brazos y manos, respiración costo-diafragmática, ataque del sonido y digitación participando en actividades escolares, religiosas, deportivas y otras de igual carácter, interpretando frases musicales de 8 compases o más de estructura formal simple con un grado de dificultad de (0.5 a 1.5) basados en el uso de diferentes compases, tempos y figuras musicales (redonda, blanca, negra y corchea) en obras del repertorio universal, haciendo énfasis en composiciones de origen folclórico y popular dominicano y latinoamericano.',
        'rae': ['Identifica las partes del instrumento musical seleccionado y su función, para su cuidado y mantenimiento.', 'Ejecuta un instrumento de la familia de viento madera y metal en actividades escolares, deportivas, religiosas y otras de igual carácter, apreciando la importancia del papel que desempeña como instrumentista.', 'Aplica la técnica básica para la ejecución de un instrumento de la familia de viento madera y metal en las actividades programadas, logrando una correcta afinación y digitación en los registros central y grave.', 'Ejecuta con precisión y fluidez el instrumento que estudia en la interpretación de frases musicales de 8 compases, dos frases o más de estructura formal simple en los registros central, grave y agudo (canciones, danzas y marchas) con un orden de dificultad de (0.5 a 1.5) del repertorio universal, con énfasis en composiciones de origen folklórico y popular dominicano y latinoamericano.', 'Identifica la importancia del papel que desempeña cuando ejecuta el instrumento de la familia de viento madera y metal seleccionado en los registros central, grave y agudo.', 'Participa en las actividades programadas con respeto y disposición para realizar las tareas.'],
        'conceptuales': ['Función del estudiante en la ejecución de frases musicales de 8 compases o más de estructura simple con dificultad de (0.5 a 1) basados en el uso de diferentes compases, tempos y figuras musicales.', 'Importancia del estudio técnico del instrumento.', 'Estructuras formales musicales simples.', 'Importancia de la interpretación de obras del repertorio musical universal y de origen folclórico y popular dominicano y latinoamericano.', 'Importancia de la música instrumental en la educación estética del pueblo.', 'Calidad tímbrica del sonido.', 'Función del instrumento que estudia en las obras que interpreta.', 'Características e importancia de los distintos tipos de actividades musicales.', 'Repertorio universal y de origen folclórico y popular dominicano y latinoamericano.'],
        'procedimentales': ['Ejecuta la técnica básica del instrumento seleccionado de la familia de viento madera o metal fundamentado en la correcta posición de brazos y manos, emisión del sonido, respiración costo-diafragmática, afinación, precisión y fluidez en la emisión del sonido, digitación y postura en los registros central, grave y agudo.', 'Participa en la realización de actividades musicales escolares, religiosas, deportivas y otras de igual carácter.', 'Interpreta frases musicales de 8 compases, dos o más, de estructura formal simple de un grado de dificultad de (0.5 a 1) basados en el uso de diferentes compases, tempos y figuras musicales del repertorio universal, así como las de origen folclórico y popular dominicano y latinoamericano.'],
        'actitudinales': ['Cuidado y mantenimiento del instrumento seleccionado para su estudio.', 'Responsabilidad en el cumplimiento de las tareas asignadas.', 'Cumple con los deberes de estudio.', 'Mantiene buenas relaciones éticas con sus compañeros y profesores, lo que le ayuda al desarrollo de los valores de justicia y equidad.', 'Valora estéticamente las obras musicales por él interpretadas, lo que contribuye al desarrollo de su autoestima.'],
    },
    'Instrumento II - Percusión': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '4',
        'elemento_competencia': 'Ejecuta instrumentos musicales de la familia de la percusión clásica de sonido indeterminado y latina desarrollando la técnica básica fundamentada en la correcta posición de los brazos y manos, ataque del sonido y digitación, interpretando obras musicales de 8 compases y dos o más frases de estructura formal simple con un grado de dificultad de (0.5 a 1.5) basados en el uso de diferentes compases, tempos, rudimentos y figuras musicales (redonda, blanca, negra, corchea y semicorchea) en obras del repertorio universal, haciendo énfasis en composiciones de origen folclórico y popular dominicano y latinoamericano.',
        'rae': ['Interpreta con fluidez pequeños fragmentos musicales del repertorio universal, utilizando el material didáctico de nivel 0.5 a 1.5.', 'Utiliza los elementos técnico-musicales en la ejecución de los instrumentos de percusión clásicos y latinos dentro de una o varias agrupaciones (sonido, afinación, ejecución, etc.).', 'Ejecuta pequeñas piezas musicales acordes al nivel (0.5 a 1.5).', 'Mantiene y cuida los instrumentos de percusión con los utensilios adecuados.'],
        'conceptuales': ['Elementos técnicos básicos de los instrumentos de percusión clásica de sonido indeterminado (rudimentos) y de percusión latina.', 'Cuidado y mantenimiento de los instrumentos de percusión de sonido indeterminado, clásicos y latinos.', 'Ejecución de los instrumentos de percusión en grupos o ensambles.', 'Repertorio universal de nivel (0.5-1.5) acorde al programa técnico de cada instrumento de percusión clásica y latina.'],
        'procedimentales': ['Aplicación de los elementos técnicos básicos de los instrumentos de percusión clásica de sonido indeterminado (rudimentos) y latinos.', 'Utilización de los accesorios requeridos en el cuidado y mantenimiento de los instrumentos de percusión clásica de sonido indeterminado y latinos.', 'Ejecución de los instrumentos de percusión clásica y latina.', 'Ejecución de un repertorio acorde al nivel técnico del estudiante con un grado de dificultad de 0.5 a 1.5.'],
        'actitudinales': ['Responsabilidad y persistencia.', 'Acepta y cumple con las observaciones técnicas.', 'Respeta, valora y se integra al trabajo en equipo.', 'Atiende y acepta las correcciones técnicas del programa.', 'Comparte los conocimientos adquiridos.', 'Sensible a los requerimientos musicales.', 'Disposición para el estudio.'],
    },
    'Práctica Instrumental Grupal II': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '4',
        'elemento_competencia': 'Ejecuta un instrumento musical como integrante de una o más agrupaciones musicales (ensamble, grupo de cámara, conjunto o banda de música), con la utilización de los elementos técnicos básicos (respiración, emisión, sonido, afinación, postura, picado, ligado y rudimentos de la percusión), con énfasis en la agógica (ritmo-tempo), permitiendo al estudiante una mayor destreza en la ejecución grupal, interpretando pequeños fragmentos musicales al unísono y polifónicos con grado de dificultad (0.5 a 1.5), que incluye prácticas al unísono para el desarrollo y fijación de los elementos técnico-musicales trabajados en diferentes compases y tiempos, incluyendo progresivamente pequeñas piezas y fragmentos del repertorio universal con énfasis en la música latinoamericana, folklórica y popular dominicana.',
        'rae': ['Ejecuta un instrumento musical utilizando los elementos técnicos básicos en la ejecución del instrumento dentro de una o varias agrupaciones (respiración, emisión, afinación, postura, ejecución, etc.).', 'Interpreta con fluidez pequeños fragmentos musicales y piezas con mayor grado de complejidad técnico-musical del repertorio universal utilizando el material didáctico de nivel 0.5 a 1.5.', 'Ejecuta pequeñas piezas musicales acordes al nivel (0.5 a 1.5).', 'Dispone de los accesorios requeridos para el cuidado y mantenimiento del instrumento.', 'Promueve el trabajo técnico-musical por secciones y familias de instrumentos.'],
        'conceptuales': ['Elementos técnicos básicos del instrumento en las prácticas grupales (respiración, emisión, sonido, afinación, postura).', 'Balance instrumental y sonoro dentro de la agrupación.', 'Concepto rítmico de la agrupación.', 'Técnicas de ensayo por secciones y familias de instrumentos.', 'Cuidado y mantenimiento del instrumento.', 'Repertorio universal de nivel 0.5 a 1.5, acorde al programa técnico de cada instrumento.', 'Repertorio con mayor grado de dificultad técnico-musical de nivel (0.5 a 1.5).', 'Repertorio latinoamericano, folclórico y popular dominicano, acorde al nivel técnico de la agrupación.'],
        'procedimentales': ['Aplica los elementos técnicos básicos del instrumento en la práctica grupal (respiración, emisión, sonido, afinación, postura).', 'Realiza trabajo sistemático de calentamiento grupal.', 'Ejecuta variados sistemas de trabajo por secciones y familias de instrumentos.', 'Realiza diversos ejercicios rítmicos como herramienta fundamental en la práctica grupal.', 'Utiliza prácticas vocales en lectura del repertorio como soporte de la afinación.', 'Utiliza los accesorios requeridos en la ejecución, cuidado y mantenimiento del instrumento.', 'Selecciona y ejecuta un repertorio acorde al nivel de la agrupación.', 'Fomenta el liderazgo dentro de la agrupación, designando monitor, encargado de sección, responsable de repertorio, disciplina, etc.'],
        'actitudinales': ['Responsabilidad y persistencia.', 'Acepta y cumple con las observaciones técnicas.', 'Respeta y valora el trabajo en equipo.', 'Atiende y acepta las exigencias del programa.', 'Comparte los conocimientos adquiridos.', 'Sensible a los requerimientos musicales.', 'Disposición para el estudio.', 'Liderazgo.'],
    },
    'Canto Coral II': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '4',
        'elemento_competencia': 'Aplica la técnica de expresión vocal y de percepción auditiva mediante la práctica de pronunciación o dicción correcta de consonantes y vocales, articulación, emisión del sonido, ejecución en compases binarios, ternarios, simples y compuestos, aplicando matices agógicos, variantes de aires o tempos rápidos, moderados y lentos y el conocimiento de los criterios que se emplean en la interpretación de repertorios, la forma musical cánon y obras corales a dos voces, enfatizando en la articulación, proyección y la seguridad en el aspecto armónico, de cada sección vocal del coro.',
        'rae': ['Aplica la técnica de la articulación para la producción correcta de vocales y consonantes.', 'Combina la buena dicción con el apoyo diafragmático y la colocación del sonido al cantar.', 'Aplica los conocimientos adquiridos de la técnica vocal en las interpretaciones de obras al unísono.', 'Canta al unísono mostrando un sonido afinado, entonado, articulado y con una buena pronunciación de vocales y consonantes.', 'Canta todas las canciones del repertorio seleccionado del nivel 2.', 'Participa con compromiso, respeto y disciplina en las actividades (ensayos parciales, generales, presentaciones) propias del coro.'],
        'conceptuales': ['Técnica para el uso del aparato fonador (dicción y articulación de consonantes y vocales) y resonador.', 'La agógica: aspectos fundamentales de la rítmica, compases binarios, ternarios, simples, compuestos, los matices, los aires o tempos.', 'Criterios para la selección del repertorio coral: efemérides, características de la agrupación coral (extensión del registro, tipos de voces que la integran), dificultades técnicas de las obras.', 'Repertorio coral al unísono con criterio claro de la entonación y la afinación.', 'Técnica para la articulación al cantar.', 'Técnica de proyección de la voz en combinación con la relajación.', 'Vocalizaciones al unísono y a 2 voces.', 'Aspecto armónico vocal: interpretación de obras corales armonizadas a 2 partes o voces.', 'Aspecto armónico vocal: interpretación de obras corales de la forma musical cánon a 2, 3 y 4 partes.', 'Refuerzo de respiración costal-diafragmática, entonación, afinación, dicción, matices agógicos.'],
        'procedimentales': ['Usa el triángulo vocálico para la producción de las vocales puras.', 'Realiza los ejercicios técnicos de vocalización con consonantes resonantes, explosivas y fricativas, utilizando cambios de tempos.', 'Interpreta ejercicios de vocalización y/o canciones cortas en compases binarios, ternarios, simples, compuestos, aplicando cambios en la agógica.', 'Analiza la lírica, la extensión del registro y las dificultades técnicas de la obra, a fin de seleccionar el repertorio apropiado para el coro escolar.', 'Ejecuta ejercicios de vocalización (articulación) frente al espejo.', 'Realiza ejercicios técnicos de vocalización con las consonantes M, P, R y T, los cuales favorecen la proyección del sonido.', 'Realiza ejercicios con combinación de vocales a 2 voces, en enlaces armónicos de I-IV-I y I-V-I.', 'Canta repertorio de obras seleccionadas de la forma cánon y arreglos a 2 voces, enfatizando la articulación y proyección vocal, la respiración costal-diafragmática, entonación, afinación, dicción y la agógica.'],
        'actitudinales': ['Se integra al trabajo en equipo.', 'Tolera a sus compañeros.', 'Cumple con las normas disciplinarias del canto coral.', 'Desarrolla su capacidad de análisis.', 'Se esfuerza para aplicar los conocimientos.', 'Interioriza y toma conciencia de la importancia de la dicción y la articulación.', 'Acepta las correcciones técnicas y de actitud frente al trabajo.', 'Fomenta el autocontrol.'],
    },
    'Refuerzo Sonoro': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '2',
        'elemento_competencia': 'Organiza la amplificación sonora de un evento, con duración de 2 horas, realizado bajo techo y al aire libre, utilizando los instrumentos y equipamiento necesario dependiendo de la cantidad del público.',
        'rae': ['Organiza el proceso de sonorización de un evento y define el orden de instalación de los equipos.', 'Realiza el diseño de amplificación identificando los equipos necesarios para realizar un correcto refuerzo sonoro, analizando las variables relativas a las condiciones de la sala, tamaño del público y charlistas, vocalistas o instrumentistas.', 'Coloca y conecta los equipos en los lugares estratégicos definidos en el diseño.', 'Aplica los conceptos básicos de refuerzo sonoro basados en el funcionamiento y capacidades de la consola, funcionamiento del paneo, pre-amplificación, capacidad de amplificación, parlantes y micrófonos, para lograr un balance de volúmenes adecuado.', 'Conecta los equipos de reforzamiento sonoro: cables de audio, cables de micrófono, reproductor de audio o video y las bocinas y monitores a la consola.', 'Selecciona el micrófono adecuado a cada instrumento observando los patrones polares, la necesidad de alimentación de energía y las condiciones acústicas de la sala o escenario.', 'Aplica la ganancia necesaria de acuerdo al instrumento o voz consiguiendo un balance entre este y los demás instrumentos de la agrupación.', 'Logra claridad y definición a cada instrumento, voz o familia de instrumentos utilizando los métodos de ecualización básicos.', 'Consigue espacialidad aplicando retardo y/o la reverberación adecuada a cada instrumento, y conoce la capacidad de potencia y los requerimientos de alimentación eléctrica del equipo que maneja.'],
        'conceptuales': ['Propiedades del sonido: altura o tono, intensidad, timbre y duración.', 'Umbral de sensación sonora, umbrales de malestar o molestia, presión sonora para diferentes frecuencias.', 'La frecuencia (Hz y kHz) y el refuerzo sonoro.', 'El decibelio o decibel (dB), el decibelímetro y curvas de medición dBA y dBC.', 'Medición y suma de la potencia acústica (intensidad).', 'Funcionamiento básico del micrófono dinámico: colocación en las distintas familias de instrumentos o voces, manejo en el escenario, diagrama polar, técnicas microfónicas de campo cercano.', 'Funcionamiento básico de los parlantes, sus partes y características.', 'Características físicas y técnicas de los conectores y cables XLR y TR.', 'Funcionamiento de la consola: secciones de pre-amplificación, ecualización, paneo y niveles.', 'El amplificador de potencia: su capacidad y consumo eléctrico. Partes y conectores de la medusa.', 'El micrófono de condensador y los patrones polares, uso y aplicación.', 'Función de la ecualización y métodos de ecualización básicos para instrumentos de viento-metal, viento-madera, cuerdas y percusión.', 'El reverb o reverberación, el compresor de audio y el concepto de "unity gain". Las consolas digitales.'],
        'procedimentales': ['Identifica y clasifica sonidos en agudos, medios y graves, fuertes o suaves.', 'Identifica instrumentos y voces por su timbre.', 'Interpreta mediciones acústicas realizadas con el decibelímetro o sonómetro y selecciona las curvas de ponderación A y C.', 'Realiza diseños básicos para la colocación de micrófonos, parlantes (PA) y monitores.', 'Define el orden de instalación de los diversos equipos.', 'Identifica los amplificadores de potencia y conecta los parlantes.', 'Analiza las diferentes secciones de la consola.', 'Identifica cada micrófono y selecciona el patrón polar necesario según el instrumento a amplificar.', 'Conecta y desconecta todos los cables de la medusa y coloca los faders en unity gain.', 'Ecualiza instrumentos y secciones (viento-madera, viento-metal, cuerdas, percusión) y realiza la compresión de un instrumento o una voz.'],
        'actitudinales': ['Respeta y valora el trabajo en equipo.', 'Cuida y da mantenimiento a los equipos siguiendo las indicaciones del fabricante durante el tiempo del evento.', 'Coloca los equipos de forma ordenada, estética y lógica.', 'Desmonta y guarda los equipos utilizados en el evento.'],
    },
    'Teoría y Entrenamiento Musical II': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '3',
        'elemento_competencia': 'Integra, argumenta, sistematiza y demuestra los conocimientos adquiridos, en la evidencia de la interrelación del alumno con sus compañeros en la utilización del nuevo lenguaje musical, lo que conlleva a un mayor disfrute estético y comprensión de la música.',
        'rae': ['Reconoce e identifica audio-visualmente los conceptos, símbolos, grafías y otros elementos del lenguaje musical en fragmentos y partituras musicales escritas.', 'Ejecuta en forma entonada piezas con diferentes grados de dificultad.', 'Reproduce oralmente y memoriza fragmentos rítmicos.', 'Compone fragmentos melódicos para voces o instrumentos (flauta dulce) utilizando todos los conocimientos teóricos adquiridos en la materia.', 'Entona lecciones sencillas a dos voces.', 'Ejecuta la lectura a primera vista.', 'Demuestra una actuación responsable en las habilidades físicas, motoras y emocionales en función del nuevo lenguaje aprendido a través de la rigurosidad de la enseñanza.'],
        'conceptuales': ['Las claves de Sol y Fa en 4ta línea. Notas y figuras. Alteraciones. Armadura de clave (escalas, intervalos, ritmos, compases simples y compuestos, signos de repetición, signos de dinámica).', 'Contenido teórico: los nuevos conocimientos se van adicionando a los ya adquiridos.', 'Signos y términos de la música en su relación con las cualidades del sonido.', 'Registros, sonidos, pentagrama, claves de Sol y Fa en 4ta línea.', 'Intervalos melódicos de 2das, 3ras, 6tas y 7mas mayores y menores, 4tas, 5tas y 8vas justas, ascendentes y descendentes.', 'Armadura de clave (con 7 alteraciones). Orden de los sostenidos y los bemoles.', 'Métrica: compases simples (denominador 2, 4 y 8), compases compuestos (denominador 8).', 'Ritmo: figuras de notas y silencios, valor absoluto y relativo de las figuras (desde la redonda hasta la semicorchea), combinaciones rítmicas, polirritmias.', 'Dinámica: matices de Pianissimo (pp) hasta Fortissimo (ff), reguladores, acentos.', 'Signos de repetición: todos los anteriores.'],
        'procedimentales': ['Lee a primera vista entonadamente un fragmento musical.', 'Crea melodías y ritmos con los conocimientos adquiridos para flauta dulce o voz.', 'Memoriza melodías y ritmos con un nivel más elevado de complejidad.', 'Entona lecciones sencillas a dos voces.'],
        'actitudinales': ['Actitud responsable y emprendedora.', 'Creatividad.', 'Compromiso ético.', 'Amor hacia la música y las artes en general.'],
    },
    'Armonía II': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '2',
        'elemento_competencia': 'Analiza las tonalidades para la creación de acompañamientos en distintas melodías, empleando elementos del cifrado tradicional o popular en forma sencilla, así como construir acordes a pequeñas piezas del material de estudio integrando correctamente los distintos tipos de cadencias estudiadas.',
        'rae': ['Reconoce, identifica y construye acordes mayores y menores.', 'Reconoce en forma escrita y auditiva las cadencias perfecta y plagal.', 'Lee cifrados tradicionales y anglosajón o popular en forma entonada.', 'Realiza acompañamientos armónicos de melodías empleando elementos del cifrado tradicional y anglosajón o popular en forma sencilla.'],
        'conceptuales': ['Intervalos armónicos. Consonancias y disonancias. Utilización de intervalos armónicos en melodías sencillas, así como tríadas y sus inversiones. Cadencia perfecta o auténtica (V-I). Cadencia plagal (IV-I).', 'Contenido teórico y práctico.', 'Intervalos armónicos: consonancias perfectas e imperfectas, disonancias. Tríadas mayores, menores, aumentadas y disminuidas: inversión, construcción y reconocimiento audio-visual. Cifrados tradicionales y anglosajón (alfabético). Reconocimiento auditivo. Cadencias auténtica y plagal.', 'Cifrado anglosajón o por letras. Cifrados tradicionales (por grados). Reconocimiento audio-visual y entonación.'],
        'procedimentales': ['Reconoce audio-visualmente los signos y términos de la música.', 'Construye distintos tipos de tríadas y sus inversiones y cadencias auténtica y plagal.', 'Crea acompañamientos simples a melodías y canciones.'],
        'actitudinales': ['Actitud responsable y emprendedora.', 'Creatividad.'],
    },
    'Historia de las Formas Musicales': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '2',
        'elemento_competencia': 'Caracteriza las distintas piezas musicales seleccionadas del repertorio universal, a partir de los siguientes elementos: compositor y su nacionalidad, periodo estilístico, época, medios sonoros, forma musical o género y las características técnico-estilísticas que las definen, a partir del siglo XVIII hasta el siglo XX en Europa.',
        'rae': ['Reconoce audio-visualmente instrumentos, agrupaciones instrumentales y vocales, así como obras representativas del periodo comprendido entre el siglo XVIII y el XX.', 'Desarrolla la memoria perceptual que le permita analizar estéticamente las manifestaciones musicales utilizando la terminología propia de la asignatura.', 'Integra el estudio multilateral de la música y su desarrollo social histórico en su vínculo con las demás manifestaciones artísticas.', 'Evidencia una posición crítica dentro de su entorno natural y social como espectador o como ejecutante.', 'Caracteriza las obras musicales a escuchar mediante un informe oral y/o escrito utilizando los elementos estilísticos que la definen.', 'Compara audio-visualmente las características técnico-estilísticas de cada periodo.', 'Identifica las formas musicales de cada periodo estilístico y su evolución histórica.', 'Estudia breves datos de la vida y obra de compositores representativos de cada periodo estilístico.'],
        'conceptuales': ['Conocimiento del surgimiento y desarrollo de la música en su relación con las demás manifestaciones artísticas.', 'La música: origen y desarrollo hasta el siglo XVIII en Europa.', 'Poder expresivo y carácter social de la música desde su surgimiento en la vida del ser humano.', 'La Prehistoria y la Antigüedad. La música en las grandes civilizaciones antiguas: Mesopotamia, Egipto, Palestina, Grecia y Roma.', 'La Edad Media: la monodia religiosa (canto gregoriano), el arte trovadoresco, el Ars Antiqua (surgimiento de la polifonía), principales representantes (Leonin y Perotin), instrumentos utilizados.', 'El Renacimiento: principales representantes (Orlando di Lasso, Palestrina, Monteverdi; en pintura y escultura, Leonardo da Vinci, Rafael, Miguel Ángel).', 'Formas musicales trabajadas: misa, oratorio, madrigal.', 'El Barroco: características generales, formas musicales (suite, concierto solista, concerto grosso, fuga), principales compositores (Vivaldi, Corelli, Handel, Bach).', 'La música europea desde el siglo XVIII hasta algunas tendencias del siglo XX.', 'El Clasicismo: el Iluminismo y la Ilustración, características técnico-estilísticas del periodo clásico, principales compositores (Haydn, Mozart, Beethoven), la orquesta sinfónica clásica.', 'El siglo XIX: el Romanticismo y el Nacionalismo, la ópera, compositores románticos (Paganini, Schumann, Chopin, Schubert, Mendelssohn, Chaikovski, Liszt), nacionalistas (el Grupo de los Cinco, Smetana, Grieg) y postrománticos (Brahms, Wagner), el Impresionismo musical (Debussy, Ravel).'],
        'procedimentales': ['Reconoce audio-visualmente los momentos históricos y sociales del desarrollo musical basado en las características técnico-estilísticas desde la Prehistoria hasta el Barroco.', 'Integra los elementos estudiados para un análisis formal sencillo de las obras musicales.', 'Realiza análisis críticos adecuados ante la audición de diversos ejemplos musicales de diferentes épocas.', 'Estudia datos biográficos de las figuras más representativas del arte y la música de los diferentes periodos de la historia.', 'Reconoce audio-visualmente los momentos históricos y sociales del desarrollo musical basado en las características técnico-estilísticas desde el Clasicismo hasta la música del siglo XX.'],
        'actitudinales': ['Actitud responsable y emprendedora.', 'Creatividad.', 'Amor por la música y las artes en general.'],
    },
    'Instrumento III - Guitarra': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '5',
        'elemento_competencia': 'Ejecuta la guitarra, para interpretar repertorio del compositor Leo Brouwer, aplicando la correcta articulación, legato y estacato así como la técnica de acompañamiento, utilizando las progresiones armónicas con acordes simples y compuestos, cifrados y nuevos acordes y esquemas de acompañamiento de los distintos géneros y ritmos musicales.',
        'rae': ['Ejecuta la guitarra para interpretar repertorio del compositor Leo Brouwer, aplicando y desarrollando la técnica de la articulación, legato, fraseo y estacato.', 'Interpreta los Estudios Sencillos de Leo Brouwer, aplicando correctamente los elementos técnicos propios de cada uno.', 'Interpreta los estudios y piezas del repertorio con la correcta articulación y fraseo propio del estilo de cada obra.', 'Acompaña melodías y canciones utilizando los acordes simples y compuestos.', 'Construye enlaces de acordes, utilizando el sistema de cifrado musical como herramienta para acompañar melodías y canciones.', 'Acompaña melodías y canciones utilizando los esquemas de acompañamiento de los distintos géneros y ritmos de música popular (huapango, chacarera, carnavalito, joropo, son, merengue, valses, rancheras, boleros, baladas, etc.).'],
        'conceptuales': ['Estudios Sencillos de la Primera Serie de Leo Brouwer.', 'Estudios y piezas. Fórmulas de acordes y progresiones. Técnicas de acompañamiento.', 'Acordes simples y compuestos. Canciones en los tonos de Do, Re, La y Mi mayor y La y Mi menor.', 'Cifrado musical A-B-C-D-E-F-G. Acordes mayores y menores, de 7ma y 9na en cifrado musical.', 'Acordes y sus familias (dominante, menor, aumentada, disminuido, menor 7ma, sexta, novena, séptima mayor, sexta menor, 4ta suspendida menor 7ma con 5ta en menor), por cada nota de la escala cromática.', 'Esquemas de acompañamiento con rasgueados o rayados: huapango (México), chacarera (Argentina), carnavalito (Bolivia), joropo (Venezuela), son (Cuba), vals venezolano, vals peruano, ranchera, bolero, balada, canción, merengue.'],
        'procedimentales': ['Desarrolla la práctica de la articulación, legato y estacato especialmente en estudios y piezas.', 'Mantiene el control de la intensidad del sonido dentro de la dinámica y matices.', 'Amplía el concepto y práctica del fraseo y vibrato propio de cada estilo en estudios, piezas clásicas y populares.', 'Desarrolla la técnica de acompañamiento, utilizando las progresiones armónicas con acordes simples y compuestos.', 'Aplica el conocimiento del cifrado musical.', 'Ejecuta con el sistema de cifrado musical los acordes mayores, menores, aumentados, disminuidos y de séptima.', 'Acompaña distintos ritmos, melodías y canciones utilizando rasgueado o rayados.'],
        'actitudinales': ['Actitud responsable y dedicación.', 'Sensibilidad ante la música.', 'Concentración.', 'Trabajo en equipo.'],
    },
    'Instrumento III - Teclado': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '5',
        'elemento_competencia': 'Toca el instrumento musical piano-teclado ejecutando los ejercicios técnicos, escalas mayores y menores, arpegios y la escala cromática; utiliza los conocimientos adquiridos para leer acordes cifrados e interpretar un repertorio que incluya una obra clásica, una obra latinoamericana sencilla, una pieza dominicana breve, otra para ejecutarse formando parte de un trío o cuarteto y otra del folklore nativo acompañada por instrumentos de percusión.',
        'rae': ['Conoce los ritmos y características más importantes de la música latinoamericana, compositores más relevantes y obras.', 'Interpreta una pieza con lectura basada en acordes cifrados. Toca una pieza sencilla como parte de un trío o cuarteto.', 'Toca de memoria el repertorio seleccionado de piezas y emplea el pedal de sostén cuando está indicado.', 'Ejecuta los acordes cadenciales básicos: I-IV, I-V, IV-I y V-I.', 'Toca los ejercicios técnicos seleccionados para su nivel con seguridad y precisión: escalas de Fa y Si mayores a 2 octavas y las escalas menores Re y Si a 1 octava.', 'Toca una pieza folclórica sencilla acompañada por instrumentos de percusión.', 'Interpreta una obra sencilla del periodo clásico.', 'Ejecuta una pieza popular dominicana escrita y reconocida de libre elección (merengue, bachata, bolero, criolla o mangulina).', 'Participa e interpreta el repertorio seleccionado en el recital de graduación con un toque musical fluido, buen ritmo, seguridad y elegancia.'],
        'conceptuales': ['El dominio técnico del teclado y el desarrollo auditivo como herramientas básicas para alcanzar una ejecución musical con claridad, seguridad y destreza.', 'El rol del intérprete como solista o como parte de un grupo.', 'La música latinoamericana: ritmos y características, compositores más destacados, sus obras y épocas.', 'Lectura de partitura con cifrado. El uso del pedal para sostener el sonido en la interpretación musical.', 'Las cadencias y su función en la música.', 'El teclado como instrumento armónico base para formar dúos, tríos, cuartetos y otros.', 'Escalas La y Mi mayores en movimiento paralelo a 2 manos y 2 octavas. Tríadas disueltas, arpegios y acordes.', 'Escala cromática a una octava, manos separadas. Arpegios de 4 notas.', 'Repertorio: piezas y estudios escogidos del acervo universal, una obra latinoamericana, una pieza dominicana breve y otra para ejecutarse en trío o cuarteto.', 'El desarrollo de la sensibilidad, expresividad y musicalidad. La importancia de lograr un nivel de calidad interpretativa y madurez en el dominio de su repertorio.', 'Escalas mayores de digitación irregular (Fa y Si a 2 octavas, acordes y arpegios) y escalas de Re y Si menores (natural, armónica y melódica) a 1 octava.', 'Los compases ternarios y su uso en la música dominicana: la mangulina, la criolla y otros ritmos.', 'Repertorio de piezas con estudios, una obra clásica, una pieza popular dominicana de libre elección y una pieza del folclore nacional acompañada por percusión.'],
        'procedimentales': ['Agilidad y seguridad en la ejecución de los ejercicios técnicos con la inversión de mayor tiempo y esfuerzo de estudio sistemático.', 'Rapidez y efectividad en la instalación y colocación de su instrumento.', 'Sentido crítico, valorando y apreciando las presentaciones a las que asiste.', 'Destreza y fluidez musical en la ejecución musical.', 'Posición correcta, agilidad y control en la ejecución de los ejercicios técnicos.', 'Conoce los requerimientos técnicos para su presentación.'],
        'actitudinales': ['Respeto y trato afable con los demás.', 'Cumple sus tareas, prácticas y horarios de ensayo.', 'Colabora con su equipo de trabajo.', 'Cuida su instrumento, partitura y accesorios.', 'Aplica las directrices de su profesor.', 'Participa activamente en recitales y presentaciones.'],
    },
    'Instrumento III - Viento': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '5',
        'elemento_competencia': 'Ejecuta un instrumento musical de la familia de viento madera y metal desarrollando la técnica básica en los registros central, grave y agudo con mayor seguridad en los sonidos extremos, fundamentada en la correcta posición de los brazos y manos, intensificación de la respiración costo-diafragmática y mayor ligereza en el ataque del sonido y digitación, interpretando 2 ó más periodos musicales de estructura formal simple (danzas, marchas y canciones) y compuesta (oberturas, popurrí, sonatinas y concertinos) con un grado de dificultad de (1.5 a 2.5) basados en el uso de diferentes compases, tempos y figuras musicales, del repertorio universal, haciendo énfasis en composiciones de origen folclórico y popular dominicano y latinoamericano.',
        'rae': ['Identifica la importancia del papel que desempeña en la ejecución de un instrumento seleccionado de la familia de viento madera y metal en los registros central, grave, agudo y sonidos extremos.', 'Identifica las partes del instrumento musical que ejecuta para su cuidado y mantenimiento.', 'Aplica la técnica básica para la ejecución de un instrumento de la familia de viento madera y metal en las actividades programadas.', 'Ejecuta con seguridad y precisión el instrumento que estudia en la interpretación de obras de estructura formal simple y compuesta de 2 ó más periodos, con un orden de dificultad de (1.5 a 2.5) en los registros central, grave, agudo y extremos.', 'Participa en las actividades programadas con respeto y disposición para realizar las tareas.', 'Aplica la técnica básica para la ejecución de un instrumento seleccionado de la familia de viento madera y metal, mostrando equilibrio sonoro en los registros y ligereza en la digitación, lo que le posibilita interpretar el fraseo correcto a través del cual expresa la belleza estética de las obras.'],
        'conceptuales': ['Importancia de la actividad musical en la educación estética del pueblo.', 'Calidad tímbrica del sonido en los distintos registros.', 'Papel que desempeña el estudiante de los instrumentos de viento madera y metal en la ejecución de obras de estructura simple y compuesta.', 'Características de los géneros musicales que interpreta. Importancia del papel que desempeña como intérprete de obras musicales como solista.', 'Repertorio universal de obras de estructura simple y compuesta con énfasis en composiciones de origen folklórico y popular dominicano y latinoamericano.'],
        'procedimentales': ['Ejecuta la técnica básica del instrumento de la familia de viento madera y metal seleccionado para su estudio en los registros central, grave, agudo y sonidos extremos, fundamentada en la emisión del sonido, respiración costo-diafragmática, ataque, posición de los brazos y dedos y digitación.', 'Participa como ejecutante de un instrumento seleccionado de la familia de viento madera y metal en la realización de actividades musicales, y como solista.', 'Interpreta obras musicales de 2 ó más periodos de estructura formal simple (canciones, danzas y marchas) y compuestas (oberturas, popurrí, sonatinas y concertinos) con un grado de dificultad de (1.5 a 2.5) del repertorio universal, así como las de origen folklórico y popular dominicano y latinoamericano.'],
        'actitudinales': ['Cuidado y mantenimiento del instrumento.', 'Responsabilidad en el cumplimiento de las tareas asignadas.', 'Cumple las observaciones técnicas orientadas por el profesor.', 'Atiende las normas éticas exigidas por el programa de estudio.', 'Comparte con sus compañeros de estudio los conocimientos adquiridos y sus experiencias.', 'Respeta a sus compañeros y profesores lo que ayuda al desarrollo de los valores de justicia y equidad.', 'Cuida de su presencia escénica (vestuario, limpieza del instrumento, etc.), lo que contribuye al desarrollo de su autoestima.'],
    },
    'Instrumento III - Percusión': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '5',
        'elemento_competencia': 'Ejecuta instrumentos musicales de la familia de la percusión clásica de sonido indeterminado y de sonido determinado, percusión latina y batería, desarrollando la técnica básica, fundamentada en la correcta posición de los brazos y manos, uso de dinámicas y mayor precisión en el ataque del sonido y digitación, interpretando como solista 2 ó más estilos musicales de estructura formal simple (danzas, marchas y canciones) y compuesta (oberturas, popurrí, sonatinas y concertinos) con un grado de dificultad de (1.5 a 2.5) basados en el uso de diferentes compases, tempos y figuras musicales, del repertorio universal, haciendo énfasis en composiciones de origen folclórico y popular dominicano y latinoamericano.',
        'rae': ['Utiliza correctamente los elementos técnico-musicales en la ejecución de los instrumentos de percusión clásica de sonido indeterminado y de sonido determinado, percusión latina y batería, dentro de una o varias agrupaciones.', 'Interpreta piezas con mayor grado de complejidad técnico-musical de nivel 1.5 a 2.5, con énfasis en el repertorio latinoamericano, folclórico y popular dominicano.', 'Ejecuta el cuidado y mantenimiento de los instrumentos musicales de percusión clásica, latina y la batería.'],
        'conceptuales': ['Elementos técnico-musicales en la ejecución de los instrumentos de percusión clásica de sonido indeterminado y de sonido determinado, percusión latina y batería.', 'Repertorio con mayor grado de dificultad técnico-musical de nivel 1.5 a 2.5.', 'Sonoridad y control rítmico dentro de la sección de percusión.', 'Repertorio latinoamericano, folclórico y popular dominicano.', 'Cuidado y mantenimiento del instrumento.'],
        'procedimentales': ['Aplicación de los elementos técnico-musicales en la ejecución de los instrumentos de percusión clásica de sonido indeterminado y de sonido determinado, percusión latina y batería.', 'Selección e interpretación de un repertorio con mayor grado de dificultad técnico-musical (1.5 a 2.5).', 'Interpretación de repertorio latinoamericano, folclórico y popular dominicano.', 'Utilización de los accesorios requeridos para la ejecución y mantenimiento del instrumento.'],
        'actitudinales': ['Responsabilidad y persistencia.', 'Acepta y cumple con las observaciones técnicas.', 'Respeta y valora el trabajo en equipo.', 'Atiende y acepta las exigencias del programa.', 'Comparte los conocimientos adquiridos.', 'Sensible a los requerimientos musicales.'],
    },
    'Práctica Instrumental Grupal III': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '4',
        'elemento_competencia': 'Ejecuta e interpreta como integrante de una agrupación musical (conjunto vocal-instrumental, ensamble, conjunto de cámara, orquesta, banda de música, agrupación popular o folclórica), con la aplicación de los elementos técnicos propios de cada instrumento, enfatizando en la calidad sonora, ritmo, dinámica y la expresión musical, propiciando una mayor calidad técnico-musical en las agrupaciones, facilitando la interpretación de un repertorio con mayor grado de dificultad (nivel 1.5 a 2.5), incluyendo repertorio tradicional universal con énfasis en la música latinoamericana, folclórica y popular dominicana, para integrarse como instrumentista en orquestas y bandas de música escolares o aficionadas.',
        'rae': ['Utiliza correctamente los elementos técnico-musicales adquiridos para una clara y fluida ejecución del instrumento dentro de la agrupación (sonido, afinación, ejecución, etc.).', 'Interpreta piezas con mayor grado de dificultad técnico-musical (nivel 1.5 a 2.5), con énfasis en el repertorio latinoamericano, folclórico y popular dominicano.', 'Ejecuta con destreza, buen sonido y dominio de los registros el repertorio trabajado.', 'Favorece el cuidado y mantenimiento de los instrumentos musicales.', 'Dispone de los accesorios requeridos para el mantenimiento y cuidado del instrumento.'],
        'conceptuales': ['Elementos técnico-musicales en la ejecución del instrumento dentro de la práctica grupal (sonido, registro, ejecución).', 'Sonoridad, balance sonoro y control rítmico dentro de la agrupación.', 'Repertorio con mayor grado de dificultad técnico-musical de nivel 1.5 a 2.5.', 'Repertorio latinoamericano, folclórico y popular dominicano.', 'Cuidado y mantenimiento del instrumento.'],
        'procedimentales': ['Aplica los elementos técnico-musicales del instrumento en la práctica grupal (sonido, registro, ejecución).', 'Realiza plan de trabajo que contemple ejercicios sistemáticos de calentamiento grupal (respiración, emisión, afinación, escalas, etc.).', 'Programa y mantiene el trabajo de obras que desarrollen el balance sonoro de la agrupación.', 'Mantiene el trabajo técnico y del repertorio por secciones y familias de instrumentos.', 'Selecciona e interpreta un repertorio con mayor grado de dificultad técnico-musical (1.5 a 2.5).', 'Interpreta repertorio latinoamericano, folclórico y popular dominicano.', 'Utiliza los accesorios requeridos para la ejecución y mantenimiento del instrumento.', 'Fomenta el liderazgo dentro de la agrupación, designando monitor, encargado de sección, responsable de repertorio, disciplina, etc.'],
        'actitudinales': ['Responsabilidad y persistencia.', 'Acepta y cumple con las observaciones técnicas.', 'Respeta y valora el trabajo en equipo.', 'Atiende y acepta las exigencias del programa.', 'Comparte los conocimientos adquiridos.', 'Sensible a los requerimientos musicales.', 'Disposición para el estudio.', 'Liderazgo.'],
    },
    'Canto Coral III': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '3',
        'elemento_competencia': 'Interpreta obras corales con dos, tres y cuatro voces aplicando los indicadores de la dinámica musical (P, F, mP, mF, FF, reguladores, crescendo, decrescendo) y los signos de expresión y el carácter musical haciendo uso de un repertorio tanto de corte universal, popular y folklórico con respiración costal-diafragmática, manteniendo la entonación, afinación, calidad sonora y ritmo, articulando, proyectando la voz, mostrando dominio de la dicción, calidad interpretativa y expresiva, con actitud disciplinada y responsable.',
        'rae': ['Aplica la técnica para el control y calidad sonora, mostrando dominio del sonido al cantar.', 'Combina la calidad sonora con la dinámica musical.', 'Aplica los conocimientos adquiridos de la técnica vocal en las interpretaciones de obras a tres voces.', 'Canta a tres voces haciendo uso de los signos de expresión, carácter y la dinámica musical.', 'Canta todas las canciones del repertorio seleccionado del nivel correspondiente.', 'Participa con compromiso, respeto y disciplina en las actividades (ensayos parciales, generales, presentaciones) propias del coro.'],
        'conceptuales': ['Matices dinámicos: P, F, mP, mF, FF, reguladores, crescendo, decrescendo. Términos del carácter musical.', 'Control de la dinámica y la calidad sonora.', 'Aspecto armónico vocal: interpretación de obras corales armonizadas a 2 y 3 partes o voces.', 'Refuerzo de respiración costal-diafragmática, entonación, afinación, dicción, matices agógicos, articulación y proyección de la voz.', 'Aspecto armónico vocal: interpretación de obras corales armonizadas a 4 partes o voces.', 'Estructura y montaje de repertorio para concierto: motetes o madrigales, coral barroco o clásico, arreglo vocal de obra instrumental, obras latinoamericanas, obras populares y obras del folklor dominicano.', 'Fundamentos de la dirección coral.'],
        'procedimentales': ['Realiza ejercicios de vocalización en intensidades suave, media y fuerte (P, PP, mP, mF, F, FF).', 'Hace ejercicios de notas largas sobre cada vocal, para trabajar la proyección en distintas intensidades sonoras.', 'Realiza ejercicios con combinación de vocales a 2 y 3 voces, en enlaces armónicos de I-IV-I y I-V-I.', 'Monta repertorio seleccionado de obras arregladas a 2, 3 y 4 voces, enfatizando la aplicación de las competencias adquiridas en los niveles previos.', 'Realiza rutina de relajación y respiración diafragmática en sus tres fases.', 'Vocaliza al unísono, a dos y a tres voces, con triadas o acordes en estado fundamental y en sus inversiones.', 'Ensaya (parcial y general) el repertorio, dirigido por estudiantes seleccionados, con programación del ensayo, rutina de ejercicios, repaso de cada sección vocal y la dirección coral.'],
        'actitudinales': ['Se integra al trabajo en equipo.', 'Desarrolla mayor capacidad de independencia auditiva-armónica.', 'Fomenta la seguridad en sí mismo y en la línea melódica que interpreta.', 'Desarrolla la capacidad de liderazgo.', 'Tolera a sus compañeros.', 'Cumple con las normas disciplinarias del canto coral.', 'Desarrolla su capacidad de análisis.', 'Interioriza y toma conciencia de la importancia de la articulación y la proyección.', 'Acepta las correcciones técnicas y de actitud frente al trabajo.', 'Fomenta el autocontrol y la sensibilidad.', 'Muestra disciplina y nivel de compromiso.'],
    },
    'Tecnología Musical': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '2',
        'elemento_competencia': 'Digitaliza partituras de 12 a 24 compases en claves de Sol y Fa, utilizando el asistente de creación de partituras (Setup Wizard), escoge la armadura de clave, el compás, el texto y las fuentes tipográficas (fonts), además, digitaliza las partituras de 24 a 36 compases para instrumento base de acompañamiento (piano, guitarra u otro) y la línea melódica del instrumento solista o voz, con acordes, acentuaciones, expresiones y dinámicas; adquiere los rudimentos básicos sobre el proceso de edición de audio digital.',
        'rae': ['Instala una aplicación informática (software) para digitalización de partituras.', 'Ejecuta y maneja la aplicación para digitalizar y editar partituras (propietarias y de código libre).', 'Utiliza el asistente para la creación de partituras (Setup Wizard).', 'Utiliza las barras de elementos para introducir los caracteres de la notación musical.', 'Identifica y emplea las herramientas de compaginación y maquetación.', 'Imprime la partitura digitalizada.', 'Utiliza el manejador de partituras (Score Manager), para añadir instrumentos y pentagramas.', 'Utiliza las barras de elementos de notación musical, para agregar acentuaciones, dinámicas, reguladores, trinos, indicaciones de octavas y expresiones.', 'Escanea partituras musicales y las convierte a formato digital.', 'Exporta las partituras digitalizadas a formato estándar MIDI, e importa formatos MIDI a partituras.', 'Conoce diferentes aplicaciones para la edición de audio digital (WAVE o MP3).', 'Convierte formatos MIDI a formatos de audio (Wave o MP3), utilizando aplicaciones de edición de audio digital.'],
        'conceptuales': ['Instalación de una aplicación para edición de partituras en cualquier sistema operativo.', 'Aplicaciones para la edición de partituras, tanto propietarias como libres (Finale, Sibelius, Lilypond).', 'Asistente para la creación de partituras (Setup Wizard).', 'Barras de elementos de notación musical.', 'Herramientas de compaginación y maquetación (Page Layout).', 'Impresión de partituras. Manejador de partituras (Score Manager).', 'El escáner. MIDI (interfaz digital para instrumentos musicales).', 'Aplicaciones para la edición de audio y estaciones de audio digitales (DAW), tanto propietarias como libres (Pro Tools, Digital Performance, Sonar, Reason, Cubase, Audacity, Sony Sound Forge).'],
        'procedimentales': ['Instala una aplicación para la edición de partituras en cualquier sistema operativo.', 'Digitaliza partituras con agilidad y precisión.', 'Diseña y maqueta las partituras con estética y buen acabado.', 'Investiga y participa de manera dinámica en foros y grupos de discusión en línea.', 'Imprime y organiza las partituras.', 'Escudriña y analiza partituras de grandes editoras.', 'Maneja las estaciones de audio digitales (DAW).'],
        'actitudinales': ['Disciplina.', 'Cumple con las tareas asignadas.', 'Comparte los conocimientos adquiridos.', 'Acepta y aplica las instrucciones de su profesor.', 'Esmero en lograr un nivel de calidad.'],
    },
    'Dirección de Grupos Musicales': {
        'modulo': 'Bachillerato en Artes — Mención Música',
        'horas': '2',
        'elemento_competencia': 'Imparte talleres a grupos musicales infantiles en el entorno de su comunidad utilizando estrategias lúdicas y creativas a través de técnicas prácticas del aprendizaje basado en el constructivismo sociocultural.',
        'rae': ['Realiza la planeación de talleres de educación musical, fundamentado en los métodos de enseñanza musical más usados.', 'Imparte talleres musicales desarrollando las competencias de los niveles más fundamentales.', 'Valora la práctica musical y la conformación de grupos.', 'Describe las técnicas y recursos más adecuados para el taller de música.', 'Incentiva a los participantes a desarrollar su percepción auditiva a través del lenguaje sonoro cotidiano, en su relación con el juego.'],
        'conceptuales': ['Métodos de la enseñanza musical: Willems, Kodaly, Integral, Orff, Dalcroze, Suzuki.', 'La planeación de talleres.', 'Estrategias y técnicas según la edad.', 'Seguimiento individual y colectivo de los participantes.'],
        'procedimentales': ['Practica el proceso de planeación para un taller de iniciación musical.', 'Realiza talleres demostrativos en el aula.', 'Crea modelos de seguimiento (teóricos y prácticos) que respondan a distintos niveles de la enseñanza musical.', 'Elabora proyectos de acción y actividades musicales.'],
        'actitudinales': ['Fomento de actitud responsable y emprendedora.', 'Fomento de la creatividad.', 'Valor del proceso de enseñanza-aprendizaje.', 'Desarrollo del sentido de organización y previsión.', 'Desarrollo de la comunicación por medio de la expresión oral.', 'Fomento de la tolerancia y la paciencia.', 'Valora el trabajo colaborativo.'],
    },
}

ALIAS_MUSICA = {}

import re as _re
import unicodedata as _ud

def _firma_musica(s: str) -> str:
    """Firma sin acentos/espacios para búsqueda tolerante a kerning del PDF."""
    nfkd = _ud.normalize('NFKD', s)
    sin_tilde = ''.join(c for c in nfkd if not _ud.combining(c))
    return _re.sub(r'[^a-zA-Z0-9]', '', sin_tilde).lower()

_IDX_MUSICA = {_firma_musica(k): k for k in CURRICULUM_MUSICA}

# El catálogo de asignaturas (PLAN_ARTES) sólo reserva UN slot de horas por
# grado para "Instrumento I/II/III" (el estudiante cursa una única
# especialización), pero el currículo oficial desglosa el contenido por
# especialización (Guitarra/Teclado/Viento/Percusión). Si alguien busca el
# nombre genérico sin especialización, se agrega el contenido de las 4
# especializaciones de ese nivel en una sola respuesta combinada, en vez de
# devolver vacío.
_NIVEL_ROMANO = {"i": "I", "ii": "II", "iii": "III"}

def _nivel_instrumento_generico(nombre: str) -> str | None:
    firma = _firma_musica(nombre)
    if not firma.startswith("instrumento"):
        return None
    resto = firma[len("instrumento"):]
    return _NIVEL_ROMANO.get(resto)

_RE_INSTRUMENTO_ESPECIALIZACION = _re.compile(r'^Instrumento\s+(I{1,3})\s*-\s*(.+)$')

def _combinar_especializaciones_instrumento(nivel: str) -> dict:
    # Toma solo las claves "Instrumento {nivel} - <especialización>" cuyo
    # nivel romano coincide EXACTAMENTE (evita que "I" haga match parcial
    # con "II"/"III").
    claves = []
    for k in CURRICULUM_MUSICA:
        m = _RE_INSTRUMENTO_ESPECIALIZACION.match(k)
        if m and m.group(1) == nivel:
            claves.append(k)
    if not claves:
        return {}
    combinado = {"modulo": f"Bachillerato en Artes — Mención Música", "horas": CURRICULUM_MUSICA[claves[0]].get("horas", ""),
                 "elemento_competencia": CURRICULUM_MUSICA[claves[0]].get("elemento_competencia", ""),
                 "rae": [], "conceptuales": [], "procedimentales": [], "actitudinales": []}
    for campo in ("rae", "conceptuales", "procedimentales", "actitudinales"):
        vistos = set()
        for k in claves:
            especializacion = k.split(" - ")[-1] if " - " in k else k
            for item in CURRICULUM_MUSICA[k].get(campo, []):
                marcado = f"[{especializacion}] {item}"
                if item not in vistos:
                    vistos.add(item)
                    combinado[campo].append(marcado)
    return combinado

def get_asignatura_musica(nombre: str) -> dict:
    canon = ALIAS_MUSICA.get(nombre, nombre)
    result = CURRICULUM_MUSICA.get(canon) or CURRICULUM_MUSICA.get(nombre)
    if not result:
        firma = _firma_musica(nombre)
        orig_key = _IDX_MUSICA.get(firma)
        if orig_key:
            result = CURRICULUM_MUSICA.get(orig_key)
    if not result:
        nivel = _nivel_instrumento_generico(nombre)
        if nivel:
            result = _combinar_especializaciones_instrumento(nivel)
    return result or {}

def formatear_contexto_musica(nombre: str) -> str:
    d = get_asignatura_musica(nombre)
    if not d: return ""
    partes = []
    if d.get("elemento_competencia"):
        partes.append("ELEMENTO DE COMPETENCIA:\n" + d["elemento_competencia"])
    if d.get("rae"):
        partes.append("RAE (Resultados de Aprendizaje Esperados):\n" + "\n".join("- " + r for r in d["rae"]))
    if d.get("conceptuales"):
        partes.append("SABERES CONCEPTUALES:\n" + "\n".join("- " + c for c in d["conceptuales"]))
    if d.get("procedimentales"):
        partes.append("SABERES PROCEDIMENTALES:\n" + "\n".join("- " + p for p in d["procedimentales"]))
    if d.get("actitudinales"):
        partes.append("SABERES ACTITUDINALES:\n" + "\n".join("- " + a for a in d["actitudinales"]))
    return "\n\n".join(partes)
